#!/usr/bin/env bash

# Copyright 2017-2021 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cwl=$1
inputs=$2

function check_cp_cap {
  _CAP="$1"
  if [ -z "$_CAP" ]; then
        return 1
  fi

  _CAP_VALUE=${!_CAP}
  if [ -z "$_CAP_VALUE" ]; then
        return 1
  fi

  if [ ${_CAP_VALUE,,} == 'true' ] || [ ${_CAP_VALUE,,} == 'yes' ]; then
        return 0
  else
        return 1
  fi
}

if [ -z $cwl ] || [ ! -f $cwl ]; then
  echo "[ERROR] CWL file must be specified"
  exit 1
fi

if [ -z $inputs ] || [ ! -f $inputs ]; then
  if [ -z $inputs ]; then
    inputs=/tmp/inputs.yml
  fi
  python3 /toil_bin/cwl_inputs_parser.py $cwl $inputs /tmp/tmp-toil-inputs.yml
  if [ $? -ne 0 ]; then
    echo "[ERROR] Can't parse inputs"
    exit 1
  fi
fi

_batch_system=""
if check_cp_cap "CP_CAP_SGE"; then
  if [ -z "$TOIL_GRIDENGINE_PE" ]; then
    export TOIL_GRIDENGINE_PE=local
  fi
  if [ -z "$TOIL_GRIDENGINE_ARGS" ]; then
    export TOIL_GRIDENGINE_ARGS="-q main.q"
  fi

  TOIL_GRIDENGINE_STATE_POLLING_WAIT=${TOIL_GRIDENGINE_STATE_POLLING_WAIT:-30}
  _batch_system="--batchSystem=grid_engine --disableCaching --statePollingWait=$TOIL_GRIDENGINE_STATE_POLLING_WAIT"
  
  # Make sure the flush time is 1s, if it's more than that - toil will fail running qacct
  echo "[INFO] Setting up SGE accounting configuration"
  SGE_SINGLE_LINE=1 qconf -sconf > /tmp/global
  sed -i '/reporting_params/c\reporting_params accounting=true reporting=false accounting_flush_time=00:00:01 joblog=false sharelog=00:00:00' /tmp/global
  qconf -Mconf /tmp/global
  rm -f /tmp/global

  echo "[INFO] Final SGE configuration:"
  echo "       Batch system info:                     $_batch_system"
  echo "       TOIL_GRIDENGINE_ARGS:                  $TOIL_GRIDENGINE_ARGS"
  echo "       TOIL_GRIDENGINE_PE:                    $TOIL_GRIDENGINE_PE"
  echo "       TOIL_GRIDENGINE_STATE_POLLING_WAIT:    $TOIL_GRIDENGINE_STATE_POLLING_WAIT"
fi

# Create the temp dir if it is set to /common/...
mkdir -p $TMP

toil-cwl-runner $_batch_system \
                --cleanWorkDir never \
                --no-match-user \
                --no-read-only \
                --workDir=/common/workdir \
                $cwl $inputs
