#!/usr/bin/env bash

# Copyright 2017-2021 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cwl=$1
inputs=$2

function check_cp_cap {
  _CAP="$1"
  if [ -z "$_CAP" ]; then
        return 1
  fi

  _CAP_VALUE=${!_CAP}
  if [ -z "$_CAP_VALUE" ]; then
        return 1
  fi

  if [ ${_CAP_VALUE,,} == 'true' ] || [ ${_CAP_VALUE,,} == 'yes' ]; then
        return 0
  else
        return 1
  fi
}

if [ -z $cwl ] || [ ! -f $cwl ]; then
  echo "[ERROR] CWL file must be specified"
  exit 1
fi

if [ -z $inputs ] || [ ! -f $inputs ]; then
  if [ -z $inputs ]; then
    inputs=/tmp/inputs.yml
  fi
  python /toil_bin/cwl_inputs_parser.py $cwl $inputs /tmp/tmp-toil-inputs.yml
  if [ $? -ne 0 ]; then
    echo "[ERROR] Can't parse inputs"
    exit 1
  fi
fi

_batch_system=""
if check_cp_cap "CP_CAP_SGE"; then
  if [ -z $TOIL_GRIDENGINE_PE ]; then
    TOIL_GRIDENGINE_PE=$CP_CAP_SGE_PE_NAME
  fi
  if [ -z $TOIL_GRIDENGINE_ARGS ]; then
    TOIL_GRIDENGINE_ARGS="-q $CP_CAP_SGE_PE_NAME"
  fi
  _batch_system="--batchSystem=grid_engine --disableCaching=true --statePollingWait=10"
fi

toil-cwl-runner $_batch_system --preserve-entire-environment --workDir=/common/workdir $cwl $inputs
