apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cp-monitoring-srv
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        cloud-pipeline/cp-monitoring-srv: "true"
        cloud-pipeline/core-component: "Deployment"
    spec:
      nodeSelector:
        cloud-pipeline/cp-monitoring-srv: "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
        - name: cp-monitoring-srv
          image: ${CP_DOCKER_DIST_SRV}lifescience/cloud-pipeline:monitoring-service-$CP_VERSION
          imagePullPolicy: "Always"
          command: ["/init"]
          envFrom:
          - configMapRef:
              name: cp-config-global
          volumeMounts:
            - name: monitoring-srv-logs
              mountPath: /opt/monitoring/logs
      volumes:
        - name: monitoring-srv-logs
          hostPath:
            path: /opt/monitoring/logs
      imagePullSecrets:
        - name: cp-distr-docker-registry-secret
