apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cp-git-sync
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: cp-git-sync
      namespace: default
      labels:
        cloud-pipeline/cp-git-sync: "true"
    spec:
      nodeSelector:
        cloud-pipeline/cp-git-sync: "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
        - name: cp-git-sync
          image: lifescience/cloud-pipeline:api-srv-$CP_VERSION
          imagePullPolicy: "Always"
          command: ["/init-git-sync", "https://$(CP_API_SRV_INTERNAL_HOST):$(CP_API_SRV_INTERNAL_PORT)/pipeline/restapi/", "$(CP_API_JWT_ADMIN)"]
          envFrom:
          - configMapRef:
              name: cp-config-global
          volumeMounts:
            - mountPath: /opt/git-sync/logs
              name: git-sync-logs
      volumes:
        - name: git-sync-logs
          hostPath:
            path: /opt/git-sync/logs
      imagePullSecrets:
        - name: cp-distr-docker-registry-secret
    