apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cp-system-pvc
  namespace: cloud-pipeline-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: cp-system-pv
  resources:
    requests:
      storage: 500Gi
