apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: cp-system-pv
  namespace: cloud-pipeline-test
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: disk.csi.azure.com
    volumeHandle: /subscriptions/<subscription>/resourceGroups/<resource-group>/providers/Microsoft.Compute/disks/<fs-name>
