#!/bin/bash
# Copyright 2017-2021 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function validate_properties {
    local property="$1"
    local optional="$2"
    if [ -z "${!property}" ]; then
        if [ "$optional" == "true" ]; then
            echo "[warning] $property is not set"
        else
            echo "[error] $property is not set. Release notes agent could not be started"
            exit 1
        fi
    fi
}

validate_properties "CP_RELEASE_NOTES_GITHUB_TOKEN"
validate_properties "CP_RELEASE_NOTES_JIRA_BASE_64_TOKEN"
validate_properties "CP_RELEASE_NOTES_JIRA_VERSION_FIELD_ID" "true"
validate_properties "CP_RELEASE_NOTES_JIRA_GITHUB_FIELD_ID" "true"
validate_properties "CP_RELEASE_NOTES_MAJOR_CHANGE_SUBSCRIBERS_EMAILS" "true"
validate_properties "CP_RELEASE_NOTES_MINOR_CHANGE_SUBSCRIBERS_EMAILS" "true"
validate_properties "CP_NOTIFIER_SMTP_SERVER_HOST"
validate_properties "CP_NOTIFIER_SMTP_SERVER_PORT"
validate_properties "CP_NOTIFIER_SMTP_FROM"
validate_properties "CP_NOTIFIER_SMTP_USER" "true"
validate_properties "CP_NOTIFIER_SMTP_PASS" "true"

RELEASE_NOTES_LOG=$CP_RELEASE_NOTES_HOME/logs/release-notes.log
mkdir -p $(dirname $RELEASE_NOTES_LOG)
touch $RELEASE_NOTES_LOG

cd $CP_RELEASE_NOTES_HOME
java -jar release-notes-agent.jar send-release-notes &> $RELEASE_NOTES_LOG
