#!/usr/bin/env bash
# Copyright 2017-2020 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cd /orchest-images

tar -cC 'rabbitmq' . | docker load && \
tar -cC 'jupyter-server' . | docker load && \
tar -cC 'base-kernel-py' . | docker load && \
tar -cC 'auth-server' . | docker load && \
tar -cC 'jupyter-enterprise-gateway' . | docker load && \
tar -cC 'orchest-webserver' . | docker load && \
tar -cC 'memory-server' . | docker load && \
tar -cC 'celery-worker' . | docker load && \
tar -cC 'orchest-ctl' . | docker load && \
tar -cC 'orchest-api' . | docker load && \
tar -cC 'nginx-proxy' . | docker load && \
tar -cC 'update-server' . | docker load && \
tar -cC 'file-manager ' . | docker load

cd /

${ORCHEST_HOME}/orchest install \
 && ${ORCHEST_HOME}/orchest start \
 && sleep infinity
