plugins {
    id 'java'
    id 'jacoco'
    id 'org.springframework.boot' version '3.5.3'
    id 'org.sonarqube' version '2.6.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group "com.epam.pipeline"

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

bootJar {
    archiveFileName = "elasticsearch-agent.jar"
    manifest {
        attributes(
                "Implementation-Version": version)
    }
}

repositories {
    gradlePluginPortal()
    mavenCentral()
}

dependencies {

    // Core library
    implementation project(":cloud-pipeline-common:model")
    implementation(project(path: ":elasticsearch-common", configuration: "shadow"))

    configurations {
        all*.exclude module : 'spring-boot-starter-logging'
        all*.exclude group: 'commons-logging', module: 'commons-logging'
    }
    implementation("org.aspectj:aspectjweaver:1.8.8")

    //SpringBoot
    implementation group: "org.springframework.boot", name: "spring-boot-starter", version: springBootVersion
    implementation group: "org.springframework.boot", name: "spring-boot-starter-jdbc", version: springBootVersion
    implementation group: "org.springframework.boot", name: "spring-boot-starter-web", version: springBootVersion
    implementation group: "org.springframework.boot", name: "spring-boot-starter-log4j2", version: springBootVersion
    implementation group: "org.springframework.boot", name: "spring-boot-starter-data-ldap", version: springBootVersion

    // DB
    // Pool
    implementation group: "com.mchange", name: "c3p0", version: c3p0Version
    //Postgres
    implementation group: "org.postgresql", name: "postgresql", version: postgresqlVersion

    // Apache Commons
    implementation group: "commons-io", name: "commons-io", version: apacheCommonsIOVersion
    implementation group: "org.apache.commons", name: "commons-lang3", version: apacheCommonsLangVersion
    implementation group: "org.apache.commons", name: "commons-collections4", version: apacheCommonsCollectionsVersion

    //Lombok
    implementation group: "org.projectlombok", name: "lombok", version: lombokVersion
    annotationProcessor group: "org.projectlombok", name: "lombok", version: lombokVersion

    // Retrofit
    implementation group: "com.squareup.retrofit2", name: "retrofit", version: retrofitVersion
    implementation group: "com.squareup.retrofit2", name: "converter-jackson", version: retrofitVersion
    implementation group: "com.squareup.okhttp3", name: "okhttp", version: okhttpVersion

    // Jackson
    implementation group: "com.fasterxml.jackson.core", name: "jackson-databind", version: jaksonVersion

    // Swagger
    implementation group: "io.springfox", name: "springfox-swagger2", version: swaggerVersion
    implementation group: "io.springfox", name: "springfox-swagger-ui", version: swaggerVersion

    // AWS
    implementation group: "com.amazonaws", name: "aws-java-sdk-s3", version: awsSdkS3Version
    implementation group: "com.amazonaws", name: "aws-java-sdk-sts", version: awsSdkSTSVersion
    
    // Azure
    implementation group: "com.microsoft.azure", name: "azure-storage-blob", version: azureSdkBlobVersion

    //GS Bucket
    implementation group:"com.google.cloud", name:"google-cloud-storage", version:googleStorageSdkVersion

    //Tests
    implementation group: "org.springframework.boot", name: "spring-boot-starter-test", version: springBootVersion
    testImplementation group: "org.projectlombok", name: "lombok", version: lombokVersion
    testAnnotationProcessor group: "org.projectlombok", name: "lombok", version: lombokVersion
    testImplementation group: "org.elasticsearch.client", name: "transport", version: elasticsearchVersion

    //ShedLock
    implementation group: 'net.javacrumbs.shedlock', name: 'shedlock-spring', version: shedlockVersion
    implementation group: 'net.javacrumbs.shedlock', name: 'shedlock-provider-jdbc-template', version: shedlockVersion
}

test {
    useJUnitPlatform()
    reports.html.required = true
}
