import {
  AreaChartOutlined,
  BarsOutlined,
  ForkOutlined,
  HomeOutlined,
  MailOutlined,
  MessageOutlined,
  PlayCircleOutlined,
  PoweroffOutlined,
  SearchOutlined,
  SettingOutlined,
  ToolOutlined,
  UserDeleteOutlined,
} from '@ant-design/icons';
import {navigationPages, routeingPaths as paths} from '../../routing/paths.ts';
import {NavigationItem} from './types.ts';

export const navigationItems: NavigationItem[] = [
  {
    key: navigationPages.dashboard,
    title: 'Home',
    icon: HomeOutlined,
    path: paths.dashboard,
    keys: ['dashboard'],
    isDefault: false,
    isLink: true,
  },
  {
    key: navigationPages.library,
    title: 'Library',
    icon: ForkOutlined,
    path: paths.library,
    keys: [
      'library',
      'storages',
      'pipelines',
      'folder',
      'storage',
      'configuration',
      'metadata',
      'metadataFolder',
      'vs',
    ],
    isDefault: true,
    isLink: true,
  },
  {
    key: navigationPages.cluster,
    title: 'Cluster state',
    icon: BarsOutlined,
    path: paths.cluster,
    keys: ['cluster'],
    isDefault: false,
    isLink: true,
  },
  {
    key: navigationPages.tools,
    title: 'Tools',
    icon: ToolOutlined,
    path: paths.tools,
    keys: ['tools', 'tool'],
    isDefault: false,
    isLink: true,
  },
  {
    key: navigationPages.runs,
    title: 'Runs',
    icon: PlayCircleOutlined,
    path: paths.runs,
    keys: ['runs'],
    isDefault: false,
    isLink: true,
  },
  {
    key: navigationPages.settings,
    title: 'Settings',
    icon: SettingOutlined,
    path: paths.settings,
    keys: [
      'settings',
      'cli',
      'events',
      'user',
      'email',
      'preferences',
      'regions',
      'logs',
      'dictionaries',
      'profile',
    ],
    isDefault: false,
    isLink: true,
  },
  {
    key: navigationPages.search,
    title: 'Search',
    icon: SearchOutlined,
    path: paths.searchAdvanced,
    isDefault: false,
  },
  {
    key: navigationPages.billing,
    title: 'Billing',
    icon: AreaChartOutlined,
    path: paths.billing,
    isDefault: false,
    isLink: true,
  },
  {
    key: navigationPages.notifications,
    title: 'Notifications',
    icon: MailOutlined,
    path: paths.notifications,
    isDefault: false,
    isLink: true,
  },
  {
    key: navigationPages.chat,
    title: 'Chat',
    icon: MessageOutlined,
    path: paths.chat,
    keys: ['chat', 'ai-chat'],
    isDefault: false,
    isLink: true,
  },
  {
    key: 'divider',
    isDivider: true,
    static: true,
  },
  {
    key: 'logout',
    visible: (context) => !context.impersonation?.isImpersonated,
    title: 'Log out',
    icon: PoweroffOutlined,
    path: '/logout',
    isDefault: false,
    static: true,
  },
  {
    key: 'stop-impersonation',
    visible: (context) => Boolean(context.impersonation?.isImpersonated),
    title: (context) =>
      context.impersonation?.isImpersonated
        ? `Stop impersonation as ${context.impersonation.impersonatedUserName}`
        : undefined,
    icon: UserDeleteOutlined,
    isDefault: false,
    static: true,
    action: (context) => context.impersonation?.stopImpersonation?.(),
  },
  {
    key: 'launch',
    keys: ['launch'],
    static: true,
    hidden: true,
  },
  {
    key: navigationPages.miew,
    keys: ['miew'],
    static: true,
    hidden: true,
  },
  {
    key: navigationPages.wsi,
    keys: ['wsi'],
    static: true,
    hidden: true,
  },
  {
    key: navigationPages.hcs,
    keys: ['hcs'],
    static: true,
    hidden: true,
  },
  {
    key: navigationPages.run,
    keys: ['run'],
    static: true,
    hidden: true,
  },
];
