/*
 * Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id 'java'
    id 'maven-publish'
    id 'jacoco'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.sonarqube' version '2.6.1'
}

group 'com.epam.pipeline'

ext { springBootVersion = '2.7.18' }

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    withSourcesJar() // Modern way to create sources jar
}

repositories { mavenCentral() }

dependencies {
    implementation("org.springframework.boot:spring-boot-starter")
    testImplementation("org.springframework.boot:spring-boot-starter-test")

    implementation("org.springframework.boot:spring-boot-starter-data-jpa")

    implementation group: 'org.springframework.security', name: 'spring-security-acl', version: '4.2.2.RELEASE'

    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version: '2.8.7'
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.8.7'
    implementation group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-jsr310', version: '2.9.6'

    implementation group: 'commons-io', name: "commons-io", version: "2.4"
    implementation group: 'commons-validator', name: "commons-validator", version: "1.5.0"
    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.7'
    implementation group: 'org.apache.commons', name: 'commons-math3', version: '3.6.1'
    implementation group: 'org.apache.commons', name: "commons-collections4", version: "4.0"
    implementation group: "org.apache.commons", name: "commons-text", version: "1.4"

    implementation 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'

    implementation group: 'io.springfox', name: 'springfox-swagger2', version: '2.6.1'

    implementation 'io.fabric8:kubernetes-model:1.0.67'

    // Retrofit
    implementation group: 'com.squareup.retrofit2', name: 'retrofit', version: '2.3.0'
    implementation group: 'com.squareup.retrofit2', name: 'converter-jackson', version: '2.3.0'
    implementation group: 'com.squareup.okhttp3', name: 'okhttp', version: '3.9.1'
    implementation group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-jsr310', version: '2.9.6'
    implementation group: 'com.squareup.retrofit2', name: 'converter-scalars', version: '2.3.0'

    // Mockito
    testImplementation group: "org.mockito", name: "mockito-core", version: '2.21.0'

    // Map struct
    implementation 'org.mapstruct:mapstruct-jdk8:1.2.0.Final'
    implementation 'org.mapstruct:mapstruct-processor:1.2.0.Final'
}

dependencyManagement {
    imports {
        mavenBom("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}
