#!/bin/bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

BILLING_RUNTIME_LOG=$CP_BILLING_HOME/logs/runtime.log
mkdir -p $(dirname $BILLING_RUNTIME_LOG)
touch $BILLING_RUNTIME_LOG

cd $CP_SEARCH_HOME
nohup java $CP_BILLING_JAVA_OPTS -jar billing-report-agent.jar &> $BILLING_RUNTIME_LOG &
APP_PID="$!"

sleep 5

# Workaround the container hanging when being terminated
function sig_handler {
    echo "Got SIGTERM, stopping PID $APP_PID and exiting"
    if [ $APP_PID -ne 0 ]; then
        kill -SIGTERM "$APP_PID"
        wait "$APP_PID"
    fi
    exit 143
}
trap 'kill $! ; sig_handler' SIGTERM
tail -F $BILLING_RUNTIME_LOG &
wait "$!"
