#!/bin/bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

BILLING_RUNTIME_LOG=$CP_BILLING_HOME/logs/runtime.log
mkdir -p $(dirname $BILLING_RUNTIME_LOG)
touch $BILLING_RUNTIME_LOG

if [ "$CP_BILLING_CA_BUNDLE" ] && [ -f "$CP_BILLING_CA_BUNDLE" ]; then
    echo "[INFO] Setting up trust to $CP_BILLING_CA_BUNDLE defined via CP_BILLING_CA_BUNDLE"
    ca_bundle_tmp=$(mktemp -d)
    cd "$ca_bundle_tmp"
    csplit -z -f cert- -b '%02d.pem' "$CP_BILLING_CA_BUNDLE" '/-----BEGIN CERTIFICATE-----/' '{*}'

    JAVA_HOME=$(java -XshowSettings:properties -version 2>&1 | awk -F'= ' '/java\.home/ {print $2}')
    if [ -z "$JAVA_HOME" ]; then
        echo "[ERROR] Cannot get JAVA_HOME, skipping CP_BILLING_CA_BUNDLE setup"
    else
        i=1
        for f in cert-*.pem; do
            keytool -importcert -noprompt \
                -alias "billing-ca-$i" \
                -file "$f" \
                -keystore "$JAVA_HOME/lib/security/cacerts" \
                -storepass changeit
            i=$((i+1))
        done
    fi

    rm -rf "$ca_bundle_tmp"
fi

cd $CP_BILLING_HOME
nohup java $CP_BILLING_JAVA_OPTS -jar billing-report-agent.jar &> $BILLING_RUNTIME_LOG &
APP_PID="$!"

sleep 5

# Workaround the container hanging when being terminated
function sig_handler {
    echo "Got SIGTERM, stopping PID $APP_PID and exiting"
    if [ $APP_PID -ne 0 ]; then
        kill -SIGTERM "$APP_PID"
        wait "$APP_PID"
    fi
    exit 143
}
trap 'kill $! ; sig_handler' SIGTERM
tail -F $BILLING_RUNTIME_LOG &
wait "$!"
