#db configuration
spring.datasource.url=
spring.datasource.username=pipeline
spring.datasource.password=pipeline
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.maximumPoolSize=1

notification.scheduler.delay=30000

notification.enable.smtp=true
notification.enable.ui=false
notification.enable.azure=false

submit.threads=2

email.smtp.server.host.name=
email.smtp.port=587
email.ssl.on.connect=false
email.start.tls.enabled=true
email.from=
email.user=
email.password=

email.notification.retry.count=3
#in ms
email.notification.retry.delay=100
#in ms
email.notification.letter.delay=100

# azure api
notification.azure.tenant.id=${CP_NOTIFIER_AZ_TENANT_ID:}
notification.azure.client.id=${CP_NOTIFIER_AZ_CLIENT_ID:}
notification.azure.client.secret=${CP_NOTIFIER_AZ_CLIENT_SECRET:}
# comma separated values:
notification.azure.scopes=${CP_NOTIFIER_AZ_SCOPES:https://graph.microsoft.com/.default}
notification.azure.sender=${CP_NOTIFIER_AZ_SENDER:}
notification.azure.dry-run=${CP_NOTIFIER_AZ_DRY_RUN:false}
