apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-api-srv: "true"
  name: cp-api-srv
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: ${CP_API_SRV_INTERNAL_PORT}
    targetPort: 8080
    name: cp-api-srv-port-https
  selector:
    cloud-pipeline/cp-api-srv: "true"
