instance_type        = "m6i.large"
region               = "us-east-1"
source_ami           = ""
ssh_username         = "ec2-user"
iam_instance_profile = ""
subnet_id            = ""
deps_file            = "cpu/install-deps.sh"
ami_type             = "cpu"
