/*
 * Copyright 2017-2026 EPAM Systems, Inc. (https://www.epam.com/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * After the LESS->CSS migration this module is a thin wrapper around
 * `inject-css-variables`. Predefined themes are styled by the bundled
 * `styles/palette.css` (CSS custom properties scoped to body classes), so
 * they do not need any runtime injection. Custom themes ship a small
 * `<style id="cp-theme-vars-{id}">` element with their `--cp-*` overrides
 * — no LESS templates, no scoped rules.
 */

import injectCssVariables, {ejectCssVariables} from './inject-css-variables';

function isPredefined (theme) {
  if (!theme || !theme.predefined) {
    return false;
  }
  // Testing/preview clones generated by Appearance Management always carry
  // a synthetic identifier; they need their own runtime CSS vars even if
  // the source theme is predefined.
  if (typeof theme.identifier === 'string' && /-testing(?:-\d+)?$/.test(theme.identifier)) {
    return false;
  }
  return true;
}

export function ejectTheme (theme) {
  try {
    ejectCssVariables(theme);
  } catch (e) {
    console.warn(`Error ejecting theme: ${e.message}`);
  }
}

export default function injectTheme (theme) {
  if (!theme || !theme.identifier) {
    return Promise.resolve();
  }
  if (isPredefined(theme)) {
    // Predefined themes are fully covered by styles/palette.css.
    // We still eject any stale <style> from earlier sessions just in case.
    try {
      ejectCssVariables(theme);
    } catch (_) { /* noop */ }
    return Promise.resolve();
  }
  return injectCssVariables(theme);
}
