apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cp-clair
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        cloud-pipeline/cp-clair: "true"
        cloud-pipeline/core-component: "Deployment"
    spec:
      nodeSelector:
        cloud-pipeline/cp-clair: "true"
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: cp-clair
          image: ${CP_DOCKER_DIST_SRV}lifescience/cloud-pipeline:${CP_CLAIR_DOCKER_NAME}-$CP_VERSION
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: cp-config-global
          volumeMounts:
            - mountPath: /opt/docker-registry/pki
              name: docker-pki
              readOnly: true
            - mountPath: /opt/common/pki
              name: common-pki
              readOnly: true
          readinessProbe:
            httpGet:
              path: ${CP_CLAIR_HEALTH_ENDPOINT}
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: docker-pki
          hostPath:
            path: /opt/docker-registry/pki
        - name: common-pki
          hostPath:
            path: /opt/common/pki
      imagePullSecrets:
        - name: cp-distr-docker-registry-secret
