from .types import DefaultParameter
from .logger import cp_api_logger
from .utilities import (perform_cp_api_request,
                        timed_cache)


CP_CAP_SGE = "CP_CAP_SGE"
CP_CAP_SPARK = "CP_CAP_SPARK"
CP_CAP_SLURM = "CP_CAP_SLURM"
CP_CAP_KUBE = "CP_CAP_KUBE"
CP_CAP_AUTOSCALE = "CP_CAP_AUTOSCALE"
CP_CAP_AUTOSCALE_WORKERS = "CP_CAP_AUTOSCALE_WORKERS"
CP_CAP_AUTOSCALE_HYBRID = "CP_CAP_AUTOSCALE_HYBRID"
CP_CAP_AUTOSCALE_PRICE_TYPE = "CP_CAP_AUTOSCALE_PRICE_TYPE"

CP_CAP_DIND_CONTAINER = "CP_CAP_DIND_CONTAINER"
CP_CAP_SYSTEMD_CONTAINER = "CP_CAP_SYSTEMD_CONTAINER"
CP_CAP_SINGULARITY = "CP_CAP_SINGULARITY"
CP_CAP_DESKTOP_NM = "CP_CAP_DESKTOP_NM"
CP_CAP_MODULES = "CP_CAP_MODULES"
CP_DISABLE_HYPER_THREADING = "CP_DISABLE_HYPER_THREADING"

CP_CAP_LIMIT_MOUNTS = "CP_CAP_LIMIT_MOUNTS"
CP_CAP_RUN_CAPABILITIES = "CP_CAP_RUN_CAPABILITIES"

CP_CAP_DCV = "CP_CAP_DCV"
CP_CAP_DCV_DESKTOP = "CP_CAP_DCV_DESKTOP"
CP_CAP_DCV_WEB = "CP_CAP_DCV_WEB"

CP_CAP_RESCHEDULE_RUN = "CP_CAP_RESCHEDULE_RUN"
CP_CAP_AUTOSCALE_HYBRID_FAMILY = "CP_CAP_AUTOSCALE_HYBRID_FAMILY"
CP_CAP_AUTOSCALE_INSTANCE_TYPE = "CP_CAP_AUTOSCALE_INSTANCE_TYPE"

CP_CAP_SHARE_FS_TYPE = "CP_CAP_SHARE_FS_TYPE"
CP_CAP_SHARE_FS_DEPLOYMENT_TYPE = "CP_CAP_SHARE_FS_DEPLOYMENT_TYPE"
CP_CAP_SHARE_FS_SIZE = "CP_CAP_SHARE_FS_SIZE"
CP_CAP_SHARE_FS_THROUGHPUT = "CP_CAP_SHARE_FS_THROUGHPUT"
CP_CAP_SHARE_FS_IOPS = "CP_CAP_SHARE_FS_IOPS"

KNOWN_SYSTEM_PARAMETERS = [
    CP_CAP_SGE,
    CP_CAP_SPARK,
    CP_CAP_SLURM,
    CP_CAP_KUBE,
    CP_CAP_AUTOSCALE,
    CP_CAP_AUTOSCALE_WORKERS,
    CP_CAP_AUTOSCALE_HYBRID,
    CP_CAP_AUTOSCALE_PRICE_TYPE,

    CP_CAP_DIND_CONTAINER,
    CP_CAP_SYSTEMD_CONTAINER,
    CP_CAP_SINGULARITY,
    CP_CAP_DESKTOP_NM,
    CP_CAP_MODULES,
    CP_DISABLE_HYPER_THREADING,

    CP_CAP_LIMIT_MOUNTS,
    CP_CAP_RUN_CAPABILITIES,

    CP_CAP_DCV,
    CP_CAP_DCV_DESKTOP,
    CP_CAP_DCV_WEB,

    CP_CAP_RESCHEDULE_RUN,
    CP_CAP_AUTOSCALE_HYBRID_FAMILY,
    CP_CAP_AUTOSCALE_INSTANCE_TYPE,

    CP_CAP_SHARE_FS_TYPE,
    CP_CAP_SHARE_FS_DEPLOYMENT_TYPE,
    CP_CAP_SHARE_FS_SIZE,
    CP_CAP_SHARE_FS_THROUGHPUT,
    CP_CAP_SHARE_FS_IOPS
]


@timed_cache(minutes=10)
def get_system_parameters() -> list[DefaultParameter]:
    try:
        data = perform_cp_api_request('run/defaultParameters')
        if data is None or not isinstance(data, list):
            data = []
        result = [DefaultParameter.from_payload(p) for p in data]
        return [p for p in result if p is not None]
    except BaseException as e:
        cp_api_logger.error('error fetching run default parameters',
                            exc_info=e)
    return []
