#!/usr/bin/env bash

# Copyright 2017-2020 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Adds a new record to /etc/hosts file as well as default hostfile using file system locking.
# It prevents possible race condition during host files modification.
# 
# Usage examples:
#
# add_to_hosts "pipeline-12345" \
#              "127.0.0.2"

# Required args
WORKER_HOST="$1"
WORKER_IP="$2"

LOCK_FILE="/var/run/hosts-modification.lock"
DEFAULT_HOSTFILE="${DEFAULT_HOSTFILE:-/common/hostfile}"

COMMAND="echo -e '$WORKER_IP\t$WORKER_HOST' >> '/etc/hosts';
         echo -e '$WORKER_HOST' >> '$DEFAULT_HOSTFILE'"

flock -w 10 "$LOCK_FILE" bash -c "$COMMAND"
