#!/usr/bin/env bash

# Copyright 2017-2021 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Adds a new host record to default hostfile in a concurrent safe way.
# Additionally adds a new host record to /etc/hosts if host ip is provided as a second argument.
# 
# Usage examples:
#
# add_to_hosts "pipeline-12345" \
#              "127.0.0.1"
#
# add_to_hosts "pipeline-12345"

# Required args
WORKER_HOST="$1"
WORKER_IP="$2"

LOCK_FILE="/var/run/hosts-modification.lock"
DEFAULT_HOSTFILE="${DEFAULT_HOSTFILE:-/common/hostfile}"

if [[ -z "$WORKER_IP" ]]; then
    COMMAND="echo -e '$WORKER_HOST' >> '$DEFAULT_HOSTFILE'"
else
    COMMAND="echo -e '$WORKER_HOST' >> '$DEFAULT_HOSTFILE';
             echo -e '$WORKER_IP\t$WORKER_HOST' >> '/etc/hosts'"
fi

flock -w 10 "$LOCK_FILE" bash -c "$COMMAND"
