#!/usr/bin/env bash

# Copyright 2017-2020 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

MOUNT_DIR="$1"

FS_SETUP_TASK="InitializeSharedFS"
pipe_log_info "Started cluster shared FS setup" "$FS_SETUP_TASK"

# Check input parameters
if [ -z "$MOUNT_DIR" ]
then
    pipe_log_fail "Directory to export is not defined, exiting" "$FS_SETUP_TASK"
    exit 1
fi

# Install NFS clients
install_nfs_client

# Get Storage
_MOUNT_STORAGE_JSON=$(curl -k -s --fail --header "Authorization: Bearer $API_TOKEN" $API/datastorage/mountStorage?run_id=$RUN_ID)
_STORAGE_TYPE=$(echo "$_MOUNT_STORAGE_JSON" | jq -r '.payload | storageType')


if [ "$_STORAGE_TYPE" == "nfs" ]; then
    MOUNT_CMD="mkdir -p ${MOUNT_DIR} && rm -rf ${MOUNT_DIR}/* && mount ${NFS_IP}:/ ${SHARED_PATH} -t nfs4 -o actimeo=${CP_CAP_NFS_ACTIMEO}",nfsvers=4.1
elif [ "$_STORAGE_TYPE == "lustre"]; then

fi


