#!/usr/bin/env bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FS_SETUP_TASK="InitializeSharedFS"

pipe_log_info "Started cluster shared FS setup" "$FS_SETUP_TASK"

######################################################
# Check if this is a RPM Linux distribution
######################################################
/usr/bin/rpm -q -f /usr/bin/rpm >/dev/null 2>&1
IS_RPM_BASED=$?

######################################################
# Install LFS Master server
######################################################
pipe_log_info "--> Installing LFS master server" "$FS_SETUP_TASK"

_LFS_INSTALL_RESULT=1
if [[ "$IS_RPM_BASED" = 0 ]]; then
    yum -y -q install lizardfs-master
    _LFS_INSTALL_RESULT=$?
else
    apt-get install lsb-release gnupg -y -qq && \
    apt-get install -t stable lizardfs-master -y -qq
    _LFS_INSTALL_RESULT=$?
fi

if [ $_LFS_INSTALL_RESULT -ne 0 ]; then
    pipe_log_fail "Failed to install LFS master server, process will not continue with shared FS initialization" "$FS_SETUP_TASK"
    exit 1
fi

pipe_log_info "--> LFS master server installed" "$FS_SETUP_TASK"

######################################################
# Configure LFS Master
######################################################

cp /var/lib/mfs/metadata.mfs.empty /var/lib/mfs/metadata.mfs
cp /etc/mfs/mfsexports.cfg.dist /etc/mfs/mfsexports.cfg
cp /etc/mfs/mfsmaster.cfg.dist /etc/mfs/mfsmaster.cfg
cp /etc/mfs/mfsgoals.cfg.dist /etc/mfs/mfsgoals.cfg

echo "MASTER_HOST=lizardfs-master" >> /etc/mfs/mfsmaster.cfg
echo "CHUNKS_SOFT_DEL_LIMIT = 500" >> /etc/mfs/mfsmaster.cfg
echo "CHUNKS_HARD_DEL_LIMIT = 500" >> /etc/mfs/mfsmaster.cfg
echo "CHUNKS_LOOP_PERIOD = 500" >> /etc/mfs/mfsmaster.cfg

echo "1 1 : _" > /etc/mfs/mfsgoals.cfg

######################################################
# Start LFS Master
######################################################

if [[ "$IS_RPM_BASED" = 0 ]]; then
    nohup mfsmaster -d start > /var/log/mfsmaster.out 2>&1 &
else
    sed -i "s/fals/tru/g" /etc/default/lizardfs-master
    service lizardfs-master start
fi


if [ $? -ne 0 ]
then
    pipe_log_warn "Errors occured while starting LFS Master server, process will still proceed. See any messages above" "$FS_SETUP_TASK"
    exit 1
fi
pipe_log_success "Done with cluster shared FS setup" "$FS_SETUP_TASK"
