#!/usr/bin/env bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_MASTER_RUN_ID="$1"
_CHUNK_DIR="${2:-/mnt/chunks}"
_METADATA_DIR="${3:-/var/lib/mfs}"
FS_SETUP_TASK="InitializeSharedFS"

pipe_log_info "Started cluster LFS chunk server setup" "$FS_SETUP_TASK"


######################################################
# Check input parameters
######################################################
if [ -z "$_CHUNK_DIR" ]
then
    pipe_log_fail "Chunk data directory is not defined, exiting" "$FS_SETUP_TASK"
    exit 1
fi
if [ -z "$_METADATA_DIR" ]
then
    pipe_log_fail "Chunk metadata directory is not defined, exiting" "$FS_SETUP_TASK"
    exit 1
fi
if [ -z "$_MASTER_RUN_ID" ]
then
    pipe_log_fail "Master node run id is not defined, exiting" "$FS_SETUP_TASK"
    exit 1
fi

######################################################
# Check if this is a RPM Linux distribution
######################################################
/usr/bin/rpm -q -f /usr/bin/rpm >/dev/null 2>&1
IS_RPM_BASED=$?

######################################################
# Wait for LFS master node
######################################################
MASTER_INFO_RESULT=$(eval "$CP_PYTHON2_PATH ${COMMON_REPO_DIR}/scripts/cluster_wait_for_node.py --run-id ${_MASTER_RUN_ID} --task-name InitializeSharedFS")

if [ $? -ne 0 ]
then
    exit 1
fi

MASTER_INFO=($MASTER_INFO_RESULT)
MASTER_NAME=${MASTER_INFO[-2]}
MASTER_IP=${MASTER_INFO[-1]}

if [ -z "$MASTER_IP" ]
then
    pipe_log_fail "LFS Master node IP is not defined, exiting" "$FS_SETUP_TASK"
    exit 1
else
    pipe_log_info "LFS Master node IP: ${MASTER_IP}" "$FS_SETUP_TASK"
fi
if [ -z "$MASTER_NAME" ]
then
    pipe_log_fail "LFS Master node name is not defined, exiting" "$FS_SETUP_TASK"
    exit 1
else
    pipe_log_info "LFS Master node name: ${MASTER_NAME}" "$FS_SETUP_TASK"
fi

######################################################
# Install LFS Chunk server
######################################################
pipe_log_info "--> Installing LFS chunk server" "$FS_SETUP_TASK"

_LFS_INSTALL_RESULT=1

if [[ "$IS_RPM_BASED" = 0 ]]; then
    yum -y -q install lizardfs-chunkserver
    _LFS_INSTALL_RESULT=$?
else
    apt-get install lsb-release gnupg -y -qq && \
    apt-get install -t stable lizardfs-chunkserver -y -qq
    _LFS_INSTALL_RESULT=$?
fi

if [ $_LFS_INSTALL_RESULT -ne 0 ]
then
    pipe_log_fail "Failed to install LFS chunk server, process will not continue with shared FS initialization" "$FS_SETUP_TASK"
    exit 1
fi
pipe_log_info "--> LFS master chunk installed" "$FS_SETUP_TASK"

######################################################
# Configure LFS Chunk server
######################################################

cp /etc/mfs/mfschunkserver.cfg.dist /etc/mfs/mfschunkserver.cfg
echo "MASTER_HOST=lizardfs-master" >> /etc/mfs/mfschunkserver.cfg
mkdir -p $_CHUNK_DIR
chown -R mfs. $_CHUNK_DIR

echo "$_CHUNK_DIR" >> /etc/mfs/mfshdd.cfg
echo 'PERFORM_FSYNC = 0' >> /etc/mfs/mfschunkserver.cfg
sed -i '/# LABEL = _/c\LABEL = CLOUD_PIPELINE' /etc/mfs/mfschunkserver.cfg

mkdir -p $_METADATA_DIR
chown -R mfs. $_METADATA_DIR

if ! grep "lizardfs-master" /etc/hosts -q; then
    echo "$MASTER_IP" lizardfs-master >> /etc/hosts
fi

######################################################
# Start LFS Chunk server
######################################################

nohup mfschunkserver -d start > /var/log/mfschunkserver.out 2>&1 &

if [ $? -ne 0 ]
then
    pipe_log_warn "Errors occured while starting LFS Chunk server, process will still proceed. See any messages above" "$FS_SETUP_TASK"
fi
pipe_log_success "Done with cluster shared FS setup" "$FS_SETUP_TASK"
