#!/usr/bin/env bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

MOUNT_DIR="$1"

FS_SETUP_TASK="InitializeSharedFS"
pipe_log_info "Started cluster Lustre FS setup" "$FS_SETUP_TASK"

# Check input parameters
if [ -z "$MOUNT_DIR" ]
then
    pipe_log_fail "Directory for shared fs is not defined, exiting" "$FS_SETUP_TASK"
    exit 1
fi

mount_shared_lustre_fs "$MOUNT_DIR" "$RUN_ID" POST "$FS_SETUP_TASK"

if [ $? -ne 0 ]; then
    pipe_log_fail "Failed to setup Lustre FS on master node" "$FS_SETUP_TASK"
    exit 1
else
    pipe_log_success "Successfully mounted Lustre FS to master node" "$FS_SETUP_TASK"
fi
