#!/usr/bin/env bash

# Copyright 2017-2020 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

MOUNT_DIR="$1"

FS_SETUP_TASK="InitializeSharedFS"
pipe_log_info "Started cluster shared FS setup" "$FS_SETUP_TASK"

# Check input parameters
if [ -z "$MOUNT_DIR" ]
then
    pipe_log_fail "Directory to export is not defined, exiting" "$FS_SETUP_TASK"
    exit 1
fi

# Install NFS clients
install_nfs_client

# Get Storage
_MOUNT_STORAGE_JSON=$(curl -k -s --fail --header "Authorization: Bearer $API_TOKEN" $API/datastorage/runMount?run_id=$RUN_ID)
_STORAGE_TYPE=$(echo "$_MOUNT_STORAGE_JSON" | jq -r '.payload | storageType')
_STORAGE_PATH=$(echo "$_MOUNT_STORAGE_JSON" | jq -r '.payload | storagePath')
_MOUNT_OPTIONS=$(echo "$_MOUNT_STORAGE_JSON" | jq -r '.payload | mountOptions')

if [ "$_STORAGE_TYPE" == "nfs" ]; then
    _MOUNT_PROTOCOL="nfs"
elif [ "$_STORAGE_TYPE == "LUSTRE"]; then
    _MOUNT_PROTOCOL="lustre"
else
    pipe_log_fail "Unsupported storage type $_STORAGE_TYPE for shared file system" "$FS_SETUP_TASK"
    exit 1
fi

mkdir -p ${MOUNT_DIR} && rm -rf ${MOUNT_DIR}/* && mount -t ${_MOUNT_PROTOCOL} ${_STORAGE_PATH} ${MOUNT_DIR}" ${_MOUNT_OPTIONS}



