#!/bin/bash

# Copyright 2017-2023 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function fix_nomachine_display_owner() {
    local _cfg_file="$1"

    if [ -f "$_cfg_file" ]; then
        \cp "$_cfg_file" "${_cfg_file}_bkp"
        sed -i '/DisplayOwner/d' "$_cfg_file"
        echo "DisplayOwner $OWNER" >> "$_cfg_file"

        echo "NoMachine DisplayOwner-fix is applied to $_cfg_file"
    fi
}

fix_nomachine_display_owner "/usr/NX/etc/server.cfg"
fix_nomachine_display_owner "/usr/NX/etc/server.cfg.template"

# NoMachine/DCV screensaver fix
command -v "xset" >/dev/null 2>&1
IS_XSET_INSTALLED=$?

if [[ "$IS_XSET_INSTALLED" = 0 ]]; then
    /usr/bin/rpm -q -f /usr/bin/rpm >/dev/null 2>&1
    IS_RPM_BASED=$?

    [ $IS_RPM_BASED == 0 ] && { rpm -qa | grep screensaver &> /dev/null ; } && yum remove -y "*-screensaver"
    [ $IS_RPM_BASED != 0 ] && { dpkg -l | grep screensaver &> /dev/null ; } && apt purge -y "*-screensaver"
    [ $IS_RPM_BASED != 0 ] && { dpkg -l | grep light-locker &> /dev/null ; } && apt purge -y "light-locker*"

    sleep 1; xset s off
    sleep 1; xset s noblank

    echo "Screensaver-fix is applied"
fi

