#!/bin/bash

# Copyright 2017-2022 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "[INFO] Installing ZSH shell"

/usr/bin/rpm -q -f /usr/bin/rpm >/dev/null 2>&1
_IS_RPM_BASED=$?

_install_result=0
if [ $_IS_RPM_BASED -eq 0 ]; then
    yum install -y  zsh
    _install_result=$?
else
    apt-get update -y --allow-insecure-repositories
    apt-get install  -y zsh
    _install_result=$?
fi

if [ $_install_result -ne 0 ]; then
    echo "[ERROR] Unable to install ZSH shell"
    exit 1
else
    echo "[INFO] ZSH shell has been installed"
fi

if [ "$CP_CAP_SHELL_LIST_ZSH_SET_AS_DEFAULT" == "true" ]; then
    echo "[INFO] Setting ZSH as a default shell"

    chsh -s $(which zsh) root && \
    chsh -s $(which zsh) $OWNER

    if [ $_install_result -ne 0 ]; then
        echo "[ERROR] Unable to set ZSH as a default shell"
        exit 1
    else
        echo "[INFO] ZSH shell is a default for root and $OWNER now"
    fi
else
    echo "[INFO] ZSH will not be set as a default shell. It is not requested"
fi
_oh_my_zsh_url="${CP_CAP_SHELL_LIST_ZSH_OH_MY_URL:-"${GLOBAL_DISTRIBUTION_URL}tools/zsh/oh-my-zsh/install.sh"}"

echo "[INFO] Installing 'oh-my-zsh' framework from '${_oh_my_zsh_url}'"

if [ -d ~/.oh-my-zsh ] && [ "$CP_CAP_SHELL_LIST_ZSH_REINSTALL" == "true" ]; then
    echo "[WARN] 'oh-my-zsh' already installed, but forced to reinstall via CP_CAP_SHELL_LIST_ZSH_REINSTALL"
    rm -rf ~/.oh-my-zsh ${OWNER_HOME}/.oh-my-zsh
fi

wget "$_oh_my_zsh_url" -O /tmp/omz_install.sh && \
echo y | bash /tmp/omz_install.sh

if [ $? -ne 0 ]; then
    echo "[ERROR] Unable to install 'oh-my-zsh'"
    exit 1
else
    echo "[INFO] 'oh-my-zsh' has been installed"
fi

sed -i '1 i\export ZSH_DISABLE_COMPFIX=true' ~/.zshrc && \
\cp ~/.zshrc ${OWNER_HOME}/.zshrc && \
chown ${OWNER}:${OWNER} ${OWNER_HOME}/.zshrc && \
\cp -r ~/.oh-my-zsh ${OWNER_HOME}/.oh-my-zsh && \
chown -R ${OWNER}:${OWNER} ${OWNER_HOME}/.zshrc
