#!/usr/bin/env bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

###############################################################
# Common
###############################################################

if [ "$1" == "--skip-cert" ]; then
    _DIND_SKIP_CERTS_SETUP=1
fi

if ! command -v "jq" >/dev/null 2>&1 ; then
    echo "Installing jq"
    wget -q "https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64" -O /usr/bin/jq
    chmod +x /usr/bin/jq
fi

if [ -z "$CP_CAP_DIND_REGISTRY_HOST" ]; then
    CP_CAP_DIND_REGISTRY_HOST="$(echo "$docker_image" | cut -d "/" -f1)"
fi

if [ -z "$CP_CAP_DIND_REGISTRY_HOST" ]; then
    echo "Unable to determine default registry host to configure docker credentials"
    exit 1
fi

###############################################################
# Get the id of the CP_CAP_DIND_REGISTRY_HOST registry
###############################################################
_DIND_REGISTRY_ID=$(curl -s \
                    --max-time 30 \
                    -X GET \
                    --insecure \
                    --header "Accept: application/json" \
                    --header "Authorization: Bearer $API_TOKEN" \
                    "$API/dockerRegistry/loadTree" | jq -r ".payload.registries[] | select(.path == \"$CP_CAP_DIND_REGISTRY_HOST\").id // 0")

if [ "$_DIND_REGISTRY_ID" == 0 ]; then
    echo "Cannot determine id of the registry, containing  "
    exit 1
fi
echo "Registry ($CP_CAP_DIND_REGISTRY_HOST) id is: $_DIND_REGISTRY_ID"

###############################################################
# Setup certificate of the CP_CAP_DIND_REGISTRY_HOST registry
###############################################################
if [ -z "$_DIND_SKIP_CERTS_SETUP" ]; then
    _DIND_REGISTRY_CERTS_DIR="/etc/docker/certs.d/$CP_CAP_DIND_REGISTRY_HOST"
    mkdir -p $_DIND_REGISTRY_CERTS_DIR
    curl -k -s --header "Authorization: Bearer $API_TOKEN" \
        -o $_DIND_REGISTRY_CERTS_DIR/ca.crt \
        $API/dockerRegistry/$_DIND_REGISTRY_ID/cert
    
    if [ $? -ne 0 ]; then
        echo "Unable to configure certificate for $CP_CAP_DIND_REGISTRY_HOST registry"
        exit 1
    else
        echo "Registry certificate is configured"
    fi
else
    echo "Registry certificate will be skipped"
fi

###############################################################
# Login to the CP_CAP_DIND_REGISTRY_HOST registry
###############################################################
docker login "$CP_CAP_DIND_REGISTRY_HOST" -u "$OWNER" --password-stdin <<< "$API_TOKEN" > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "Unable to configure docker credentials for $CP_CAP_DIND_REGISTRY_HOST registry and $OWNER user"
    exit 1
else
    echo "Docker credentials are configured"
fi
