#!/usr/bin/env bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DATASTORAGE_RULES=$1
UPLOAD_TASK_NAME=$2

UPLOAD_RESULT=$(eval "${CP_PYTHON2_PATH} ${COMMON_REPO_DIR}/scripts/transfer_parameters.py --input-dir ${INPUT_DIR} \
    --common-dir ${COMMON_DIR} --analysis-dir ${ANALYSIS_DIR} --task ${UPLOAD_TASK_NAME}" \
    --storage-rules ${DATASTORAGE_RULES} --operation download)

if [ $? -ne 0 ]
then
    exit 1
fi