#!/bin/bash

# Copyright 2017-2020 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

EFA_SETUP_TASK=EFASupport

pipe_log_info "Started AWS EFA Driver setup" "$EFA_SETUP_TASK"

if [ -z "$CP_USE_HOST_NETWORK" ]; then
  pipe_log_warn "CP_USE_HOST_NETWORK is not set. EFA capability may work unexpectedly or doesn't work at all!" "$EFA_SETUP_TASK"
fi

if [ -z "$CP_NODE_SSH_PORT" ]; then
  pipe_log_warn "CP_NODE_SSH_PORT is not set. EFA capability may work unexpectedly or doesn't work at all!" "$EFA_SETUP_TASK"
  if [ "$CP_USE_HOST_NETWORK" != "" ]; then
    pipe_log_warn "CP_USE_HOST_NETWORK is set, but CP_NODE_SSH_PORT doesn't, so ssh to the run can be misconfigured and doesn't work!" "$EFA_SETUP_TASK"
  fi
fi

if [ -z "$CP_CAP_TARGET_SUBNET_ID" ]; then
  pipe_log_warn "CP_CAP_TARGET_SUBNET_ID is not set. EFA capability may work unexpectedly or doesn't work at all!" "$EFA_SETUP_TASK"
fi

if [ -z "$CP_CAP_TARGET_SECURITY_GROUPS" ]; then
  pipe_log_warn "CP_CAP_TARGET_SECURITY_GROUPS is not set. EFA capability may work unexpectedly or doesn't work at all!" "$EFA_SETUP_TASK"
fi

EFA_SETUP_DIR="/opt/"

cd $EFA_SETUP_DIR
curl -O "${GLOBAL_DISTRIBUTION_URL}tools/efa/aws-efa-installer-1.21.0.tar.gz" \
    && tar -xf aws-efa-installer-1.21.0.tar.gz \
    && rm -rf aws-efa-installer-1.21.0.tar.gz \
    && cd aws-efa-installer \
    && ./efa_installer.sh -y --skip-kmod --skip-limit-conf --no-verify &> /dev/null

if [ $? -ne 0 ]; then
  pipe_log_fail "Problems with installing EFA Driver" "$EFA_SETUP_TASK"
  exit 1
fi

export PATH="$PATH:/opt/amazon/efa/bin/"

fi_info -p efa -t FI_EP_RDM
if [ $? -ne 0 ]; then
  pipe_log_fail "Problems with checking EFA Driver after installation" "$EFA_SETUP_TASK"
  exit 1
fi

pipe_log_success "AWS EFA successfully installed" "$EFA_SETUP_TASK"
