#!/usr/bin/env bash

# Copyright 2017-2023 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "Setup gpustat"
echo "-"

_GPUSTAT_HOME="${1:-/usr/cpbin/gpustat}"
_GPUSTAT_HOME_WEB="$_GPUSTAT_HOME/app"
if [ ! -d "$_GPUSTAT_HOME_WEB" ]; then
    echo "[ERROR] gpustat web home directory $_GPUSTAT_HOME_WEB does not exist, probably a corrupted installation. Exiting..."
    exit 1
fi

CP_GPUSTAT_PORT="${CP_GPUSTAT_PORT:-8092}"
CP_GPUSTAT_TIMEOUT="${CP_GPUSTAT_TIMEOUT:-30}"
CP_GPUSTAT_PID_FILE="${CP_GPUSTAT_PID_FILE:-/var/run/gpustat.pid}"
echo "- Port:               $CP_GPUSTAT_PORT"
echo "- Recheck timeout(s): $CP_GPUSTAT_TIMEOUT"
echo "- Pid file:           $CP_GPUSTAT_PID_FILE"

_GPUSTAT_HOSTS=
DEFAULT_HOSTFILE=${DEFAULT_HOSTFILE:-/common/hostfile}

while true; do
    if [ ! -f "$DEFAULT_HOSTFILE" ]; then
        _GPUSTAT_HOSTS_NEW=$(hostname)
    else
        _GPUSTAT_HOSTS_NEW=$(echo $(cat $DEFAULT_HOSTFILE))
    fi

    if [ "$_GPUSTAT_HOSTS" == "$_GPUSTAT_HOSTS_NEW" ]; then
        continue
    fi

    _GPUSTAT_HOSTS="$_GPUSTAT_HOSTS_NEW"
    echo "[INFO] A list of hosts has changed, new list: $_GPUSTAT_HOSTS_NEW"
    echo "[INFO] (re)Starting gpustat"
    if [ -f "$CP_GPUSTAT_PID_FILE" ]; then
        echo "[INFO] --> gpustat is already running, stopping pid $CP_GPUSTAT_PID_FILE"
        kill $(cat $CP_GPUSTAT_PID_FILE)
    fi

    echo "[INFO] --> Starting a new instance of gpustat"
    cd "$_GPUSTAT_HOME_WEB"
    nohup gpustat-web --port "$CP_GPUSTAT_PORT" $_GPUSTAT_HOSTS > /var/log/gpustat.log 2>&1 &
    echo $! > "$CP_GPUSTAT_PID_FILE"

    sleep "$CP_GPUSTAT_TIMEOUT"
done
