#!/usr/bin/env bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function install_from_source {
    # Check whether we are on rpm or deb based distribution
    /usr/bin/rpm -q -f /usr/bin/rpm >/dev/null 2>&1
    _IS_RPM_BASED=$?

    # Install dependencies according to the distribution
    if [ $_IS_RPM_BASED -eq 0 ]; then
        yum install -y  automake \
                        fuse \
                        fuse-devel \
                        gcc-c++ \
                        libcurl-devel \
                        libxml2-devel \
                        openssl-devel
    else
        apt-get update -y --allow-insecure-repositories
        apt-get install  -y     automake \
                                autotools-dev \
                                fuse \
                                g++ \
                                libcurl4-gnutls-dev \
                                libfuse-dev \
                                libssl-dev \
                                libxml2-dev \
                                make \
                                pkg-config \
                                zlib1g-dev \
                                libncurses5-dev \
                                gettext-base \
                                libjsoncpp-dev
    fi

    # Install from sources
    _prev_wd=$(pwd) &&
    cd /tmp  && \
    rm -rf s3fs-fuse && \
    git clone https://github.com/s3fs-fuse/s3fs-fuse.git  && \
    cd s3fs-fuse  && \
    git checkout tags/v1.83 && \
    ./autogen.sh  && \
    ./configure  && \
    make  && \
    make install && \
    cd $_prev_wd && \
    rm -rf /tmp/s3fs-fuse
}

_FUSE_TYPE=s3fs

command -v s3fs >/dev/null 2>&1
_IS_S3FS_INSTALLED=$?
if [ $_IS_S3FS_INSTALLED -eq 0 ]; then
    echo "$_FUSE_TYPE already installed, skipping installation"
    exit 0
fi

echo "$_FUSE_TYPE is NOT installed, proceeding with installation from sources"

install_from_source
_IS_INSTALLED_FROM_SOURCE=$?
if [ $_IS_INSTALLED_FROM_SOURCE -eq 0 ]; then
    echo "${_FUSE_TYPE} installed from sources"
else
    echo "${_FUSE_TYPE} installation from sources failed"
    exit 1
fi
