#!/usr/bin/env bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function install_glibc_from_package_repository {
    /usr/bin/rpm -q -f /usr/bin/rpm >/dev/null 2>&1

    if [ $? -eq 0 ]; then
       yum install -y glibc
    else
       apt-get install -y libc-bin
    fi

    getent --version
}

function install_from_package_repository {
    # Check whether we are on rpm or deb based distribution
    /usr/bin/rpm -q -f /usr/bin/rpm >/dev/null 2>&1
    _IS_RPM_BASED=$?

    # Install dependencies according to the distribution
    if [ $_IS_RPM_BASED -eq 0 ]; then
        yum install -y blobfuse fuse
    else
        apt-get install -y blobfuse fuse
    fi
}

_FUSE_TYPE=blobfuse
_FUSE_BIN=/usr/bin/blobfuse

command -v getent > /dev/null 2>&1
if [ $? -ne 0 ]; then

    if ! install_glibc_from_package_repository; then
        echo "glibc is not installed. So resolved ip for Azure blob service will not be added to /etc/hosts. Some connection problem may appear during a work with Azure blob mounts"
    fi
fi


command -v blobfuse >/dev/null 2>&1
_IS_BLOBFUSE_INSTALLED=$?
if [ $_IS_BLOBFUSE_INSTALLED -eq 0 ]; then
    echo "$_FUSE_TYPE already installed, skipping installation"
    exit 0
fi

echo "$_FUSE_TYPE is NOT installed, proceeding with installation from package repository"

install_from_package_repository
_IS_INSTALLED_FROM_PACKAGE_REPOSITORY=$?
if [ $_IS_INSTALLED_FROM_PACKAGE_REPOSITORY -eq 0 ]; then
    echo "${_FUSE_TYPE} installed from package repository"
else
    echo "${_FUSE_TYPE} installation from package repository failed"
    exit 1
fi
