#!/usr/bin/env bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function get_os_distribution_parameter {
    _PARAMETER_NAME=$1
    echo $(cat /etc/os-release | grep "^$_PARAMETER_NAME=" | awk -F '=' '{gsub(/"/, "", $2); print $2}')
}

function install_glibc_from_package_repository {
    /usr/bin/rpm -q -f /usr/bin/rpm >/dev/null 2>&1

    if [ $? -eq 0 ]; then
       yum install -y glibc
    else
       apt-get install -y libc-bin
    fi

    getent --version
}

function install_from_package_repository {
    # Check whether we are on rpm or deb based distribution
    /usr/bin/rpm -q -f /usr/bin/rpm >/dev/null 2>&1
    _IS_RPM_BASED=$?

    DISTRIB_ID=$(get_os_distribution_parameter "ID") && # ubuntu/centos/...
    DISTRIB_RELEASE=$(get_os_distribution_parameter "VERSION_ID") # 16.04/7/...

    if [ "$?" -ne 0 ]
    then
        echo "OS distribution parameters retrieving failed"
        exit 1
    fi

    # Workaround for debian distro, as a prebuilt binary is not provided
    # It is proved that ubuntu 16 version works well for debian 9
    if [ "$DISTRIB_ID" == "debian" ]; then
        DISTRIB_ID="ubuntu"
        DISTRIB_RELEASE="16.04"
    fi

    # Install dependencies according to the distribution
    if [ $_IS_RPM_BASED -eq 0 ]; then
        rpm -Uvh https://packages.microsoft.com/config/$DISTRIB_ID/$DISTRIB_RELEASE/packages-microsoft-prod.rpm && \
        yum install -y blobfuse fuse
    else
        apt-get update -y --allow-insecure-repositories ; \
        apt-get install -y apt-transport-https && \
        wget https://packages.microsoft.com/config/$DISTRIB_ID/$DISTRIB_RELEASE/packages-microsoft-prod.deb && \
        dpkg -i packages-microsoft-prod.deb && \
        rm packages-microsoft-prod.deb && \
        apt-get update -y --allow-insecure-repositories ; \
        apt-get install -y blobfuse fuse
    fi
}

_FUSE_TYPE=blobfuse
_FUSE_BIN=/usr/bin/blobfuse

command -v getent > /dev/null 2>&1
if [ $? -ne 0 ]; then

    if ! install_glibc_from_package_repository; then
        echo "glibc is not installed. So resolved ip for Azure blob service will not be added to /etc/hosts. Some connection problem may appear during a work with Azure blob mounts"
    fi
fi


command -v blobfuse >/dev/null 2>&1
_IS_BLOBFUSE_INSTALLED=$?
if [ $_IS_BLOBFUSE_INSTALLED -eq 0 ]; then
    echo "$_FUSE_TYPE already installed, skipping installation"
    exit 0
fi

echo "$_FUSE_TYPE is NOT installed, proceeding with installation from package repository"

install_from_package_repository
_IS_INSTALLED_FROM_PACKAGE_REPOSITORY=$?
if [ $_IS_INSTALLED_FROM_PACKAGE_REPOSITORY -eq 0 ]; then
    echo "${_FUSE_TYPE} installed from package repository"
else
    echo "${_FUSE_TYPE} installation from package repository failed"
    exit 1
fi
