#!/usr/bin/env bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function get_os_distribution_parameter {
    _PARAMETER_NAME=$1
    echo $(cat /etc/os-release | grep "^$_PARAMETER_NAME=" | awk -F '=' '{gsub(/"/, "", $2); print $2}')
}

function install_from_package_repository {
    # Check whether we are on rpm or deb based distribution
    /usr/bin/rpm -q -f /usr/bin/rpm >/dev/null 2>&1
    _IS_RPM_BASED=$?

    DISTRIB_ID=$(get_os_distribution_parameter "ID") && # ubuntu/centos/...
    DISTRIB_RELEASE=$(get_os_distribution_parameter "VERSION_ID") # 16.04/7/...

    if [ "$?" -ne 0 ]
    then
        echo "OS distribution parameters retrieving failed"
        exit 1
    fi

    # Install dependencies according to the distribution
    if [ $_IS_RPM_BASED -eq 0 ]; then
        tee /etc/yum.repos.d/gcsfuse.repo > /dev/null <<EOF
[gcsfuse]
name=gcsfuse (packages.cloud.google.com)
baseurl=https://packages.cloud.google.com/yum/repos/gcsfuse-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF
        yum update -y -q
        yum install -y -q gcsfuse
    else
        apt-get install -y -qq gnupg lsb-release > /dev/null
        export GCSFUSE_REPO=gcsfuse-`lsb_release -c -s`
        echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | tee /etc/apt/sources.list.d/gcsfuse.list
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
        apt-get update -qq -y > /dev/null
        apt-get install -y -qq gcsfuse > /dev/null
    fi
}

_FUSE_TYPE=gcsfuse
_FUSE_BIN=/usr/bin/gcsfuse

command -v gcsfuse >/dev/null 2>&1
_IS_GCSFUSE_INSTALLED=$?
if [ $_IS_GCSFUSE_INSTALLED -eq 0 ]; then
    echo "$_FUSE_TYPE already installed, skipping installation"
    exit 0
fi

echo "$_FUSE_TYPE is NOT installed, proceeding with installation from package repository"

_DISTR_URL_PATH="https://cloud-pipeline-oss-builds.s3.amazonaws.com/tools/gcsfuse/gcsfuse.tar"

local_package_install $_DISTR_URL_PATH "gcsfuse"
if [ $? -ne 0 ]; then
    install_from_package_repository
    _IS_INSTALLED_FROM_PACKAGE_REPOSITORY=$?
    if [ $_IS_INSTALLED_FROM_PACKAGE_REPOSITORY -eq 0 ]; then
        echo "${_FUSE_TYPE} installed from package repository"
    else
        echo "${_FUSE_TYPE} installation from package repository failed"
        exit 1
    fi
else
    echo "${_FUSE_TYPE} installed from local repository"
fi
