#!/usr/bin/env bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

LFS_INSTALL_TASK="InstallLFSClient"

######################################################
# Check if this is a RPM Linux distribution
######################################################
/usr/bin/rpm -q -f /usr/bin/rpm >/dev/null 2>&1
IS_RPM_BASED=$?

######################################################
# Install LFS client
######################################################
pipe_log_info "--> Installing LFS client" "$LFS_INSTALL_TASK"

if [[ "$IS_RPM_BASED" = 0 ]]; then
    _LFS_INSTALL_RESULT=0
    if ! rpm -q "lizardfs-client"  &> /dev/null; then
        yum -y -q install lizardfs-client
        _LFS_INSTALL_RESULT=$?
    fi
else
    apt-get install lsb-release gnupg -y -qq && \
    apt-get install -t stable lizardfs-client -y -qq
    _LFS_INSTALL_RESULT=$?
fi

if [ $_LFS_INSTALL_RESULT -ne 0 ]
then
    pipe_log_fail "Failed to install LFS client, process will not continue with shared FS initialization" "$LFS_INSTALL_TASK"
    exit 1
fi
pipe_log_info "--> LFS client installed" "$LFS_INSTALL_TASK"

pipe_log_success "Finished NFS client installation" "$LFS_INSTALL_TASK"
