#!/usr/bin/env bash
# Copyright 2017-2020 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

NFS_INSTALL_TASK="InstallNFSClient"

######################################################
# Check if NFS client is already installed
######################################################
/usr/bin/rpm -q -f /usr/bin/rpm >/dev/null 2>&1
IS_RPM_BASED=$?

if [[ "$IS_RPM_BASED" = 0 ]]
then
    CHECK_CMD="rpm -qa | grep nfs-utils && rpm -qa | grep cifs-utils && rpm -qa | grep lustre-client"
    AMAZON_FSX_PUBLIC_KEY_URL="https://fsx-lustre-client-repo-public-keys.s3.amazonaws.com/fsx-rpm-public-key.asc" &&
    LUSTRE_CLIENT_REPO_URL="https://fsx-lustre-client-repo.s3.amazonaws.com/el/$(. /etc/os-release;echo $VERSION_ID)/fsx-lustre-client.repo" &&
    read -r -d '' INSTALL_CMD <<- EOM
      yum install nfs-utils cifs-utils wget -y -q &&
      wget $AMAZON_FSX_PUBLIC_KEY_URL -qO /tmp/fsx-rpm-public-key.asc &&
      rpm --import /tmp/fsx-rpm-public-key.asc &&
      wget $LUSTRE_CLIENT_REPO_URL -qO /etc/yum.repos.d/aws-fsx.repo &&
      yum install -y -q kmod-lustre-client lustre-client &&
      rm -f /tmp/fsx-rpm-public-key.asc /etc/yum.repos.d/aws-fsx.repo
EOM
else
    CHECK_CMD="dpkg -l | grep nfs-common && dpkg -l | grep cifs-utils && dpkg -l | grep lustre-client"
    AMAZON_FSX_PUBLIC_KEY_URL="https://fsx-lustre-client-repo-public-keys.s3.amazonaws.com/fsx-ubuntu-public-key.asc"
    LUSTRE_CLIENT_REPO_URL="https://fsx-lustre-client-repo.s3.amazonaws.com/$(. /etc/os-release;echo $ID $VERSION_CODENAME)"
    read -r -d '' INSTALL_CMD <<- EOM
      apt-get install wget apt-utils -y -qq  &&
      wget -qO- $AMAZON_FSX_PUBLIC_KEY_URL | apt-key add - &&
      echo "deb $LUSTRE_CLIENT_REPO_URL main" > /etc/apt/sources.list.d/fsxlustreclientrepo.list && apt-get update -qq &&
      mkdir -p /lib/modules/$(uname -r) &&
      apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" nfs-common cifs-utils linux-aws lustre-client-modules-aws -y > /dev/null
EOM
fi

eval "$CHECK_CMD"

######################################################
# If NFS client is already installed - skip installation, otherwise install
######################################################
if [ $? -ne 0 ]
then
    pipe_log_info "--> NFS client not found, proceeding with installation" "$NFS_INSTALL_TASK"
    pipe_log_info "--> Installing NFS client" "$NFS_INSTALL_TASK"
    eval "$INSTALL_CMD"
    if [ $? -ne 0 ]
    then
        pipe_log_fail "Failed to install NFS client, process will not continue with shared FS initialization" "$NFS_INSTALL_TASK"
        exit 1
    fi
    pipe_log_info "--> NFS client installed" "$NFS_INSTALL_TASK"
else
    pipe_log_info "--> NFS client is already installed" "$NFS_INSTALL_TASK"
fi

#####################################################
# Restart NFS client
#####################################################
rpcbind && rpc.statd

pipe_log_success "Finished NFS client installation" "$NFS_INSTALL_TASK"
