#!/usr/bin/env bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_FUSE_TYPE=goofys
_FUSE_URL="https://github.com/kahing/goofys/releases/download/v0.19.0/goofys"
_FUSE_BIN=/usr/local/bin/goofys

if [ ! -f ${_FUSE_BIN} ]; then
    echo "${_FUSE_BIN} not found. Installing..."
    wget -q --no-check-certificate ${_FUSE_URL} -O ${_FUSE_BIN} 2>/dev/null || curl -s -k -o ${_FUSE_BIN} ${_FUSE_URL}
    if [ $? -ne 0 ]; then
        echo "Error downloading ${_FUSE_URL} to ${_FUSE_BIN}"
        exit 1
    fi
    chmod +x ${_FUSE_BIN}
    echo "${_FUSE_BIN} installed"
else
    echo "${_FUSE_BIN} already installed"
fi