#!/usr/bin/env bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_SOURCE="$1"
_PACKAGE_TO_CHECK="$2"

function check_installed {
      local _COMMAND_TO_CHECK="$1"
      command -v "$_COMMAND_TO_CHECK" >/dev/null 2>&1
      return $?
}

# This script will download archive with sources to be installed

if [ -z "$_SOURCE" ]; then
     echo "Parameter SOURCE is not specified, no package will be installed"
     exit 1
fi

_PATH_TO_PACKAGES=/tmp/localinstall
_ARCH_NAME=$(basename "$_SOURCE")
_BIN_DIR=${_ARCH_NAME%.*}

mkdir -p $_PATH_TO_PACKAGES
wget -q --no-check-certificate $_SOURCE --directory-prefix=$_PATH_TO_PACKAGES > /dev/null
tar -xf "$_PATH_TO_PACKAGES/$_ARCH_NAME" -C $_PATH_TO_PACKAGES

check_installed "dpkg" && check_installed "apt-get" && {
    echo "Local installation of the deb file(s): $_PATH_TO_PACKAGES/$_BIN_DIR/*.deb"
    apt-get update
    export DEBIAN_FRONTEND=noninteractive
    dpkg -i $_PATH_TO_PACKAGES/$_BIN_DIR/*.deb &> /dev/null
    dpkg --configure -a > /dev/null
    apt-get install -f -y
};

check_installed "yum" && {
    echo "Local installation of the rpm file(s): $_PATH_TO_PACKAGES/$_BIN_DIR/*.rpm"
    yum localinstall $_PATH_TO_PACKAGES/$_BIN_DIR/*.rpm -y -q > /dev/null
};

rm -rf $_PATH_TO_PACKAGES

if [ "$_PACKAGE_TO_CHECK" ]; then
    command -v $_PACKAGE_TO_CHECK >/dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "Local installation of $_PACKAGE_TO_CHECK failed"
        exit 1
    fi
fi

echo "Done with packages installation"
