#!/usr/bin/env bash

# Copyright 2017-2022 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o pipefail

if [ -z "$API" ]; then
    echo "[ERROR] API is not set"
    exit 1
fi

if [ -z "$API_TOKEN" ]; then
    echo "[ERROR] API_TOKEN is not set"
    exit 1
fi

_roles_info=$(curl -sk -H "Authorization: Bearer $API_TOKEN" $API/whoami | jq -r '.payload.roles[]')
_admin_role=$(echo "$_roles_info" | jq -r 'select(.name == "ROLE_ADMIN")')
_advanced_role=$(echo "$_roles_info" | jq -r 'select(.name == "ROLE_ADVANCED_USER")')

if [ -z "$_admin_role" ] || [ -z "$_advanced_role" ]; then
    echo "[ERROR] mount: only ROLE_ADMIN or ROLE_ADVANCED_USER can do that"
    exit 1
fi

UNDERLYING_MOUNT_COMMAND="$1"
shift 1 # removes first argument

"$UNDERLYING_MOUNT_COMMAND" "$@"
