#!/usr/bin/env bash

# Copyright 2017-2020 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

MOUNT_DIR="$1"
REQUEST_FOLDER_FOR_ID="$2"
REQUEST_TYPE="$3"

FS_SETUP_TASK="InitializeSharedFS"

_MOUNT_STORAGE_JSON=$(curl -k -s --fail -X $REQUEST_TYPE --header "Authorization: Bearer $API_TOKEN" $API/datastorage/sharedStorage?runId=$REQUEST_FOLDER_FOR_ID)
_STORAGE_PATH=$(echo "$_MOUNT_STORAGE_JSON" | jq -r '.payload.path')
_MOUNT_TYPE=$(echo "$_MOUNT_STORAGE_JSON" | jq -r '.payload.mount.mountType')
_MOUNT_OPTIONS=$(echo "$_MOUNT_STORAGE_JSON" | jq -r '.payload.storage.mountOptions')

pipe_log_info "Storage $_STORAGE_PATH with type $_MOUNT_TYPE will be used as shared FS" "$FS_SETUP_TASK"

if [ $_MOUNT_OPTIONS == "null" ]; then
    _MOUNT_OPTIONS=$(echo "$_MOUNT_STORAGE_JSON" | jq -r '.payload.mount.mountOptions')
fi

if [ $_MOUNT_OPTIONS == "null" ]; then
    _OPTIONS_STR=""
else
    _OPTIONS_STR=" -o $_MOUNT_OPTIONS"
fi

if [ "$_MOUNT_TYPE" == "NFS" ]; then
    _MOUNT_PROTOCOL="nfs"
elif [ "$_MOUNT_TYPE" == "LUSTRE" ]; then
    _MOUNT_PROTOCOL="lustre"
else
    pipe_log_fail "Unsupported storage type $_STORAGE_TYPE for shared file system" "$FS_SETUP_TASK"
    exit 1
fi

mkdir -p "${MOUNT_DIR}" && rm -rf "${MOUNT_DIR}/*" && mount -t ${_MOUNT_PROTOCOL} "${_STORAGE_PATH}" "${MOUNT_DIR}" ${_OPTIONS_STR}
exit $?