#!/usr/bin/env bash
# Copyright 2023 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DCV_INSTALL_TASK="NiceDCVInitialization"

_user_name="${1:-$OWNER}"

if [ -z "$_user_name" ]; then
    pipe_log_fail "User is not defined for the DCV session creation" "$DCV_INSTALL_TASK"
    exit 1
fi

CP_DCV_INIT_SCRIPT="${CP_DCV_INIT_SCRIPT:-/opt/dcv/extras/xfce4launch}"
if [ "$CP_DCV_INIT_SCRIPT" ]; then
    CP_DCV_INIT_SCRIPT="--init $CP_DCV_INIT_SCRIPT"
    pipe_log_info "Using '$CP_DCV_INIT_SCRIPT' initialization script for a DCV session" "$DCV_INSTALL_TASK"
fi
dcv create-session --owner $_user_name --user $_user_name $CP_DCV_INIT_SCRIPT "${_user_name}-session"

if [ $? -ne 0 ]; then
    pipe_log_fail "Cannot create DCV session for '$_user_name'" "$DCV_INSTALL_TASK"
else
    pipe_log_info "DCV session was created for '$_user_name'" "$DCV_INSTALL_TASK"
fi