#!/usr/bin/env bash
# Copyright 2021 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DCV_INSTALL_TASK="NiceDCVInitialization"
export _RETRIES_TIMEOUT="${CP_DCV_RETRY_TIMEOUT:-30}"
export _RETRIES_COUNT="${CP_DCV_RETRIES_COUNT:-60}"

# Note: these locations are baked into the generated "xfce4launch" script (see below),
# as the environment of the run is not available to the DCV session initialization
CP_DCV_EXTRAS_DIR="/opt/dcv/extras"
CP_DCV_XFCE_TEMPLATES_DIR="$CP_DCV_EXTRAS_DIR/xfce"

function install_optional_rpm_pkgs {
  for _optional_pkg in "$@"; do
    yum -y install "$_optional_pkg" || \
    yum -y install --disablerepo=cloud-pipeline "$_optional_pkg"
    if [ $? -ne 0 ]; then
      pipe_log_warn "[WARNING] Optional DCV prerequisite $_optional_pkg is not available, skipping it" "$DCV_INSTALL_TASK"
    fi
  done
}

function install_optional_deb_pkgs {
  for _optional_pkg in "$@"; do
    DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends "$_optional_pkg"
    if [ $? -ne 0 ]; then
      pipe_log_warn "[WARNING] Optional DCV prerequisite $_optional_pkg is not available, skipping it" "$DCV_INSTALL_TASK"
    fi
  done
}

function install_prerequisites {
  pipe_log_info "Installing DCV prerequisites" "$DCV_INSTALL_TASK"
  _pkg_result=0
  if [[ "$IS_RPM_BASED" = 0 ]]; then
    if [ "$CP_OS" == "centos" ]; then
      _rpm_dcv_extra_pkgs="xvattr gnome-system-log desktop-backgrounds-gnome"
    fi

    _rpm_dcv_pkgs="glx-utils mesa-dri-drivers xorg-x11-server-Xorg \
                       xorg-x11-utils xorg-x11-xauth xorg-x11-xinit \
                       xorg*fonts* xterm freeglut \
                       gnome-desktop3 gnome-terminal \
                       gnome-system-monitor nautilus evince gnome-color-manager \
                       gnome-font-viewer gnome-shell gnome-calculator gedit gdm \
                       metacity gnome-session gnome-classic-session \
                       gnome-session-xsession gnu-free-fonts-common \
                       gnu-free-mono-fonts gnu-free-sans-fonts \
                       gnu-free-serif-fonts $_rpm_dcv_extra_pkgs"

    # xfce4-xkb-plugin (a keyboard layout switcher) and setxkbmap are optional, as they may
    # be missing in the mirrored repositories. If they are not available - a desktop session
    # is still started, but with a single (default) keyboard layout.
    # Note: setxkbmap and xrandr are shipped by the packages of the same name in el9 and by
    # the "xorg-x11-*-utils" packages in the previous releases, so both of them are requested
    _rpm_dcv_optional_pkgs="libXvMC mesa-libxatracker xfce4-xkb-plugin \
                            setxkbmap xorg-x11-xkb-utils \
                            xrandr xorg-x11-server-utils"

    yum install -y epel-release
    yum -y install $_rpm_dcv_pkgs && \
    yum -y groupinstall "Xfce"
    _pkg_result=$?

    # Fallback: try same with an upstream repo
    if [ $_pkg_result -ne 0 ]; then
      yum -y install --disablerepo=cloud-pipeline $_rpm_dcv_pkgs && \
      yum -y groupinstall --disablerepo=cloud-pipeline "Xfce"
      _pkg_result=$?
    fi

    if [ $_pkg_result -eq 0 ]; then
      install_optional_rpm_pkgs $_rpm_dcv_optional_pkgs
    fi
  else
    apt update -y && \
    DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
     xfce4 dbus-x11 xfce4-terminal firefox
    _pkg_result=$?
    if [ $_pkg_result -eq 0 ]; then
      install_optional_deb_pkgs xfce4-xkb-plugin x11-xkb-utils
    fi
  fi
  if [ $_pkg_result -ne 0 ]; then
    pipe_log_fail "[ERROR] Cannot install system prerequisites for DCV" "$DCV_INSTALL_TASK"
    return $_pkg_result
  fi

  $CP_PYTHON2_PATH -m pip install $CP_PIP_EXTRA_ARGS flask==1.1.1 Flask-HTTPAuth==3.3.0
  _py_result=$?
  if [ $_py_result -ne 0 ]; then
    pipe_log_fail "[ERROR] Cannot install python prerequisites for DCV" "$DCV_INSTALL_TASK"
    return $_py_result
  fi
}

function install_dcv {
  pipe_log_info "Installing DCV server" "$DCV_INSTALL_TASK"
  _pkg_result=0
  _dcv_distro_url="${CP_CAP_DCV_DISTRO_URL:-"${GLOBAL_DISTRIBUTION_URL}tools/dcv"}"
  if [[ "$IS_RPM_BASED" = 0 ]]; then
    # Major version of the underlying distribution, e.g. 7 for "centos:7.9", 9 for "rocky:9.8".
    # If it cannot be resolved - the el8 distribution is used, as before
    _dcv_os_major="${CP_VER_MAJOR:-${CP_VER%%.*}}"
    if ! [[ "$_dcv_os_major" =~ ^[0-9]+$ ]]; then
        pipe_log_warn "[WARNING] Cannot resolve a major version of the distribution from CP_VER='$CP_VER', el8 packages will be used" "$DCV_INSTALL_TASK"
        _dcv_os_major=8
    fi

    if [ "$_dcv_os_major" -eq 7 ]; then
        _NICE_DCV_DISTRIBUTION="${CP_CAP_DCV_DISTRIBUTION:-nice-dcv-2021.2-11190-el7-x86_64}"
        rpm --import "$_dcv_distro_url/NICE-GPG-KEY"
    elif [ "$_dcv_os_major" -ge 9 ]; then
        _NICE_DCV_DISTRIBUTION="${CP_CAP_DCV_DISTRIBUTION:-nice-dcv-2024.0-19030-el9-x86_64}"
        rpm --import "$_dcv_distro_url/NICE-GPG-KEY"
    else
        _NICE_DCV_DISTRIBUTION="${CP_CAP_DCV_DISTRIBUTION:-nice-dcv-2021.2-11445-el8-x86_64}"
    fi
    pipe_log_info "DCV distribution to be installed: ${_NICE_DCV_DISTRIBUTION}" "$DCV_INSTALL_TASK"

    wget "$_dcv_distro_url/${_NICE_DCV_DISTRIBUTION}.tgz" && \
      tar -xvzf ${_NICE_DCV_DISTRIBUTION}.tgz && \
      cd ${_NICE_DCV_DISTRIBUTION} && \
      yum install -y nice-dcv-server-*.x86_64.rpm \
                      nice-dcv-web-viewer-*.x86_64.rpm \
                      nice-xdcv-*.x86_64.rpm
    _pkg_result=$?
  else
    if [[ "$CP_VER" == *"18.04"* ]]; then
      _NICE_DCV_DISTRIBUTION=nice-dcv-2021.2-11190-ubuntu1804-x86_64
      wget "$_dcv_distro_url/NICE-GPG-KEY"
      gpg --import NICE-GPG-KEY
      wget "$_dcv_distro_url/$_NICE_DCV_DISTRIBUTION.tgz" && \
      tar -xvzf $_NICE_DCV_DISTRIBUTION.tgz && cd $_NICE_DCV_DISTRIBUTION && \
      apt install -y ./nice-dcv-server_2021.2.11190-1_amd64.ubuntu1804.deb \
                     ./nice-dcv-web-viewer_2021.2.11190-1_amd64.ubuntu1804.deb \
                     ./nice-xdcv_2021.2.411-1_amd64.ubuntu1804.deb
      _pkg_result=$?
    elif [[  "$CP_VER" == *"20.04"* ]]; then
      _NICE_DCV_DISTRIBUTION=nice-dcv-2021.2-11190-ubuntu2004-x86_64
      wget "$_dcv_distro_url/NICE-GPG-KEY"
      gpg --import NICE-GPG-KEY
      wget "$_dcv_distro_url/$_NICE_DCV_DISTRIBUTION.tgz" && \
      tar -xvzf $_NICE_DCV_DISTRIBUTION.tgz && cd $_NICE_DCV_DISTRIBUTION && \
      apt install -y ./nice-dcv-server*.deb \
                      ./nice-dcv-web-viewer*.deb \
                      ./nice-xdcv_*.deb
      _pkg_result=$?
    elif [[  "$CP_VER" == *"22.04"* ]]; then
      _NICE_DCV_DISTRIBUTION=nice-dcv-2022.2-14521-ubuntu2204-x86_64
      wget "$_dcv_distro_url/NICE-GPG-KEY"
      gpg --import NICE-GPG-KEY
      wget "$_dcv_distro_url/$_NICE_DCV_DISTRIBUTION.tgz" && \
      tar -xvzf $_NICE_DCV_DISTRIBUTION.tgz && cd $_NICE_DCV_DISTRIBUTION && \
      apt install -y ./nice-dcv-server*.deb \
                      ./nice-dcv-web-viewer*.deb \
                      ./nice-xdcv_*.deb
      _pkg_result=$?
    elif [[  "$CP_VER" == *"24.04"* ]]; then
      _NICE_DCV_DISTRIBUTION=nice-dcv-2024.0-19030-ubuntu2404-x86_64
      wget "$_dcv_distro_url/NICE-GPG-KEY"
      gpg --import NICE-GPG-KEY
      wget "$_dcv_distro_url/$_NICE_DCV_DISTRIBUTION.tgz" && \
      tar -xvzf $_NICE_DCV_DISTRIBUTION.tgz && cd $_NICE_DCV_DISTRIBUTION && \
      apt install -y ./nice-dcv-server*.deb \
                      ./nice-dcv-web-viewer*.deb \
                      ./nice-xdcv_*.deb
      _pkg_result=$?
    else
      pipe_log_fail "[ERROR] Unsupported Ubuntu version: $CP_VER" "$DCV_INSTALL_TASK"
      return 1
    fi
  fi

  if [ $_pkg_result -ne 0 ]; then
    pipe_log_fail "[ERROR] Cannot install DCV itself" "$DCV_INSTALL_TASK"
    return $_pkg_result
  fi

  cd ..
  if [ "${_NICE_DCV_DISTRIBUTION}" ]; then
    rm -rf "${_NICE_DCV_DISTRIBUTION}"*
  fi
  pipe_log_info "DCV successfully installed and configured" "$DCV_INSTALL_TASK"
}

function configure_dcv {
  pipe_log_info "Configuring DCV server" "$DCV_INSTALL_TASK"
  usermod -aG video dcv
  sed -i 's|#authentication="none"|authentication="none"|g' /etc/dcv/dcv.conf
  sed -i -E "s|#web-port=.*|web-port=$CP_DCV_WEB_PORT|g" /etc/dcv/dcv.conf

cat <<EOF >>/etc/dcv/dcv.conf
[clipboard]
primary-selection-copy=true
primary-selection-paste=true
EOF
}

function configure_dcv_extras {
  mkdir -p "$CP_DCV_EXTRAS_DIR"

  # Xfce configuration templates are shipped with the common repository and are applied
  # to the session user's home directory by the DCV session initialization script (see below)
  local _xfce_templates_src="${COMMON_REPO_DIR}/resources/linux/xfce"
  if [ -d "$_xfce_templates_src" ]; then
    rm -rf "$CP_DCV_XFCE_TEMPLATES_DIR"
    \cp -r "$_xfce_templates_src" "$CP_DCV_XFCE_TEMPLATES_DIR" && \
    chmod -R a+rX "$CP_DCV_XFCE_TEMPLATES_DIR"
  else
    pipe_log_warn "[WARNING] Xfce configuration templates are not found at $_xfce_templates_src, a default Xfce look and feel will be used" "$DCV_INSTALL_TASK"
  fi

# Settings are resolved from the run environment and are stored in the script itself, as it is
# executed by the "dcvserver" service (see nice_dcv_create_session), i.e. the environment
# of the run is NOT available, when a session is being created
cat <<EOF >"$CP_DCV_EXTRAS_DIR/xfce4launch"
#!/bin/bash

# Initialization script of the DCV session: applies the Cloud Pipeline Xfce configuration
# to the session user's home directory and starts the desktop environment.
# If called with the "--runtime" option - applies the configuration, which requires
# an already running Xfce session (a desktop backdrop and a keyboard layout).
# Note: this script is generated by the "nice_dcv_setup" script, do not edit it in place.

CP_DCV_LAUNCH_SCRIPT_PATH="$CP_DCV_EXTRAS_DIR/xfce4launch"
CP_DCV_XFCE_TEMPLATES_DIR="$CP_DCV_XFCE_TEMPLATES_DIR"
CP_DCV_XFCE_STARTUP_TIMEOUT="${CP_DCV_XFCE_STARTUP_TIMEOUT:-60}"
# Shall match the XKB plugin id in the xfce4-panel.xml template
CP_DCV_XKB_PLUGIN_ID="${CP_DCV_XKB_PLUGIN_ID:-6}"
CP_DCV_XKB_MODEL="${CP_DCV_XKB_MODEL:-pc105}"
CP_DCV_XKB_LAYOUTS="${CP_DCV_XKB_LAYOUTS:-us,fr,de}"
CP_DCV_XKB_TOGGLE="${CP_DCV_XKB_TOGGLE:-grp:ctrl_shift_toggle}"
EOF

cat <<'EOF' >>"$CP_DCV_EXTRAS_DIR/xfce4launch"

CP_DCV_XFCONF_DIR="$HOME/.config/xfce4/xfconf/xfce-perchannel-xml"
CP_DCV_PANEL_DIR="$HOME/.config/xfce4/panel"

function log_msg() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [xfce4launch] $1"
}

function resolve_xkb_plugin() {
    # xfce4-xkb-plugin is registered as "xkb-plugin" or "xkb", depending on its version
    local _plugins_dir
    local _plugin
    for _plugins_dir in /usr/share/xfce4/panel/plugins /usr/share/xfce4/panel-plugins; do
        for _plugin in xkb-plugin xkb; do
            if [ -f "$_plugins_dir/$_plugin.desktop" ]; then
                echo "$_plugin"
                return 0
            fi
        done
    done
    return 1
}

function configure_xfce() {
    if [ ! -d "$CP_DCV_XFCE_TEMPLATES_DIR" ]; then
        log_msg "[WARNING] Xfce configuration templates are not found at $CP_DCV_XFCE_TEMPLATES_DIR, falling back to the default configuration"
        mkdir -p "$CP_DCV_XFCONF_DIR"
        [ -f /etc/xdg/xfce4/panel/default.xml ] && \
            \cp /etc/xdg/xfce4/panel/default.xml "$CP_DCV_XFCONF_DIR/xfce4-panel.xml"
        return 0
    fi

    mkdir -p "$CP_DCV_XFCONF_DIR" "$CP_DCV_PANEL_DIR"
    \cp "$CP_DCV_XFCE_TEMPLATES_DIR/xfce4-panel.xml" "$CP_DCV_XFCONF_DIR/xfce4-panel.xml"

    local _xkb_plugin="$(resolve_xkb_plugin)"
    if [ "$_xkb_plugin" ]; then
        log_msg "Keyboard layout switcher is resolved as '$_xkb_plugin', layouts: $CP_DCV_XKB_LAYOUTS"
        sed -i "s|_XKB_PLUGIN_NAME_|$_xkb_plugin|g" "$CP_DCV_XFCONF_DIR/xfce4-panel.xml"
        \cp "$CP_DCV_XFCE_TEMPLATES_DIR/xkb-plugin.rc" \
            "$CP_DCV_PANEL_DIR/$_xkb_plugin-$CP_DCV_XKB_PLUGIN_ID.rc"
        # An empty variant shall be defined for each of the configured layouts, e.g. ",," for "us,fr,de"
        local _xkb_variants="$(echo "$CP_DCV_XKB_LAYOUTS" | tr -dc ',')"
        \cp "$CP_DCV_XFCE_TEMPLATES_DIR/keyboard-layout.xml" "$CP_DCV_XFCONF_DIR/keyboard-layout.xml"
        sed -i -e "s|_XKB_LAYOUTS_|$CP_DCV_XKB_LAYOUTS|g" \
               -e "s|_XKB_VARIANTS_|$_xkb_variants|g" \
               -e "s|_XKB_TOGGLE_|$CP_DCV_XKB_TOGGLE|g" "$CP_DCV_XFCONF_DIR/keyboard-layout.xml"
    else
        # Without the plugin there is no way to switch the layouts back, so a single
        # (default) layout is kept and the plugin is dropped from the panel
        log_msg "[WARNING] Keyboard layout switcher (xfce4-xkb-plugin) is not installed, it will be excluded from the panel"
        sed -i '/<!--XKB-->/,/<!--\/XKB-->/d' "$CP_DCV_XFCONF_DIR/xfce4-panel.xml"
    fi
}

function wait_for_xfce_session() {
    # xfconf-query connects to the session dbus, which is started by "startxfce4".
    # xfdesktop is used as an indicator, that the session (and dbus) is up and running
    local _iteration
    for _iteration in $(seq 1 "$CP_DCV_XFCE_STARTUP_TIMEOUT"); do
        pgrep -U "$(id -u)" -x xfdesktop >/dev/null 2>&1 && return 0
        sleep 1
    done
    log_msg "[WARNING] Xfce session is still not running after $CP_DCV_XFCE_STARTUP_TIMEOUT seconds"
    return 1
}

function disable_desktop_backdrop() {
    if ! command -v xfconf-query >/dev/null 2>&1; then
        log_msg "[WARNING] xfconf-query is not installed, a default Xfce wallpaper will be used"
        return 0
    fi

    # A backdrop is configured per monitor (a RandR output name) and per workspace,
    # so the monitors, registered by xfdesktop, are resolved first
    local _monitors=""
    local _iteration
    for _iteration in $(seq 1 "$CP_DCV_XFCE_STARTUP_TIMEOUT"); do
        _monitors="$(xfconf-query -c xfce4-desktop -l 2>/dev/null \
                     | sed -n 's|^/backdrop/\(screen[0-9]*/[^/]*\)/.*|\1|p' | sort -u)"
        [ "$_monitors" ] && break
        sleep 1
    done
    if [ -z "$_monitors" ]; then
        _monitors="$(xrandr --query 2>/dev/null | sed -n 's|^\([^ ]\{1,\}\) connected.*|screen0/monitor\1|p')"
        _monitors="${_monitors:-screen0/monitor0}"
        log_msg "[WARNING] Xfce backdrop properties are not registered, falling back to: $(echo $_monitors)"
    fi

    # A single set of the backdrop properties is applied to all the workspaces
    xfconf-query -c xfce4-desktop -p "/backdrop/single-workspace-mode" -n -t bool -s true
    local _monitor
    for _monitor in $_monitors; do
        # "image-style=0" stands for "None", i.e. a solid color is used instead of a wallpaper
        xfconf-query -c xfce4-desktop -p "/backdrop/$_monitor/workspace0/image-style" -n -t int -s 0
        xfconf-query -c xfce4-desktop -p "/backdrop/$_monitor/workspace0/last-image" -n -t string -s ""
    done
    command -v xfdesktop >/dev/null 2>&1 && xfdesktop --reload
    log_msg "Xfce desktop wallpaper is disabled"
}

function configure_keyboard_layout() {
    # xfsettingsd applies the keyboard-layout.xml on its own, setxkbmap is used
    # to cover the cases, when the xfsettingsd keyboard plugin is not available
    if [ ! -f "$CP_DCV_XFCONF_DIR/keyboard-layout.xml" ]; then
        return 0
    fi
    if ! command -v setxkbmap >/dev/null 2>&1; then
        log_msg "[WARNING] setxkbmap is not installed, keyboard layouts are configured by xfsettingsd only"
        return 0
    fi
    setxkbmap -model "$CP_DCV_XKB_MODEL" \
              -layout "$CP_DCV_XKB_LAYOUTS" \
              -option "$CP_DCV_XKB_TOGGLE"
    log_msg "Keyboard layouts are set to $CP_DCV_XKB_LAYOUTS ($CP_DCV_XKB_TOGGLE to switch)"
}

if [ "${1:-}" == "--runtime" ]; then
    wait_for_xfce_session
    disable_desktop_backdrop
    configure_keyboard_layout
    exit 0
fi

configure_xfce

# The rest of the configuration is applied in background, as it requires a running Xfce session
bash "$CP_DCV_LAUNCH_SCRIPT_PATH" --runtime &

exec startxfce4
EOF
chmod +x "$CP_DCV_EXTRAS_DIR/xfce4launch"

  if [ ! -x "$CP_DCV_EXTRAS_DIR/xfce4launch" ]; then
    pipe_log_fail "[ERROR] Cannot create a DCV session initialization script at $CP_DCV_EXTRAS_DIR/xfce4launch" "$DCV_INSTALL_TASK"
    exit 1
  fi
}

function run_dcv {
  pipe_log_info "Starting DCV server and waiting for boot up" "$DCV_INSTALL_TASK"
  if [[ "$IS_RPM_BASED" = 0 ]]; then
    systemctl start dbus
    systemctl start dcvserver
  else
    service dbus start
    nohup dcvserver --service &> /var/log/dcv/server.log &
  fi

  # Wait until dcv server will be ready
  for _RETRY_ITERATION in $(seq 1 "$_RETRIES_COUNT"); do
      curl -k -s "https://localhost:$CP_DCV_WEB_PORT/" &> /dev/null
      _CHECK_RESULT=$?

      if [ $_CHECK_RESULT -ne 0 ]; then
        pipe_log_warn "[WARNING] DCV server is still not running. Try #${_RETRY_ITERATION}." "$DCV_INSTALL_TASK"
        sleep "$_RETRIES_TIMEOUT"
      else
        pipe_log_info "[INFO] DCV server is running. Proceeding." "$DCV_INSTALL_TASK"
        break
      fi
  done

  if [ $_CHECK_RESULT -ne 0 ]; then
      pipe_log_fail "[ERROR] DCV server cannot be run." "$DCV_INSTALL_TASK"
      exit 1
  fi

  # We may want to delay session creation, as the subsequent scripts may want to modify the user's profile
  # Which won't be possible once the session is created and a process is running on the user's behalf
  # So we shall set 'CP_DCV_DELAY_SESSION_CREATION=true' and then call 'nice_dcv_create_session' in the 
  # next execution steps
  if [ "$CP_DCV_DELAY_SESSION_CREATION" == "true" ]; then
    pipe_log_warn "DCV session will NOT be created now as the CP_DCV_DELAY_SESSION_CREATION is set to 'true'. Make sure to run 'nice_dcv_create_session' before the user can login." "$DCV_INSTALL_TASK"
  else
    nice_dcv_create_session
  fi

  # Serve additional server to provide dcv desktop session file
  if [ -n "${CP_DCV_DESKTOP_PORT}" ]; then
      pipe_log_info "Run DCV desktop launcher" "$DCV_INSTALL_TASK"
      nohup "${CP_PYTHON2_PATH}" "${COMMON_REPO_DIR}/scripts/serve_desktop.py" \
          --serving-port "${CP_DCV_DESKTOP_PORT}" \
          --desktop-port "${CP_DCV_WEB_PORT}" \
          --template-path "${COMMON_REPO_DIR}/resources/linux/template.dcv" \
          &> "/var/log/nice_dcv_desktop.log" &
  else
      pipe_log_warn "CP_DCV_DESKTOP_PORT is not set. Desktop endpoint will not work! Use WEB endpoint instead." "$DCV_INSTALL_TASK"
  fi
}

function check_dcv_installation {
  if [[ "$IS_RPM_BASED" = 0 ]]; then
    rpm -qa | grep dcv
  else
    dpkg -l | grep dcv
  fi
}

######################################################
# Check if this is a RPM Linux distribution
######################################################
/usr/bin/rpm -q -f /usr/bin/rpm >/dev/null 2>&1
export IS_RPM_BASED=$?

######################################################
# Check cloud platform
######################################################
if [[ "${CLOUD_PROVIDER}" -ne "AWS" ]]; then
    pipe_log_fail "Cloud ${CLOUD_PROVIDER} is not supported, exiting." "$DCV_INSTALL_TASK"
    exit 1
fi

export CP_DCV_DESKTOP_PORT="${CP_DCV_DESKTOP_PORT:-$CP_CAP_DCV_DESKTOP_PORT}"
if [ -z $CP_DCV_DESKTOP_PORT ]; then
    pipe_log_warn "DCV desktop port is not set (CP_DCV_DESKTOP_PORT). Default 8099 will be used." "$DCV_INSTALL_TASK"
    export CP_DCV_DESKTOP_PORT=8099
fi

export CP_DCV_WEB_PORT="${CP_DCV_WEB_PORT:-$CP_CAP_DCV_WEB_PORT}"
if [ -z $CP_DCV_WEB_PORT ]; then
    pipe_log_warn "DCV web port is not set (CP_DCV_WEB_PORT). Default 8100 will be used." "$DCV_INSTALL_TASK"
    export CP_DCV_WEB_PORT=8100
fi
check_dcv_installation
IS_DCV_INSTALLED=$?

if [ $IS_DCV_INSTALLED -eq 0 ]; then
   pipe_log_info "--> DCV installed already" "$DCV_INSTALL_TASK"
else
   install_prerequisites && \
   install_dcv && \
   configure_dcv

   if [ $? -ne 0 ]; then
    pipe_log_fail "[ERROR] DCV installation failed. Exiting" "$DCV_INSTALL_TASK"
    exit 1
   fi
fi

# Extras are (re)configured even if DCV is preinstalled in an image, as they only
# define a desktop session bootstrapping and do not modify the DCV installation itself
configure_dcv_extras

run_dcv
pipe_log_success "[INFO] DCV server is ready." "$DCV_INSTALL_TASK"
