#!/usr/bin/env bash
# Copyright 2017-2020 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

COMMAND_TEXT=$1
DEFAULT_TASK_NAME=$2

# Check global variables
if [ -z "$API" ]
  then
    echo "[ERROR] API Url is not set"
	  exit 1
fi

if [ -z "$RUN_ID" ]
  then
    echo "[ERROR] Run ID is not set"
	  exit 1
fi

if [ -z "$LOG_DIR" ]
  then
    echo "[WARN] Log directory is not set, using /runs"
	  export LOG_DIR=/runs
fi

# Check arguments
if [ -z "$COMMAND_TEXT" ]
  then
    echo "[ERROR] Command text shall be supplied"
	  exit 1
fi

if [ -z "$DEFAULT_TASK_NAME" ]
  then
    echo "[ERROR] Default task name shall be supplied"
	  exit 1
fi


if [ -z "$LOG_TO_CONSOLE" ]
then
    LOG_TO_CONSOLE=False
else
    LOG_TO_CONSOLE=True
fi

if [ -z "$LOG_BUFFER_SIZE" ]
then
    LOG_BUFFER_SIZE=10000
fi


# Execute command
CMD="import pipeline; command=pipeline.LoggedCommand(\"${COMMAND_TEXT}\", None, \"${DEFAULT_TASK_NAME}\", buffer_size=${LOG_BUFFER_SIZE}, log_stdout=${LOG_TO_CONSOLE}); command.execute();"
$CP_PYTHON2_PATH -c "$CMD"
result=$?

exit $result
