#!/usr/bin/env bash
# Copyright 2017-2020 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PIPELINE_NAME=$1

if [ -z "$PIPELINE_NAME" ]
then
    echo "[ERROR] Pipeline name is not set."
	exit 1
fi

GITFS_INSTALL=0

command -v gitfs >/dev/null 2>&1 && { GITFS_INSTALL=1;  };

if [ $GITFS_INSTALL -ne 0 ] ;
then
    PIPELINE_MOUNT=${REPOSITORY_MOUNT}/${PIPELINE_NAME}
    mkdir -p ${REPOSITORY_MOUNT}
    mkdir -p ${PIPELINE_MOUNT}
    MOUNT_COMMAND=$($CP_PYTHON2_PATH ${COMMON_REPO_DIR}/scripts/clone_pipeline.py --pipeline ${PIPELINE_NAME})
    gitfs  "${MOUNT_COMMAND}" "${PIPELINE_MOUNT}" -o log=${LOG_DIR}/gitfs.log,allow_other=true
    if [ $? -ne 0 ]
    then
        echo "[ERROR] Failed to mount git repository"
        exit 1
    else
        _REPOSITORY_MOUNT_SRC="${REPOSITORY_MOUNT}/${PIPELINE_NAME}/current"
        _REPOSITORY_HOME="$HOME/code-repository"
        if [ -d "$_REPOSITORY_MOUNT_SRC" ]; then
            mkdir -p ${_REPOSITORY_HOME}
            if [ -d "$_REPOSITORY_MOUNT_SRC/src" ]; then
                  ln -s "$_REPOSITORY_MOUNT_SRC/src" "$_REPOSITORY_HOME/${PIPELINE_NAME}"
            else
                  ln -s "$_REPOSITORY_MOUNT_SRC" "$_REPOSITORY_HOME/${PIPELINE_NAME}"
            fi
        else
            echo "$_REPOSITORY_MOUNT_SRC not found, no code repository will be available"
        fi
    fi
else
    echo "[ERROR] Gitfs is not installed."
    exit 1
fi
