#!/bin/bash
# NOTE 1: The difference between this script and pipe_notify is that this one is compatible with standard
# /bin/mail program and can be replacement for it.
# It can be very convenient and for some cases even necessary (f.i. integration with Slurm ang SGE)
#
# NOTE 2: Currently supports only bare minimal of options from original /bin/mail program (-s and receiver)
#
# See https://www.commandlinux.com/man-page/man1/mail.1.html for the information about all args

_PIPE_MAIL_LOG_FILE="/var/log/pipe_mail.log"

echo "Start sending emails to pipeline users" >> ${_PIPE_MAIL_LOG_FILE}

echo "Getting envs from /etc/cp_env.sh" >> ${_PIPE_MAIL_LOG_FILE}
source /etc/cp_env.sh

echo "Parsing args: $@" >> ${_PIPE_MAIL_LOG_FILE}
POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    -a|-b|-c|-u) # skipping unused key-value args of /bin/mail program
    shift # past argument
    shift # past value
    ;;
    -d|-E|-f|-I|-i|-N|-n|-v) # skipping unused flag args of /bin/mail program
    shift # past argument
    ;;
    -s) # Subject of the email to be sent
    export _NOTIFICATION_SUBJECT="Run #$RUN_ID. Job info: $2"
    shift # past argument
    shift # past value
    ;;
    *)    # save positional args
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

echo "Sending emails to: $@" >> ${_PIPE_MAIL_LOG_FILE}
while [[ $# -gt 0 ]]
do
    export _to_user="$1"
    echo "Sending to $_to_user ..." >> ${_PIPE_MAIL_LOG_FILE}

    if [ ! -f "$DEFAULT_HOSTFILE" ]; then
            _NODE_NAMES="$(hostname)"
    else
        IFS=$'\n' read -d '' -r -a _NODE_NAMES < "$DEFAULT_HOSTFILE"
    fi

    for _NODE in ${_NODE_NAMES[*]} ; do
        if [[ "$_to_user" == *"$_NODE"* ]]; then
            _to_user_and_hostname="$_to_user"
            IFS='@' read -r -a user_info <<< "$_to_user"
            export _to_user="${user_info[0]}"
            echo "Got username $_to_user from username@host record $_to_user_and_hostname" >> ${_PIPE_MAIL_LOG_FILE}
            break
        fi
    done

    if [[ "$_to_user" == "root" ]]; then
        echo "Job owner is $_to_user, changing receiver to $REMOTE_OWNER" >> ${_PIPE_MAIL_LOG_FILE}
        export _to_user="$REMOTE_OWNER"
    fi

    pipe_notify "$_NOTIFICATION_SUBJECT" "$_NOTIFICATION_SUBJECT" "$_to_user" &>> ${_PIPE_MAIL_LOG_FILE}
    shift # skip email that was already processed
done

echo "Done sending emails to pipeline users" >> ${_PIPE_MAIL_LOG_FILE}
echo >> ${_PIPE_MAIL_LOG_FILE}
