#!/usr/bin/env bash
# Copyright 2017-2024 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

TAG_NAME="$1"
TAG_VALUE="${2:-true}"

# Check arguments
if [ -z "$TAG_NAME" ]; then
    echo "[ERROR] TAG_NAME shall be supplied"
	  exit 1
fi

# Call API
CMD="from pipeline import PipelineAPI; api = PipelineAPI(\"${API}\", \"${LOG_DIR}\"); tags={\"$TAG_NAME\": \"$TAG_VALUE\"}; api.update_pipeline_run_tags(\"${RUN_ID}\", tags, keep_existing_tags=True)"
$CP_PYTHON2_PATH -c "$CMD"
