#!/usr/bin/env bash
# Copyright 2017-2020 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Check global variables
if [ -z "$API" ]
  then
    echo "[ERROR] API Url is not set"
	  exit 1
fi

TASK_NAME=""

while getopts "ec:d:p:t:" options; do
  case $options in
    e ) PASS_ENV=true;;
	c ) CMD_TEXT=$OPTARG;;
	d ) DOCKER=$OPTARG;;
	p ) PARENT_ID=$OPTARG;;
	t ) TASK_NAME=$OPTARG
  esac
done
shift $(($OPTIND - 1))

# Check arguments
if [ -z "$CMD_TEXT" ]
  then
    echo "[ERROR] Command shall be supplied"
	  exit 1 -c
fi

if [ -z "$DOCKER" ]
  then
    echo "[ERROR] Docker image shall be supplied"
	  exit 1
fi

if [ -z "$PARENT_ID" ]
  then
    echo "[ERROR] Parent RUN_ID shall be supplied"
	  exit 1
fi

# Execute command
CMD="import pipeline; launcher = pipeline.PodLauncher(task_name=\"${TASK_NAME}\"); launcher.launch_pod($PARENT_ID, \"${CMD_TEXT}\", \"$DOCKER\", pass_env_vars=\"${PASS_ENV}\");"
$CP_PYTHON2_PATH -c "$CMD"
result=$?

exit $result
