#!/bin/bash
# Copyright 2017-2020 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "Linking $COMMON_REPO_DIR_MUTUAL_LOC/shell/pipe_mail as default linux mail client"
rm -rf "/usr/bin/mail" && ln -s "$COMMON_REPO_DIR_MUTUAL_LOC/shell/pipe_mail" "/usr/bin/mail" \
    && rm -rf "/bin/mail" && ln -s "$COMMON_REPO_DIR_MUTUAL_LOC/shell/pipe_mail" "/bin/mail"
if [ "$?" -eq "0" ]; then
    echo "Successfully linked $COMMON_REPO_DIR_MUTUAL_LOC/shell/pipe_mail as default linux mail client"
else
    echo "Fail to link $COMMON_REPO_DIR_MUTUAL_LOC/shell/pipe_mail"
fi
