#!/usr/bin/env bash

# Copyright 2017-2020 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Usage examples:
#
# pipe_get_preference "launch.dind.container.vars"
#
# pipe_get_preference "launch.dind.container.vars" \
#                     "http_proxy,https_proxy,no_proxy,API,API_TOKEN"
#

# Required args
PREFERENCE="$1"
# Optional args
DEFAULT_VALUE="$2"

# Check global variables
if [ -z "$LOG_DIR" ]
  then
    echo "[WARN] Log directory is not set, using /runs"
	  export LOG_DIR=/runs
fi

# Check arguments
if [ -z "$PREFERENCE" ]
  then
    echo "[ERROR] Preference name shall be supplied"
	  exit 1
fi

# Call preferences API
CMD="import pipeline.api;"
CMD="${CMD} pipe=pipeline.api.PipelineAPI(\"${API}\", \"${LOG_DIR}\");"
CMD="${CMD} print(pipe.get_preference('${PREFERENCE}').get('value', ''))"
VALUE=$($CP_PYTHON2_PATH -c "$CMD")
if [[ "$?" == "0" && "$VALUE" ]]
then
  echo "$VALUE"
else
  echo "$DEFAULT_VALUE"
fi
