#!/usr/bin/env bash

# Copyright 2017-2020 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Removes host record from /etc/hosts file as well as default hostfile using file system locking.
# It prevents possible race condition during host files modification.
#
# Usage examples:
#
# remove_from_hosts "pipeline-12345"

# Required args
WORKER_HOST="$1"

LOCK_FILE="/var/run/hosts-modification.lock"
DEFAULT_HOSTFILE="${DEFAULT_HOSTFILE:-/common/hostfile}"

COMMAND="sed '/\t$WORKER_HOST$/d' /etc/hosts > /etc/hosts_modified; cp /etc/hosts_modified /etc/hosts; rm /etc/hosts_modified;
         sed '/^$WORKER_HOST$/d' '$DEFAULT_HOSTFILE' > '${DEFAULT_HOSTFILE}_modified'; cp '${DEFAULT_HOSTFILE}_modified' '$DEFAULT_HOSTFILE'; rm '${DEFAULT_HOSTFILE}_modified'"

flock -w 10 "$LOCK_FILE" bash -c "$COMMAND"
