#!/usr/bin/env bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

###############################################################################
# Set git credentials.
###############################################################################

error=$(tput setaf 1)
normal=$(tput sgr0)
message="${error}Must be set and not be empty.${normal}"

api_host_url=${API:?${message}}
api_token=${API_TOKEN:?${message}}
api_pipeline_credentials_url="${api_host_url}/pipeline/git/credentials"

git_credentials=$(curl --silent --insecure \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer ${api_token}" \
  ${api_pipeline_credentials_url})

git_url=$(echo ${git_credentials} | ${CP_PYTHON2_PATH} -c 'import sys, json; print(json.load(sys.stdin)["payload"]["url"])')
git_username=$(echo ${git_credentials} | ${CP_PYTHON2_PATH} -c 'import sys, json; print(json.load(sys.stdin)["payload"]["userName"])')
git_email=$(echo ${git_credentials} | ${CP_PYTHON2_PATH} -c 'import sys, json; print(json.load(sys.stdin)["payload"]["email"])')

git_credentials_file="/git/config/credentials"
mkdir -p $(dirname "$git_credentials_file") && touch "$git_credentials_file"
echo ${git_url} > ${git_credentials_file}
git config --global credential.helper "store --file ${git_credentials_file}"
git config --global http.sslVerify "false"
git config --global user.name ${git_username}
git config --global user.email ${git_email}