#!/usr/bin/env bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_CURRENT_EXEC_NODE_NAME=$1
_SGE_RESOURCES_SETUP_TASK=$2
_NODE_CPU_COUNT=$3

function configure_consumable_sge_resource {
    RESOURCE_NAME="$1"
    RESOURCE_TYPE="$2"
    RESOURCE_DEFAULT="$3"
    RESOURCE_VALUE="$4"
    RESOURCE_CONSUMABLE_TYPE="$5"
    RESOURCE_RELOP="$6"

    # Add consumable resource if it is master node, this shall be done once
    if [[ "$cluster_role" = "master" ]]; then
        add_consumable_sge_resource "$RESOURCE_NAME" "$RESOURCE_TYPE" "$RESOURCE_DEFAULT" "$RESOURCE_CONSUMABLE_TYPE" "$RESOURCE_RELOP"
    fi

    # Add consumable resource capacity for a current execution host
    add_sge_resource_capacity "$RESOURCE_NAME" "$RESOURCE_VALUE"
}

function add_consumable_sge_resource {
    RESOURCE_NAME="$1"
    RESOURCE_TYPE="$2"
    RESOURCE_DEFAULT="$3"
    RESOURCE_CONSUMABLE_TYPE="$4"
    RESOURCE_RELOP="$5"

    _CONFIG_FILE=/tmp/complex_${_CURRENT_EXEC_NODE_NAME}.txt
    qconf -sc > "$_CONFIG_FILE"
    # First remove any line, which start with the resource name, in case it already exists
    # Otherwise - resource won't be added/modified
    sed -i "/^$RESOURCE_NAME /d" "$_CONFIG_FILE"
    echo "$RESOURCE_NAME $RESOURCE_NAME $RESOURCE_TYPE $RESOURCE_RELOP YES $RESOURCE_CONSUMABLE_TYPE $RESOURCE_DEFAULT 0" >> "$_CONFIG_FILE"
    qconf -Mc "$_CONFIG_FILE"
    rm "$_CONFIG_FILE"
    pipe_log_info "Added GridEngine consumable resource: $RESOURCE_NAME" "$_SGE_RESOURCES_SETUP_TASK"
}

function add_sge_resource_capacity {
    RESOURCE_NAME="$1"
    RESOURCE_VALUE="$2"

    qconf -aattr exechost complex_values "$RESOURCE_NAME=$RESOURCE_VALUE" "$_CURRENT_EXEC_NODE_NAME"
    pipe_log_info "Added $RESOURCE_NAME=$RESOURCE_VALUE for $_CURRENT_EXEC_NODE_NAME execution host" "$_SGE_RESOURCES_SETUP_TASK"
}

if [[ -z "$_SGE_RESOURCES_SETUP_TASK" ]]; then
    _SGE_RESOURCES_SETUP_TASK="SGESetupResources"
fi

if [[ -z "$_CURRENT_EXEC_NODE_NAME" ]]; then
    pipe_log_info "Execution node name is not set, using ${HOSTNAME}" "$_SGE_RESOURCES_SETUP_TASK"
    _CURRENT_EXEC_NODE_NAME="$HOSTNAME"
fi

#
# Setup GPU, RAM, CPU consumable resources for a current node
#
_NODE_GPUS_COUNT=$(nvidia-smi -L 2>/dev/null | wc -l)
_NODE_GPUS_COUNT="${_NODE_GPUS_COUNT:-0}"
CP_CAP_GE_CONSUMABLE_RESOURCE_NAME_GPU=${CP_CAP_GE_CONSUMABLE_RESOURCE_NAME_GPU:-gpus}
CP_CAP_GE_CONSUMABLE_RESOURCE_CONSUMABLE_TYPE_GPU=${CP_CAP_GE_CONSUMABLE_RESOURCE_CONSUMABLE_TYPE_GPU:-JOB}
pipe_log_info "$_NODE_GPUS_COUNT GPUs found" "$_SGE_RESOURCES_SETUP_TASK"

if (( _NODE_GPUS_COUNT > 0 )) && check_cp_cap "CP_CAP_SGE_GPU_EXCLUSIVE_MODE"; then
    nvidia-smi -e 0
    nvidia-smi -c 3
    nvidia-smi -pm 1
    pipe_log_info "GPUs are set to exclusive mode via CP_CAP_SGE_GPU_EXCLUSIVE_MODE" "$_SGE_RESOURCES_SETUP_TASK"
fi

if (( _NODE_GPUS_COUNT > 0 )) && check_cp_cap "CP_CAP_SGE_GPU_RSMAP_DEVICES"; then
    CP_CAP_GE_CONSUMABLE_RESOURCE_LOCKS_GPU="${CP_CAP_GE_CONSUMABLE_RESOURCE_LOCKS_GPU:-/tmp/sge-gpus-locks}"
    mkdir -p "$CP_CAP_GE_CONSUMABLE_RESOURCE_LOCKS_GPU/total"
    for DEVICE_ID in $(seq 0 "$(( _NODE_GPUS_COUNT - 1 ))"); do
        mkdir "$CP_CAP_GE_CONSUMABLE_RESOURCE_LOCKS_GPU/total/$DEVICE_ID"
    done
    mkdir -p "$CP_CAP_GE_CONSUMABLE_RESOURCE_LOCKS_GPU/inuse"
    chmod g+rw,o+rw "$CP_CAP_GE_CONSUMABLE_RESOURCE_LOCKS_GPU/inuse" -R
    setfacl -d -m user::rwx -m group::rwx -m other::rwx "$CP_CAP_GE_CONSUMABLE_RESOURCE_LOCKS_GPU/inuse"
    pipe_log_info "GPUs are managed as RSMAP devices via CP_CAP_SGE_GPU_RSMAP_DEVICES" "$_SGE_RESOURCES_SETUP_TASK"
fi

_NODE_RAM_COUNT=$(grep MemTotal /proc/meminfo | awk '{print int($2 / (1024 * 1024)) "G"}')
CP_CAP_GE_CONSUMABLE_RESOURCE_NAME_RAM=${CP_CAP_GE_CONSUMABLE_RESOURCE_NAME_RAM:-ram}
CP_CAP_GE_CONSUMABLE_RESOURCE_CONSUMABLE_TYPE_RAM=${CP_CAP_GE_CONSUMABLE_RESOURCE_CONSUMABLE_TYPE_RAM:-YES}
pipe_log_info "$_NODE_RAM_COUNT RAM found" "$_SGE_RESOURCES_SETUP_TASK"

if [ -z "$_NODE_CPU_COUNT" ]; then
    _NODE_CPU_COUNT=$(nproc)
fi
# Using "n_cpu", which is a number of available CPUs == slots, instead of "cpu" here as:
#   "cpu" is a "built in" resource
#   It is automatically calculated, based on the real cpu utilization in %% (reported by the "load_values"), e.g.:
# ```
# $ qconf -se pipeline-46089
# hostname              pipeline-46089
# complex_values        ram=7G
# load_values           load_avg=10.740000,load_short=10.620000, \
#                       ...
#                       virtual_used=1466.832031M,cpu=100.000000
# ```
CP_CAP_GE_CONSUMABLE_RESOURCE_NAME_CPU=${CP_CAP_GE_CONSUMABLE_RESOURCE_NAME_CPU:-n_cpu}
CP_CAP_GE_CONSUMABLE_RESOURCE_CONSUMABLE_TYPE_CPU=${CP_CAP_GE_CONSUMABLE_RESOURCE_CONSUMABLE_TYPE_CPU:-JOB}
pipe_log_info "$_NODE_CPU_COUNT CPUs found" "$_SGE_RESOURCES_SETUP_TASK"

# "exclusive" resource can be used to schedule jobs which occupy a whole node
# See: http://web.archive.org/web/20130706011021/http://docs.oracle.com/cd/E24901_01/doc.62/e21978/management.htm#autoId61
CP_CAP_GE_CONSUMABLE_RESOURCE_NAME_EXCLUSIVE=${CP_CAP_GE_CONSUMABLE_RESOURCE_NAME_EXCLUSIVE:-exclusive}

pipe_log_info "Starting GridEngine resources configuration..." "$_SGE_RESOURCES_SETUP_TASK"

# Changed consumable type of the "n_cpu" and "gpus" resources to "JOB" (see http://www.softpanorama.org/HPC/Grid_engine/Resources/sge_consumable_resources.shtml)
# If it is set to "YES", the resource request is multiplied by "slots"
# So we if we run "qsub -pe local 3 -l n_cpu=3", it will require 3*3=9 n_cpu per job
# For the "ram" resource, keeping it as "YES", as it makes sense to request this resource per slot

# For the CPU-only nodes, we still add "gpus" resource with value "0", so that the scripts do not fail if the request "-l gpus=N"
configure_consumable_sge_resource "$CP_CAP_GE_CONSUMABLE_RESOURCE_NAME_GPU" "INT" "0" "$_NODE_GPUS_COUNT" "$CP_CAP_GE_CONSUMABLE_RESOURCE_CONSUMABLE_TYPE_GPU" "<="
configure_consumable_sge_resource "$CP_CAP_GE_CONSUMABLE_RESOURCE_NAME_RAM" "MEMORY" "0G" "$_NODE_RAM_COUNT" "$CP_CAP_GE_CONSUMABLE_RESOURCE_CONSUMABLE_TYPE_RAM" "<="
configure_consumable_sge_resource "$CP_CAP_GE_CONSUMABLE_RESOURCE_NAME_CPU" "INT" "0" "$_NODE_CPU_COUNT" "$CP_CAP_GE_CONSUMABLE_RESOURCE_CONSUMABLE_TYPE_CPU" "<="
# We also add a predefined value for slots as it is not exposed by default
# This can be handy when using "fill up" scheduling approach: http://talby.rcs.manchester.ac.uk/~ri/_notes_sge/least_used_vs_fill_up.html
CP_CAP_GE_CONSUMABLE_RESOURCE_SLOTS_ENABLED="${CP_CAP_GE_CONSUMABLE_RESOURCE_SLOTS_ENABLED:-true}"
if [ "$CP_CAP_GE_CONSUMABLE_RESOURCE_SLOTS_ENABLED" == "true" ]; then
    qconf -aattr exechost complex_values "slots=$_NODE_CPU_COUNT" "$_CURRENT_EXEC_NODE_NAME"
fi

if [ "$CP_CAP_GE_CONSUMABLE_RESOURCE_EXCLUSIVE_ENABLED" != "false" ]; then
    configure_consumable_sge_resource "$CP_CAP_GE_CONSUMABLE_RESOURCE_NAME_EXCLUSIVE" "BOOL" "0" "true" "YES" "EXCL"
else
    pipe_log_info "Skipping $CP_CAP_GE_CONSUMABLE_RESOURCE_NAME_EXCLUSIVE configuration as CP_CAP_GE_CONSUMABLE_RESOURCE_EXCLUSIVE_ENABLED == $CP_CAP_GE_CONSUMABLE_RESOURCE_EXCLUSIVE_ENABLED" "$_SGE_RESOURCES_SETUP_TASK"
fi

# The worker_type is not used as a consumable, but can be added to the "load_formula" https://gridscheduler.sourceforge.net/htmlman/htmlman5/sched_conf.html
# Setting load_formula to worker_type will make SGE prioritize static workers before autoscaled
# https://github.com/epam/cloud-pipeline/issues/825
CP_CAP_GE_CONSUMABLE_RESOURCE_WORKER_TYPE_ENABLED="${CP_CAP_GE_CONSUMABLE_RESOURCE_WORKER_TYPE_ENABLED:-true}"
if [ "$CP_CAP_GE_CONSUMABLE_RESOURCE_WORKER_TYPE_ENABLED" == "true" ]; then
    CP_CAP_GE_CONSUMABLE_RESOURCE_NAME_WORKER_TYPE="worker_type"
    CP_CAP_GE_CONSUMABLE_RESOURCE_DEFAULT_VALUE_WORKER_TYPE_STATIC="${CP_CAP_GE_CONSUMABLE_RESOURCE_DEFAULT_VALUE_WORKER_TYPE_STATIC:-0}"
    CP_CAP_GE_CONSUMABLE_RESOURCE_DEFAULT_VALUE_WORKER_TYPE_ADD="${CP_CAP_GE_CONSUMABLE_RESOURCE_DEFAULT_VALUE_WORKER_TYPE_ADD:-1000}"
    if [ "$cluster_role" == master ] || [ "$cluster_role_type" != "additional" ]; then
        _NODE_WORKER_TYPE_WEIGHT="$CP_CAP_GE_CONSUMABLE_RESOURCE_DEFAULT_VALUE_WORKER_TYPE_STATIC"
    elif [ "$cluster_role_type" == "additional" ]; then
        _NODE_WORKER_TYPE_WEIGHT="$CP_CAP_GE_CONSUMABLE_RESOURCE_DEFAULT_VALUE_WORKER_TYPE_ADD"
    fi
    configure_consumable_sge_resource "$CP_CAP_GE_CONSUMABLE_RESOURCE_NAME_WORKER_TYPE" "INT" "0" "$_NODE_WORKER_TYPE_WEIGHT" "JOB" "<="
    
    if [ "$CP_CAP_SGE_DEFAULT_LOAD_FORMULA" ] && [ "$cluster_role" == master ]; then
        pipe_log_info "CP_CAP_SGE_DEFAULT_LOAD_FORMULA is set to ${CP_CAP_SGE_DEFAULT_LOAD_FORMULA}. Configuring scheduler." "$_SGE_RESOURCES_SETUP_TASK"
        
        qconf -ssconf > /tmp/sge_scheduler.conf
        sed -i '/^load_formula/d' /tmp/sge_scheduler.conf
        echo "load_formula $CP_CAP_SGE_DEFAULT_LOAD_FORMULA" >> /tmp/sge_scheduler.conf
        qconf -Msconf /tmp/sge_scheduler.conf
        
        if [ $? -ne 0 ]; then
            pipe_log_warn "Failed configuring load_formula in SGE scheduler" "$_SGE_RESOURCES_SETUP_TASK"  
        else
            pipe_log_info "SGE scheduler load_formula is set to $CP_CAP_SGE_DEFAULT_LOAD_FORMULA" "$_SGE_RESOURCES_SETUP_TASK"  
        fi
        rm -f /tmp/sge_scheduler.conf
    fi
fi

pipe_log_success "Finished GridEngine resources configuration" "$_SGE_RESOURCES_SETUP_TASK"
