#!/usr/bin/env bash

# Copyright 2017-2023 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SLURM_MASTER_SETUP_TASK="SLURMMasterSetup"
SLURM_CONFIG_PATH="${1:-/common/.slurm/slurm.conf}"

if [ ! -f "$SLURM_CONFIG_PATH" ]; then
    pipe_log_fail "SLURM config file not found at ${SLURM_CONFIG_PATH}, partitions won't be configured" "$SLURM_MASTER_SETUP_TASK"
    exit 1
fi

# Create nodeset
if ! grep "# NODESETS" $SLURM_CONFIG_PATH -q &> /dev/null; then
    sed -i '/# PARTITIONS/i# NODESETS' "$SLURM_CONFIG_PATH"
fi

SLURM_NS_SPEC="Nodeset=ns-$CP_CAP_SLURM_QUEUE_NAME Feature=$CP_CAP_SLURM_QUEUE_NAME"
sed -i "/# NODESETS/a$SLURM_NS_SPEC" "$SLURM_CONFIG_PATH"
pipe_log_info "Added nodeset: $SLURM_NS_SPEC" "$SLURM_MASTER_SETUP_TASK"

# Create partition
SLURM_PARTITION_SPEC="PartitionName=$CP_CAP_SLURM_QUEUE_NAME Nodes=ns-$CP_CAP_SLURM_QUEUE_NAME MaxTime=INFINITE State=UP"
sed -i "/# PARTITIONS/a$SLURM_PARTITION_SPEC" "$SLURM_CONFIG_PATH"
pipe_log_info "Added partition: $SLURM_PARTITION_SPEC" "$SLURM_MASTER_SETUP_TASK"

scontrol reconfigure
