#!/usr/bin/env bash

# Copyright 2017-2020 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_SSH_DIR="$1"
if [ -z "$_SSH_DIR" ]; then
    echo "[ERROR] Path to the SSH directory shall be specified"
    exit 1
fi
if [ ! -d "$_SSH_DIR" ]; then
    echo "[ERROR] $_SSH_DIR SSH directory does not exist"
    exit 1
fi

chmod 700 "$_SSH_DIR"
chmod 600 "$_SSH_DIR"/*
