#!/bin/bash

# Copyright 2017-2024 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# sync_to_storage add /my/folder1
# sync_to_storage add /my/folder2/file
# sync_to_storage start

function echo_debug() {
    if [ "$CP_SYNC_TO_STORAGE_DEBUG" != "true" ]; then
        return
    fi

    echo "[$(date '+%Y-%m-%d %H:%M:%S')][DEBUG] $1"
}

function add_to_spec() {
    local _location_to_add="$(echo ${1%/})"
    local _destination_to_add="$(echo ${2%/})"
    touch "$CP_SYNC_TO_STORAGE_SPEC"

    if [ -n "$_destination_to_add" ]; then
        # Spec already contains a requested location
        if grep -q -x -F "$_location_to_add $_destination_to_add" "$CP_SYNC_TO_STORAGE_SPEC"; then
            return
        fi
        echo "$_location_to_add" "$_destination_to_add" >> "$CP_SYNC_TO_STORAGE_SPEC"
    else
        # Spec already contains a requested location
        if grep -q -x -F "$_location_to_add" "$CP_SYNC_TO_STORAGE_SPEC"; then
            return
        fi
        echo "$_location_to_add" >> "$CP_SYNC_TO_STORAGE_SPEC"
    fi
}

function remove_from_spec() {
    local _location_to_add="$(echo ${1%/})"
    touch "$CP_SYNC_TO_STORAGE_REMOVE_SPEC"

    if grep -q -w -F "$_location_to_add" "$CP_SYNC_TO_STORAGE_SPEC"; then
        # Spec already marked for a deletion
        if grep -q -x -F "$_location_to_add" "$CP_SYNC_TO_STORAGE_REMOVE_SPEC"; then
            return
        fi
        echo "$_location_to_add" >> "$CP_SYNC_TO_STORAGE_REMOVE_SPEC"
    fi
}

function wait_for_pids() {
    local _sync_pids=("$@")
    for pid in ${_sync_pids[*]}; do
        echo_debug "Waiting for pid $pid to finish"
        wait "$pid"
        if [ $? -ne 0 ]; then
            echo "[WARN] Sync process with pid $pid failed"
        fi
    done
}

function perform_sync() {
    local _spec_file=$1

    local _sync_pids=()
    while read -a _sync_config_entry; do
        echo_debug "Processing entry ${_sync_config_entry[*]}"

        local _source_path=${_sync_config_entry[0]}
        _source_path_trim=${_source_path#/}
        _source_path_trim=${_source_path_trim%/}

        local _dest_path
        if [ -n "${_sync_config_entry[1]}" ]; then
          _dest_path=${_sync_config_entry[1]}
        else
          if [ -z "$CP_SYNC_TO_STORAGE_DESTINATION" ]; then
            echo "[WARN] CP_SYNC_TO_STORAGE_DESTINATION is not defined and destination is not provided for entry '${_sync_config_entry[*]}', skipping..."
            continue
          fi
          _dest_path="${CP_SYNC_TO_STORAGE_DESTINATION}/${RUN_ID}/$_source_path_trim"
          echo_debug "Destination path wasn't provided in configuration, will use default one: $_dest_path"
        fi

        echo_debug "Source path: $_source_path Destination path: $_dest_path"

        if [ ! -d "$_source_path" ] && [ ! -f "$_source_path" ]; then
            echo_debug "$_source_path not found"
            continue
        fi

        local _pipe_extra_args="${CP_SYNC_TO_STORAGE_PIPE_EXTRA_ARGS}"
        if [ -d "$_source_path" ]; then
            _pipe_extra_args="$_pipe_extra_args -r"
        fi
        if [ "$CP_SYNC_TO_STORAGE_DEBUG" != "true" ]; then
            _pipe_extra_args="$_pipe_extra_args -q"
        fi
        echo_debug "pipe extra args: $_pipe_extra_args"

        echo_debug "destination path: $_dest_path"

        local _pipe_command="pipe storage cp -f \"$_source_path\" \"$_dest_path\" $_pipe_extra_args"
        echo_debug "pipe command: $_pipe_command"

        if [ "$CP_SYNC_TO_STORAGE_THREADS" -gt 1 ]; then
            eval "$_pipe_command" &
            _sync_process_pid=$!
            echo_debug "Sync $_source_path to $_dest_path has pid $_sync_process_pid"

            _sync_pids[${#_sync_pids[@]}]=$_sync_process_pid
            if [ "${#_sync_pids[@]}" -eq "$CP_SYNC_TO_STORAGE_THREADS" ]; then
              wait_for_pids "${_sync_pids[*]}"
              _sync_pids=()
            fi
        else
            eval "$_pipe_command"
            if [ $? -ne 0 ]; then
                echo "[WARN] Sync $_source_path to $_dest_path failed"
            fi
        fi
    done <"$_spec_file"

    if [ "${#_sync_pids[@]}" -gt 0 ]; then
        wait_for_pids "${_sync_pids[*]}"
    fi
}

function sync_spec_allows_batch_mode() {
    local _spec_file=$1

    _spec_lines=$( wc -l < "$_spec_file")

    if [ "$_spec_lines" -lt "2" ]; then
        return 1
    fi

    _all_entries_are_files=1
    while read -a _sync_config_entry; do
        _source_path=${_sync_config_entry[0]}
        if [ -d "$_source_path" ]; then
            _all_entries_are_files=0
            break
        fi
    done <"$_spec_file"

    if [ "$_all_entries_are_files" -ne "1" ]; then
        return 1
    fi

    _spec_lines_with_default_bucket=$(awk '{ print $2 }' < "$_spec_file" | grep -c "^$")

    _sync_common_bucket_path=$(awk '{ print $2 }' < "$_spec_file" | grep -oP -m 1 "^(\w{2}://\w+/)(?=.+)")
    _spec_lines_with_same_bucket=$(awk '{ print $2 }' < "$_spec_file" | grep -c "$_sync_common_bucket_path")

    _all_entries_for_same_bucket=
    if [ -n "$_sync_common_bucket_path" ] && [ "$_spec_lines" -ne "$_spec_lines_with_same_bucket" ]; then
        _all_entries_for_same_bucket="1"
    fi



    if [ "$_spec_lines" -ne "$_spec_lines_with_default_bucket" ] && [ "$_all_entries_for_same_bucket" -ne "1" ]; then
        return 1
    fi

    return 0
}

function perform_batch_sync() {
    local _spec_file=$1

    _sync_common_bucket_path=$(awk '{ print $2 }' < "$_spec_file" | sed -e 'N;s/^\(.*\).*\n\1.*$/\1\n\1/;D')

    if [ -z "$_sync_common_bucket_path" ]; then
        if [ -z "$CP_SYNC_TO_STORAGE_DESTINATION" ]; then
          echo "[WARN] CP_SYNC_TO_STORAGE_DESTINATION is not defined and destination is not provided, and CP_SYNC_TO_STORAGE_DESTINATION also is not defined. Exiting."
          return 1
        fi
        _sync_common_bucket_path="${CP_SYNC_TO_STORAGE_DESTINATION}/${RUN_ID}/"
        echo_debug "Destination bucket wasn't provided in sync configuration, will use default one: $_sync_common_bucket_path"
    fi

    _file_list="${_spec_file}.file_list"
    rm -f "$_file_list"
    while read -a _sync_config_entry; do
        echo_debug "Processing entry ${_sync_config_entry[*]}"

        local _source_path=${_sync_config_entry[0]}
        _source_path_trim=${_source_path#/}
        _source_path_trim=${_source_path_trim%/}

        local _dest_path
        if [ -n "${_sync_config_entry[1]}" ]; then
          _dest_path=${_sync_config_entry[1]#$_sync_common_bucket_path}
        else
          _dest_path="$_source_path_trim"
        fi

        echo_debug "Source path: $_source_path Destination path: $_dest_path"
        printf "%s\t%s\t%s\n" "${_source_path_trim}" "$(stat -c%s "${_source_path}")" "${_dest_path}" >> "${_file_list}"
    done <"$_spec_file"
    echo_debug "Prepare file-list file: ${_file_list} with $(wc -l "$_spec_file") lines"

    local _pipe_extra_args="${CP_SYNC_TO_STORAGE_PIPE_EXTRA_ARGS}"
    if [ "$CP_SYNC_TO_STORAGE_DEBUG" != "true" ]; then
        _pipe_extra_args="$_pipe_extra_args -q"
    fi
    echo_debug "pipe extra args: $_pipe_extra_args"

    local _pipe_command="pipe storage cp -f -r / $_sync_common_bucket_path --file-list ${_file_list} $_pipe_extra_args"
    echo_debug "pipe command: $_pipe_command"
    eval "$_pipe_command"
    if [ $? -ne 0 ]; then
        echo "[WARN] Sync $_source_path to $_dest_path failed"
    fi
    #rm -f "$_file_list"
}

function start_sync_daemon() {
    while [ -z "$CP_SYNC_TO_STORAGE_STOP" ]; do

        if [ -f "$CP_SYNC_TO_STORAGE_STOP_FLAG_FILE" ]; then
            echo "File $CP_SYNC_TO_STORAGE_STOP_FLAG_FILE defined as CP_SYNC_TO_STORAGE_STOP_FLAG_FILES and present. Perform last sync iteration before stop."
            # We need to use such mechanism with additional env var instead of 'while [ -f "$CP_SYNC_TO_STORAGE_STOP_FLAG_FILE" ]'
            # because CP_SYNC_TO_STORAGE_STOP_FLAG_FILE can be created during sleep -> we still need to perform one more sync iteration
            export CP_SYNC_TO_STORAGE_STOP="true"
        fi

        if [ ! -f "$CP_SYNC_TO_STORAGE_SPEC" ]; then
            echo_debug "Spec file not found: $CP_SYNC_TO_STORAGE_SPEC"
            sleep "$CP_SYNC_TO_STORAGE_TIMEOUT_SEC"
            continue
        fi

        cp -f "$CP_SYNC_TO_STORAGE_SPEC" "${CP_SYNC_TO_STORAGE_SPEC}.tmp"
        cp -f "$CP_SYNC_TO_STORAGE_REMOVE_SPEC" "${CP_SYNC_TO_STORAGE_REMOVE_SPEC}.tmp"

        if [ "$CP_SYNC_TO_STORAGE_BATCH_MODE" -eq "0" ] || ! sync_spec_allows_batch_mode "${CP_SYNC_TO_STORAGE_SPEC}.tmp"; then
            perform_sync "${CP_SYNC_TO_STORAGE_SPEC}.tmp"
        else
            perform_batch_sync "${CP_SYNC_TO_STORAGE_SPEC}.tmp"
        fi

        # Check if some file from config marked for deletion
        if [ -f "${CP_SYNC_TO_STORAGE_REMOVE_SPEC}.tmp" ]; then
            echo "Cleaning up $CP_SYNC_TO_STORAGE_SPEC with respect to $CP_SYNC_TO_STORAGE_REMOVE_SPEC"

            touch "${CP_SYNC_TO_STORAGE_SPEC}.new"
            while read -a _sync_config_entry; do
                local _source_path=${_sync_config_entry[0]}
                if grep -q -F "$_source_path" "${CP_SYNC_TO_STORAGE_SPEC}.tmp" && grep -q -x -F "$_source_path" "${CP_SYNC_TO_STORAGE_REMOVE_SPEC}.tmp"; then
                    echo_debug "Path $_source_path is configured for the deletion from sync process"
                    continue
                fi
                echo "${_sync_config_entry[@]}" >> "${CP_SYNC_TO_STORAGE_SPEC}.new"
            done <"$CP_SYNC_TO_STORAGE_SPEC"

            mv -f "${CP_SYNC_TO_STORAGE_SPEC}.new" "${CP_SYNC_TO_STORAGE_SPEC}"
            rm -f "${CP_SYNC_TO_STORAGE_SPEC}.new"

            echo "Previous number of entries to sync is: $(wc -l < "${CP_SYNC_TO_STORAGE_SPEC}.tmp") now: $(wc -l < "$CP_SYNC_TO_STORAGE_SPEC")"
        fi

        rm -f "${CP_SYNC_TO_STORAGE_SPEC}.tmp"
        rm -f "${CP_SYNC_TO_STORAGE_REMOVE_SPEC}.tmp"

        if [ -z "$CP_SYNC_TO_STORAGE_STOP" ]; then
            sleep "$CP_SYNC_TO_STORAGE_TIMEOUT_SEC"
        fi
    done
}

export CP_SYNC_TO_STORAGE_BATCH_MODE="${CP_SYNC_TO_STORAGE_BATCH_MODE:-0}"
export CP_SYNC_TO_STORAGE_SPEC="${CP_SYNC_TO_STORAGE_SPEC:-/etc/sync_to_storage.list}"
export CP_SYNC_TO_STORAGE_REMOVE_SPEC="${CP_SYNC_TO_STORAGE_REMOVE_SPEC:-/etc/sync_to_storage_remove.list}"
export CP_SYNC_TO_STORAGE_PID_FILE="${CP_SYNC_TO_STORAGE_PID_FILE:-/var/run/sync_to_storage.pid}"
export CP_SYNC_TO_STORAGE_STOP_FLAG_FILE="${CP_SYNC_TO_STORAGE_STOP_FLAG_FILE:-/var/run/sync_to_storage.stop}"
export CP_SYNC_TO_STORAGE_TIMEOUT_SEC="${CP_SYNC_TO_STORAGE_TIMEOUT_SEC:-3600}"
export CP_SYNC_TO_STORAGE_THREADS="${CP_SYNC_TO_STORAGE_THREADS:-1}"
export CP_SYNC_TO_STORAGE_LOGFILE="${CP_SYNC_TO_STORAGE_LOGFILE:-/var/log/sync_to_storage.log}"
export CP_SYNC_TO_STORAGE_DEBUG="${CP_SYNC_TO_STORAGE_DEBUG:-false}"

_cmd="$1"

if [ "$_cmd" == "add" ]; then
    if [ -z "$2" ]; then
        echo "[ERROR] Source file for syncing is not specified, nothing will be added to the sync spec"
        exit 1
    fi
    if [ -z "$CP_SYNC_TO_STORAGE_DESTINATION" ] && [ -z "$3" ]; then
        echo "[ERROR] Sync destination location is not defined with CP_SYNC_TO_STORAGE_DESTINATION, can't register sync entry without destination provided"
        exit 1
    fi
    add_to_spec "$2" "$3"
elif [ "$_cmd" == "remove" ]; then
    if [ -z "$2" ]; then
        echo "[ERROR] Source file for syncing is not specified, nothing will be removed from the sync spec"
        exit 1
    fi
    remove_from_spec "$2"
elif [ "$_cmd" == "start" ]; then
    if [ -z "$CP_SYNC_TO_STORAGE_DESTINATION" ]; then
        echo "[WARN] Sync destination location is not defined, only config entries with both source and destination will be processed"
    fi
    CP_SYNC_TO_STORAGE_DESTINATION="${CP_SYNC_TO_STORAGE_DESTINATION%/}"

    if [ -f "$CP_SYNC_TO_STORAGE_PID_FILE" ]; then
        _prev_pid=$(cat $CP_SYNC_TO_STORAGE_PID_FILE)
        echo "[WARN] Another sync process ($_prev_pid) is already running, restarting"
        kill "$_prev_pid"
        rm -f "$CP_SYNC_TO_STORAGE_PID_FILE"
    fi
    export -f start_sync_daemon
    export -f wait_for_pids
    export -f echo_debug
    export -f sync_spec_allows_batch_mode
    export -f perform_sync
    export -f perform_batch_sync
    nohup bash -c start_sync_daemon &> "$CP_SYNC_TO_STORAGE_LOGFILE" &
    echo "$!" > "$CP_SYNC_TO_STORAGE_PID_FILE"
    echo "Sync process has been started, review logs in $CP_SYNC_TO_STORAGE_LOGFILE"
elif [ "$_cmd" == "check" ]; then
  if [ -f "$CP_SYNC_TO_STORAGE_PID_FILE" ]; then
     _prev_pid=$(cat "$CP_SYNC_TO_STORAGE_PID_FILE")
     if  ps -p "$_prev_pid" > /dev/null ; then
        echo "Sync process is running with pid: $_prev_pid"
        exit 0
    fi
  fi
  exit 1
elif [ "$_cmd" == "count" ]; then
  if [ -f "$CP_SYNC_TO_STORAGE_SPEC" ]; then
      _FILES_TO_SYNC_COUNT=$(wc -l < "$CP_SYNC_TO_STORAGE_SPEC")
      if [ "$?" -eq 0 ]; then
          echo "$_FILES_TO_SYNC_COUNT"
          exit 0
      fi
  fi
  exit 1
elif [ "$_cmd" == "stop" ]; then
    echo "Stopping sync_to_storage daemon!"
    if [ -n "$2" ]; then
        _force="$2"
        if [ "$_force" == "force" ]; then
            echo "Force option is provided, sync_to_storage daemon would be stopped immediately!"
            if [ -f "$CP_SYNC_TO_STORAGE_PID_FILE" ]; then
                _pid=$(cat "$CP_SYNC_TO_STORAGE_PID_FILE")
                kill "$_pid"
                rm -f "$CP_SYNC_TO_STORAGE_PID_FILE"
            fi
        fi
    else
        echo "Creating STOP_FLAG file: $CP_SYNC_TO_STORAGE_STOP_FLAG_FILE, sync_to_storage daemon will finish its iteration and will be stopped gracefully!"
        touch "$CP_SYNC_TO_STORAGE_STOP_FLAG_FILE"
    fi
else
    echo "[ERROR] Unknown command $_cmd"
    exit 1
fi