#!/usr/bin/env bash

# Copyright 2017-2020 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_HOME_OWNER="$1"
_HOME_DIR="$2"
_HOME_MOD="755"

if [ -z "$_HOME_OWNER" ]; then
    echo "[ERROR] OWNER is not specified, can't create HOME directory"
    exit 1
fi

if [ -z "$_HOME_DIR" ]; then
    if [ "$_HOME_OWNER" == "root" ]; then
        _HOME_DIR="/root"
    else
        _HOME_DIR="/home/${_HOME_OWNER}"
    fi
    echo "Path to the HOME directory is not specified, $_HOME_DIR will be used"
fi

if [ -d "$_HOME_DIR" ]; then
    echo "HOME directory at $_HOME_DIR already exists"
else
    mkdir "$_HOME_DIR"
    if [ $? -ne 0 ]; then
        echo "[ERROR] Cannot create HOME directory at $_HOME_DIR"
        exit 1
    fi
fi

echo "Setting ownership of $_HOME_DIR to $_HOME_OWNER"
chown "$_HOME_OWNER" "$_HOME_DIR"
if [ $? -ne 0 ]; then
    echo "[WARN] Can't set the ownership, the owner of the $_HOME_OWNER will be \"$(whoami)\""
fi

echo "Setting permissions of $_HOME_DIR to $_HOME_MOD"
chmod "$_HOME_MOD" "$_HOME_DIR"
