#!/bin/bash

# Copyright 2017-2022 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo -e "127.0.0.1 localhost\n127.0.0.1 dc1.cppl.com dc1" > /etc/hosts
echo -e "nameserver 8.8.8.8\nsearch cppl.com" > /etc/resolv.conf
samba-tool domain provision --use-rfc2307 \
 	--realm=CPPL.COM --domain=CPPL \
	--server-role=dc --dns-backend=BIND9_DLZ \
	--adminpass=Test123 --krbtgtpass=Test123 --machinepass=Test123
samba-tool domain passwordsettings set --complexity=off
samba-tool domain passwordsettings set --min-pwd-length=5
samba-tool user create USER1 USER1
samba-tool user create USER2 USER2
samba-tool user create USER3 USER3
samba-tool group addmembers users USER1,USER2,USER3
samba-tool user disable USER1
samba-tool user disable USER3

/usr/sbin/samba -F
