#!/bin/bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function copy_pub_pem {
    local from="$1"
    local to="$2"

    jwt_public_key=$(<$from)
    if [[ "$jwt_public_key" != "-----BEGIN PUBLIC KEY-----"* ]]; then
        echo "JWT Public key ($from) does not start with \"-----BEGIN PUBLIC KEY-----\", adding PEM prefix and suffix"
        echo "-----BEGIN PUBLIC KEY-----" > "$to"
        echo "$jwt_public_key" >> "$to"
        echo "-----END PUBLIC KEY-----" >> "$to"
    else
        \cp "$from" "$to"
    fi
}

# Init required variables and validate
if [ -z "$API" ]; then
    export API="https://${CP_API_SRV_INTERNAL_HOST}:${CP_API_SRV_INTERNAL_PORT}/pipeline/restapi/"
fi

if [ -z "$API_TOKEN" ] && [ "$CP_API_JWT_ADMIN" ]; then
    export API_TOKEN="${CP_API_JWT_ADMIN}"
elif [ -z "$CP_API_JWT_ADMIN" ]; then
    echo "API_TOKEN is empty and cannot be initialized from CP_API_JWT_ADMIN, exiting"
    exit 1
fi

# Check that jwt pub key exists and check it's PEM format (pub key is required to authenticate client's JWT tokens, while accessing SSH or interactive endpoints)
export JWT_PUB_KEY="${JWT_PUB_KEY:-/etc/nginx/jwt-public-key.pem}"
CP_API_SRV_JWT_PUBLIC_KEY="$CP_API_SRV_CERT_DIR/jwt.key.public"
if [ ! -f "$JWT_PUB_KEY" ]; then
    echo "JWT Public key is not found at $JWT_PUB_KEY, trying to find it at other known locations"
    if [ -f "$CP_API_SRV_JWT_PUBLIC_KEY" ]; then
        mkdir -p $(dirname $JWT_PUB_KEY)
        copy_pub_pem $CP_API_SRV_JWT_PUBLIC_KEY $JWT_PUB_KEY
    else
        echo "JWT Public key is not found at $CP_API_SRV_JWT_PUBLIC_KEY as well, exiting"
        exit 1
    fi
fi

# Start wetty.js for SSH proxy
nohup node /etc/ssh-proxy/wetty/app.js -p 32000 >> /var/log/cron.log 2>&1 &

# Persist environment for a cron job
env > /etc/sync-routes/env.sh

# Start cron
crond

# Start nginx
nginx -p /etc/nginx/ -c /etc/nginx/nginx.conf

# Pring wetty and cron logs to the stdout
tail -f /var/log/cron.log