apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cp-search-srv
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: cp-search-srv
      namespace: default
      labels:
        cloud-pipeline/cp-search-srv: "true"
        cloud-pipeline/core-component: "Deployment"
    spec:
      nodeSelector:
        cloud-pipeline/cp-search-srv: "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
        - name: cp-search-srv
          image: $CP_COMMON_DISTR_DOCKER_PREFIX:search-$CP_VERSION
          imagePullPolicy: "Always"
          securityContext:
            privileged: true
          command: ["/init"]
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: cp-config-global
          volumeMounts:
            - mountPath: /opt/search/logs
              name: search-logs
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: search-logs
          hostPath:
            path: /opt/search/logs
      imagePullSecrets:
        - name: cp-distr-docker-registry-secret
