apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-gitlab-db
  namespace: default
spec:
  selector:
    matchLabels:
      cloud-pipeline/cp-gitlab-db: "true"
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        cloud-pipeline/cp-gitlab-db: "true"
    spec:
      nodeSelector:
        cloud-pipeline/cp-gitlab-db: "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
        - name: cp-gitlab-db
          image: postgres:${GITLAB_DATABASE_VERSION}
          imagePullPolicy: "IfNotPresent"
          args:
            - --shared_buffers=${GITLAB_DATABASE_SHARED_BUFFERS}
            - --max_connections=${GITLAB_DATABASE_MAX_CONNECTIONS}
          ports:
            - containerPort: ${PSG_PORT}
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: PGDATA
              value: /var/lib/postgresql/data
            - name: DB_EXTENSION
              value: pg_trgm
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: gitlab-postgresql/data
              name: cp-system
            - mountPath: /dev/shm
              name: gitlab-dshm
          readinessProbe:
            tcpSocket:
              port: ${PSG_PORT}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: ${PSG_PORT}
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 4
      volumes:
        - name: cp-system
          persistentVolumeClaim:
            claimName: cp-system-pvc
        - name: gitlab-dshm
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: cp-distr-docker-registry-secret
