apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cp-oom-reporter
  namespace: default
  labels:
    k8s-app: cp-oom-reporter
spec:
  selector:
    matchLabels:
      name: cp-oom-reporter
  template:
    metadata:
      labels:
        name: cp-oom-reporter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: runid
                    operator: Exists
      containers:
      - name: cp-oom-reporter
        image: ${CP_DOCKER_DIST_SRV}lifescience/cloud-pipeline:oom-reporter-$CP_VERSION
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: oom-reporter
          mountPath: /opt/oom-reporter
        envFrom:
        - configMapRef:
            name: cp-config-global
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: oom-reporter
        hostPath:
          path: /opt/oom-reporter
