#!/bin/bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The following environment variables shall be set
# CP_API_JWT_ADMIN
# CP_API_SRV_INTERNAL_HOST
# CP_API_SRV_INTERNAL_PORT

function download_file {
    local _FILE_URL=$1
    echo "Downloading ${_FILE_URL}"
    wget -q --no-check-certificate ${_FILE_URL} 2>/dev/null || curl -s -k -O ${_FILE_URL}
    _DOWNLOAD_RESULT=$?
    return "$_DOWNLOAD_RESULT"
}


COMMON_REPO_DIR=/opt/PipeCommon
mkdir $COMMON_REPO_DIR && cd $COMMON_REPO_DIR
# Fixed setuptools version to be compatible with the pipe-common package
curl -s https://bootstrap.pypa.io/get-pip.py | python2 && \
    python2 -m pip install -I -q setuptools==44.1.1

download_file "https://$CP_API_SRV_INTERNAL_HOST:$CP_API_SRV_INTERNAL_PORT/pipeline/pipe-common.tar.gz"
_DOWNLOAD_RESULT=$?
if [ "$_DOWNLOAD_RESULT" -ne 0 ];
then
      echo "[ERROR] Main repository download failed. Exiting"
      exit "$_DOWNLOAD_RESULT"
fi

_INSTALL_RESULT=0
tar xf pipe-common.tar.gz
python2 -m pip install . -q -I
_INSTALL_RESULT=$?
if [ "$_INSTALL_RESULT" -ne 0 ];
then
      echo "[ERROR] Main repository install failed. Exiting"
      exit "$_INSTALL_RESULT"
fi
cd /

# Init path for shell scripts from common repository
if [ -d $COMMON_REPO_DIR/shell ]; then
      chmod +x $COMMON_REPO_DIR/shell/*
      ln -s $COMMON_REPO_DIR/shell/* /usr/bin/
fi
chmod +x /opt/monitor-service/monitor_service.sh
/opt/monitor-service/monitor_service.sh --api-url "https://$CP_API_SRV_INTERNAL_HOST:$CP_API_SRV_INTERNAL_PORT/pipeline/restapi/" \
                               --api-token "$CP_API_JWT_ADMIN" \
                               --node-name $NODE_NAME \
                               --sync-file "$SYNC_FILE" \
                               --debug &> /var/log/monitor_service.log