instance_type        = "g6.xlarge"
region               = "us-east-1"
source_ami           = "ami-068c0051b15cdb816"
ssh_username         = "ec2-user"
iam_instance_profile = ""
subnet_id            = ""
deps_file            = "gpu/install-deps.sh"