apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-tes-srv: "true"
  name: cp-tes-srv
  namespace: default
spec:
  ports:
    - protocol: TCP
      nodePort: 32082
      port: 32082
      targetPort: 8080
      name: cp-tes-srv-port-https
  type: NodePort
  selector:
    cloud-pipeline/cp-tes-srv: "true"
