apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-mcp: "true"
  name: cp-mcp
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: cp-mcp-port-http
  selector:
    cloud-pipeline/cp-mcp: "true"
