CREATE SEQUENCE pipeline.S_TOOL START WITH 1 INCREMENT BY 1;
ALTER TABLE PIPELINE.TOOL DROP CONSTRAINT TOOL_pkey;
ALTER TABLE PIPELINE.TOOL ADD ID BIGINT PRIMARY KEY DEFAULT nextval('pipeline.S_TOOL');
ALTER TABLE PIPELINE.TOOL DROP COLUMN REPOSITORY;
ALTER TABLE PIPELINE.TOOL ADD CONSTRAINT tool_registry_id_fk FOREIGN KEY (REGISTRY_ID) REFERENCES DOCKER_REGISTRY (ID);