CREATE TABLE IF NOT EXISTS PIPELINE.INSTANCE_OFFER (
  SKU               TEXT    NOT NULL,
  TERM_TYPE         TEXT,
  UNIT              TEXT,
  PRICE_PER_UNIT    REAL,
  CURRENCY          TEXT,
  INSTANCE_TYPE     TEXT,
  TENANCY           TEXT,
  OPERATING_SYSTEM  TEXT,
  PRICE_LIST_PUBLISH_DATE  TIMESTAMP WITH TIME ZONE NOT NULL
);