CREATE SEQUENCE pipeline.S_PIPELINE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE pipeline.S_PIPELINE_RUN START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS PIPELINE.PIPELINE (
  PIPELINE_ID   BIGINT    NOT NULL PRIMARY KEY,
  PIPELINE_NAME TEXT      NOT NULL,
  DESCRIPTION   TEXT,
  REPOSITORY    TEXT      NOT NULL,
  MAIN_FILE     TEXT      NOT NULL,
  CREATED_DATE  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS PIPELINE.PIPELINE_RUN (
  RUN_ID      BIGINT    NOT NULL PRIMARY KEY,
  PIPELINE_ID BIGINT    NOT NULL,
  VERSION     TEXT      NOT NULL,
  START_DATE  TIMESTAMP WITH TIME ZONE NOT NULL,
  END_DATE    TIMESTAMP WITH TIME ZONE,
  PARAMETERS  TEXT,
  STATUS      BIGINT    NOT NULL,
  TERMINATING BOOLEAN DEFAULT FALSE  NOT NULL,
  POD_ID       TEXT      NOT NULL,
  CONSTRAINT pipeline_run_id_fkey FOREIGN KEY (PIPELINE_ID) REFERENCES pipeline.PIPELINE (PIPELINE_ID)
);

CREATE TABLE IF NOT EXISTS PIPELINE.PIPELINE_RUN_LOG (
  RUN_ID    BIGINT    NOT NULL,
  LOG_DATE  TIMESTAMP WITH TIME ZONE NOT NULL,
  STATUS    BIGINT    NOT NULL,
  LOG_TEXT  TEXT,
  TASK_NAME TEXT,
  INSTANCE  TEXT,
  CONSTRAINT log_run_id_fkey FOREIGN KEY (RUN_ID) REFERENCES pipeline.PIPELINE_RUN (RUN_ID)
);

CREATE TABLE IF NOT EXISTS PIPELINE.TOOL (
  IMAGE      TEXT   NOT NULL PRIMARY KEY,
  CPU        TEXT   NOT NULL,
  RAM        TEXT   NOT NULL,
  TIMEOUT    BIGINT NOT NULL,
  REPOSITORY TEXT   NOT NULL
);
