CREATE TABLE IF NOT EXISTS PIPELINE.DATASTORAGE_RULE
(
    PIPELINE_ID BIGINT  NOT NULL,
    FILE_MASK TEXT  NOT NULL,
    MOVE_TO_STS BOOLEAN DEFAULT FALSE NOT NULL,
    CREATED_DATE  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT datastorage_rule_pipeline_id_file_mask_pk PRIMARY KEY (PIPELINE_ID, FILE_MASK),
    CONSTRAINT datastorage_rule_pipeline_pipeline_id_fk FOREIGN KEY (PIPELINE_ID) REFERENCES pipeline.PIPELINE (PIPELINE_ID)
);
