CREATE TABLE IF NOT EXISTS PIPELINE.NOTIFICATION (
  NOTIFICATION_ID   BIGINT  NOT NULL PRIMARY KEY,
  SEVERITY          BIGINT  NOT NULL,
  TITLE             TEXT    NOT NULL,
  BODY              TEXT,
  STATE             BIGINT  DEFAULT 0   NOT NULL,
  CREATED_DATE      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE SEQUENCE pipeline.S_NOTIFICATION START WITH 1 INCREMENT BY 1;