ALTER TABLE PIPELINE.PIPELINE ADD owner TEXT NULL;
UPDATE PIPELINE.PIPELINE SET owner = 'Unauthorized';
ALTER TABLE pipeline.PIPELINE ALTER COLUMN owner SET NOT NULL;

ALTER TABLE PIPELINE.DATASTORAGE ADD owner TEXT NULL;
UPDATE PIPELINE.DATASTORAGE SET owner = 'Unauthorized';
ALTER TABLE pipeline.DATASTORAGE ALTER COLUMN owner SET NOT NULL;

ALTER TABLE PIPELINE.FOLDER ADD owner TEXT NULL;
UPDATE PIPELINE.FOLDER SET owner = 'Unauthorized';
ALTER TABLE pipeline.FOLDER ALTER COLUMN owner SET NOT NULL;

ALTER TABLE PIPELINE.DOCKER_REGISTRY ADD owner TEXT NULL;
UPDATE PIPELINE.DOCKER_REGISTRY SET owner = 'Unauthorized';
ALTER TABLE pipeline.DOCKER_REGISTRY ALTER COLUMN owner SET NOT NULL;

ALTER TABLE PIPELINE.TOOL ADD owner TEXT NULL;
UPDATE PIPELINE.TOOL SET owner = 'Unauthorized';
ALTER TABLE pipeline.TOOL ALTER COLUMN owner SET NOT NULL;
