CREATE SEQUENCE pipeline.S_DATASTORAGE START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS PIPELINE.DATASTORAGE (
  DATASTORAGE_ID    BIGINT    NOT NULL PRIMARY KEY,
  DATASTORAGE_NAME  TEXT      NOT NULL,
  DESCRIPTION       TEXT,
  DATASTORAGE_TYPE  TEXT      NOT NULL,
  PATH              TEXT      NOT NULL,
  CREATED_DATE      TIMESTAMP WITH TIME ZONE NOT NULL
);