CREATE SEQUENCE pipeline.S_NOTIFICATION_TEMPLATES START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS PIPELINE.NOTIFICATION_TEMPLATE (
  ID   BIGINT    NOT NULL PRIMARY KEY,
  SUBJECT TEXT,
  BODY   TEXT NOT NULL,
  NOTIFICATION_TYPE    TEXT      NOT NULL
);

CREATE SEQUENCE pipeline.S_PIPELINE_NOTIFICATION_QUEUE START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS PIPELINE.NOTIFICATION_QUEUE (
  ID   BIGINT    NOT NULL PRIMARY KEY,
  USER_IDS BIGINT[]      NOT NULL,
  TEMPLATE_ID   BIGINT NOT NULL,
  TEMPLATE_PARAMETERS  TEXT,
  CONSTRAINT template_id_fkey FOREIGN KEY (TEMPLATE_ID) REFERENCES pipeline.NOTIFICATION_TEMPLATE (ID)
);
