CREATE TABLE IF NOT EXISTS PIPELINE.RUN_USER (
    RUN_ID  BIGINT  NOT	NULL,
    NAME    TEXT    NOT NULL,
    IS_PRINCIPAL    BOOLEAN NOT NULL,
    CONSTRAINT  run_id_fkey  FOREIGN KEY (RUN_ID) REFERENCES PIPELINE.PIPELINE_RUN (RUN_ID)
);