CREATE SEQUENCE pipeline.S_CONFIGURATION START WITH 1 INCREMENT BY 1;

CREATE TABLE pipeline.configuration
(
  ID BIGINT PRIMARY KEY NOT NULL,
  NAME TEXT NOT NULL,
  DESCRIPTION TEXT,
  CREATED_DATE  TIMESTAMP WITH TIME ZONE NOT NULL,
  ENTRIES TEXT NOT NULL,
  OWNER TEXT NOT NULL,
  FOLDER_ID BIGINT,
  CONSTRAINT configuration_folder_folder_id_fk FOREIGN KEY (FOLDER_ID) REFERENCES folder (FOLDER_ID)
);

