CREATE SEQUENCE PIPELINE.S_DTS_REGISTRY START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS PIPELINE.DTS_REGISTRY (
  ID   BIGINT    NOT NULL PRIMARY KEY,
  URL TEXT  NOT NULL,
  PREFIXES TEXT[] NOT NULL
);
CREATE INDEX DTS_REGISTRY_INDEX ON PIPELINE.DTS_REGISTRY (ID, URL);