ALTER TABLE PIPELINE.DOCKER_REGISTRY ADD IF NOT EXISTS CA_CERT TEXT NULL;
ALTER TABLE PIPELINE.DOCKER_REGISTRY ADD IF NOT EXISTS SECRET_NAME TEXT NULL;
ALTER TABLE PIPELINE.DOCKER_REGISTRY ADD IF NOT EXISTS USER_NAME TEXT NULL;
ALTER TABLE PIPELINE.DOCKER_REGISTRY ADD IF NOT EXISTS PASSWORD TEXT NULL;
