CREATE SEQUENCE pipeline.S_CLUSTER_NODE_SCALE START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS PIPELINE.CLUSTER_NODE_SCALE (
    ID BIGINT  NOT NULL PRIMARY KEY,
    INSTANCE_TYPE TEXT  NOT NULL,
    NODE_DISK  BIGINT  NOT NULL,
    IS_SPOT BOOLEAN  NOT NULL DEFAULT FALSE,
    CLOUD_REGION_ID  BIGINT NOT NULL,
    NUMBER_OF_INSTANCES BIGINT NOT NULL
);
