apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cp-redis
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        cloud-pipeline/cp-redis: "true"
        cloud-pipeline/core-component: "Deployment"
    spec:
      nodeSelector:
        cloud-pipeline/cp-redis: "true"
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: cp-redis
          image: redis:6.0.5
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: cp-config-global
