apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-redis: "true"
  name: cp-redis
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: ${CP_REDIS_INTERNAL_PORT}
      targetPort: 6379
      name: cp-redis-port-http
  selector:
    cloud-pipeline/cp-redis: "true"
