plugins {
    id 'java'
    id 'jacoco'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.springframework.boot' version '3.5.3'
    id 'org.sonarqube' version '2.6.1'
}

group "com.epam.pipeline"

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

bootJar {
    archiveFileName = "billing-report-agent.jar"
    manifest {
        attributes(
                "Implementation-Version": version)
    }
}

repositories {
    gradlePluginPortal()
    mavenCentral()
}

dependencies {

    // Core library
    implementation project(":cloud-pipeline-common:model")

    configurations {
        all*.exclude module : 'spring-boot-starter-logging'
        all*.exclude group: 'commons-logging', module: 'commons-logging'
    }

    //SpringBoot
    implementation group: "org.springframework.boot", name: "spring-boot-starter", version: springBootVersion
    implementation group: "org.springframework.boot", name: "spring-boot-starter-web", version: springBootVersion
    implementation group: "org.springframework.boot", name: "spring-boot-starter-log4j2", version: springBootVersion

    // Elasticsearch
    implementation group: "org.elasticsearch.client", name: "elasticsearch-rest-client", version: elasticsearchVersion
    implementation group: "org.elasticsearch.client", name: "elasticsearch-rest-high-level-client", version: elasticsearchVersion
    implementation group: "org.elasticsearch", name: "elasticsearch", version: elasticsearchVersion

    // Apache Commons
    implementation group: "commons-io", name: "commons-io", version: apacheCommonsIOVersion
    implementation group: "org.apache.commons", name: "commons-lang3", version: apacheCommonsLangVersion
    implementation group: "org.apache.commons", name: "commons-collections4", version: apacheCommonsCollectionsVersion

    // Azure
    implementation group: 'com.microsoft.azure', name: 'azure-client-authentication', version: azureAuthVersion

    // AWS
    implementation group: 'com.amazonaws', name: 'aws-java-sdk-pricing', version: awsSdkVersion

    // GCP
    implementation group:'com.google.apis', name:'google-api-services-cloudbilling', version: gcpBillingSdkVersion

    //Lombok
    implementation group: "org.projectlombok", name: "lombok", version: lombokVersion
    annotationProcessor group: "org.projectlombok", name: "lombok", version: lombokVersion

    // Retrofit
    implementation group: "com.squareup.retrofit2", name: "retrofit", version: retrofitVersion
    implementation group: "com.squareup.retrofit2", name: "converter-jackson", version: retrofitVersion
    implementation group: "com.squareup.okhttp3", name: "okhttp", version: okhttpVersion

    // Jackson
    implementation group: "com.fasterxml.jackson.core", name: "jackson-databind", version: jaksonVersion

    // Swagger
    implementation group: "io.springfox", name: "springfox-swagger2", version: swaggerVersion
    implementation group: "io.springfox", name: "springfox-swagger-ui", version: swaggerVersion

    //Tests
    implementation group: "org.springframework.boot", name: "spring-boot-starter-test", version: springBootVersion
    testImplementation group: "org.projectlombok", name: "lombok", version: lombokVersion
    testAnnotationProcessor group: "org.projectlombok", name: "lombok", version: lombokVersion
    testImplementation group: "org.elasticsearch.client", name: "transport", version: elasticsearchVersion
    testImplementation group: "org.hamcrest", name: "hamcrest-all", version: hamcrestVersion
}

test {
    useJUnitPlatform()
    reports.html.required = true
}
