plugins {
    id 'java'
    id 'jacoco'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.springframework.boot' version '3.5.3'
    id 'org.sonarqube' version '2.6.1'
}

group "com.epam.pipeline"

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

bootJar {
    archiveFileName = 'billing-report-agent.jar'
    manifest { attributes 'Implementation-Version': version }
}

jar {
    enabled = false
}

repositories {
    gradlePluginPortal()
    mavenCentral()
}

dependencies {

    // Core library
    implementation project(":cloud-pipeline-common:model")

    configurations {
        all*.exclude module : 'spring-boot-starter-logging'
        all*.exclude group: 'commons-logging', module: 'commons-logging'
    }

    // SpringBoot
    implementation "org.springframework.boot:spring-boot-starter:$springBootVersion"
    implementation "org.springframework.boot:spring-boot-starter-web:$springBootVersion"
    implementation "org.springframework.boot:spring-boot-starter-log4j2:$springBootVersion"

    // Elasticsearch
    implementation "org.elasticsearch.client:elasticsearch-rest-client:$elasticsearchVersion"
    implementation "org.elasticsearch.client:elasticsearch-rest-high-level-client:$elasticsearchVersion"
    implementation "org.elasticsearch:elasticsearch:$elasticsearchVersion"

    implementation project(path: ":elasticsearch-common", configuration: "shadow")

    // Apache Commons
    implementation "commons-io:commons-io:$apacheCommonsIOVersion"
    implementation "org.apache.commons:commons-lang3:$apacheCommonsLangVersion"
    implementation "org.apache.commons:commons-collections4:$apacheCommonsCollectionsVersion"

    // Azure
    implementation "com.microsoft.azure:azure-client-authentication:$azureAuthVersion"

    // AWS
    implementation "com.amazonaws:aws-java-sdk-pricing:$awsSdkVersion"

    // GCP
    implementation "com.google.apis:google-api-services-cloudbilling:$gcpBillingSdkVersion"

    // Lombok
    implementation "org.projectlombok:lombok:$lombokVersion"
    annotationProcessor "org.projectlombok:lombok:$lombokVersion"

    // Retrofit
    implementation "com.squareup.retrofit2:retrofit:$retrofitVersion"
    implementation "com.squareup.retrofit2:converter-jackson:$retrofitVersion"
    implementation "com.squareup.okhttp3:okhttp:$okhttpVersion"

    // Jackson
    implementation "com.fasterxml.jackson.core:jackson-databind:$jaksonVersion"

    // Swagger
    implementation "io.springfox:springfox-swagger2:$swaggerVersion"
    implementation "io.springfox:springfox-swagger-ui:$swaggerVersion"

    //Tests
    testImplementation "org.springframework.boot:spring-boot-starter-test:$springBootVersion"
    testImplementation "org.projectlombok:lombok:$lombokVersion"
    testAnnotationProcessor "org.projectlombok:lombok:$lombokVersion"
    testImplementation "org.elasticsearch.client:transport:$elasticsearchVersion"
    testImplementation "org.hamcrest:hamcrest-all:$hamcrestVersion"
}

test {
    useJUnitPlatform()
    reports.html.required = true
}