/*
 * Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id 'java'
    id 'jacoco'
    id 'org.springframework.boot' version '3.5.3'
    id 'org.sonarqube' version '2.6.1'
}

group "com.epam.pipeline"

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
    withSourcesJar() // Modern way to create sources jar
}

bootJar {
    archiveFileName = "vm-monitor.jar"
    manifest {
        attributes(
                "Implementation-Version": version)
    }
}

jar {
    enabled = false
}

repositories {
    gradlePluginPortal()
    mavenCentral()
}

dependencies {

    // Core library
    implementation project(":cloud-pipeline-common:model")

    configurations {
        all*.exclude module : 'spring-boot-starter-logging'
        all*.exclude group: 'commons-logging', module: 'commons-logging'
    }

    //SpringBoot
    implementation group: "org.springframework.boot", name: "spring-boot-starter", version: springBootVersion
    implementation group: "org.springframework.boot", name: "spring-boot-starter-data-jpa", version: springBootVersion
    implementation group: "org.springframework.boot", name: "spring-boot-starter-log4j2", version: springBootVersion

    //Lombok
    implementation group: "org.projectlombok", name: "lombok", version: lombokVersion
    annotationProcessor group: "org.projectlombok", name: "lombok", version: lombokVersion

    // Retrofit
    implementation group: "com.squareup.retrofit2", name: "retrofit", version: retrofitVersion
    implementation group: "com.squareup.retrofit2", name: "converter-jackson", version: retrofitVersion
    implementation group: "com.squareup.retrofit2", name: "converter-scalars", version: retrofitVersion
    implementation group: "com.squareup.okhttp3", name: "okhttp", version: okhttpVersion

    // Jackson
    implementation group: "com.fasterxml.jackson.core", name: "jackson-databind", version: jaksonVersion

    //Email notifications
    implementation group: 'org.apache.commons', name: 'commons-email', version: '1.5'
    implementation group: 'org.apache.commons', name: "commons-collections4", version: "4.0"
    implementation 'commons-io:commons-io:2.4'
    implementation group: 'org.apache.velocity', name: 'velocity', version: '1.7'
    implementation group: 'org.apache.velocity', name: 'velocity-tools', version: '2.0'

    //AWS
    implementation group: "com.amazonaws", name: "aws-java-sdk-ec2", version: "1.11.704"

    //Azure
    implementation group: "com.microsoft.azure", name: "azure-mgmt-resources", version: "1.19.0"
    implementation group: "com.microsoft.azure", name: "azure", version: "1.19.0"

    //GCP
    implementation group: "com.google.apis", name: "google-api-services-compute", version: "v1-rev214-1.25.0"

    //K8s
    implementation group: "io.fabric8", name: "kubernetes-client", version: k8sLibraryVersion

    //Tests
    implementation group: "org.springframework.boot", name: "spring-boot-starter-test", version: springBootVersion
    testImplementation group: "org.projectlombok", name: "lombok", version: lombokVersion
    testAnnotationProcessor group: "org.projectlombok", name: "lombok", version: lombokVersion
}

test {
    useJUnitPlatform()
    reports.html.required = true
}
