apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-api-srv: "true"
  name: cp-api-srv
  namespace: cloud-pipeline-test
spec:
  ports:
    - name: cp-api-srv-port-https
      port: 31080
      protocol: TCP
      targetPort: 8080
    - name: cp-api-srv-port-https-443
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    cloud-pipeline/cp-api-srv: "true"
