/*
 * Copyright 2017-2026 EPAM Systems, Inc. (https://www.epam.com/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

import React from 'react';
import {
  AppstoreFilled,
  AppstoreOutlined,
  AreaChartOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  ArrowsAltOutlined,
  BarsOutlined,
  BookOutlined,
  CalendarOutlined,
  CameraFilled,
  CaretDownOutlined,
  CaretLeftOutlined,
  CaretRightOutlined,
  CaretUpOutlined,
  CheckOutlined,
  CheckCircleFilled,
  ClockCircleOutlined,
  CloseOutlined,
  CloseCircleOutlined,
  CloudDownloadOutlined,
  CloudOutlined,
  CodeOutlined,
  CompassOutlined,
  CopyOutlined,
  CustomerServiceOutlined,
  DatabaseOutlined,
  DeleteOutlined,
  DownOutlined,
  DownloadOutlined,
  EditOutlined,
  EllipsisOutlined,
  ExceptionOutlined,
  ExclamationCircleFilled,
  ExclamationCircleOutlined,
  ExportOutlined,
  EyeFilled,
  FileOutlined,
  FileTextOutlined,
  FilterOutlined,
  FolderOutlined,
  FolderOpenOutlined,
  ForkOutlined,
  ForwardOutlined,
  HddOutlined,
  HomeOutlined,
  InboxOutlined,
  InfoCircleFilled,
  InfoCircleOutlined,
  LayoutOutlined,
  LeftOutlined,
  LinkOutlined,
  LoadingOutlined,
  LockOutlined,
  MailOutlined,
  MessageOutlined,
  MinusCircleOutlined,
  NotificationOutlined,
  PaperClipOutlined,
  PauseCircleOutlined,
  PictureOutlined,
  PlayCircleFilled,
  PlayCircleOutlined,
  PlusOutlined,
  PlusCircleOutlined,
  PlusSquareOutlined,
  PoweroffOutlined,
  QuestionOutlined,
  QuestionCircleFilled,
  QuestionCircleOutlined,
  ReloadOutlined,
  RightOutlined,
  RollbackOutlined,
  SaveOutlined,
  ScanOutlined,
  SearchOutlined,
  SettingOutlined,
  ShareAltOutlined,
  ShrinkOutlined,
  SolutionOutlined,
  StarFilled,
  StarOutlined,
  SwapOutlined,
  SwitcherOutlined,
  SyncOutlined,
  TagFilled,
  TagOutlined,
  TeamOutlined,
  ToolOutlined,
  UnlockOutlined,
  UpOutlined,
  UploadOutlined,
  UserOutlined,
  UserAddOutlined,
  UserDeleteOutlined,
  UsergroupAddOutlined,
  WarningOutlined,
} from '@ant-design/icons';

const iconMapping = {
  appstore: AppstoreFilled,
  'appstore-o': AppstoreOutlined,
  'area-chart': AreaChartOutlined,
  'arrow-left': ArrowLeftOutlined,
  'arrow-right': ArrowRightOutlined,
  'arrows-alt': ArrowsAltOutlined,
  bars: BarsOutlined,
  book: BookOutlined,
  calendar: CalendarOutlined,
  camera: CameraFilled,
  'caret-down': CaretDownOutlined,
  'caret-left': CaretLeftOutlined,
  'caret-right': CaretRightOutlined,
  'caret-up': CaretUpOutlined,
  check: CheckOutlined,
  'check-circle': CheckCircleFilled,
  'clock-circle-o': ClockCircleOutlined,
  close: CloseOutlined,
  'close-circle-o': CloseCircleOutlined,
  'cloud-download-o': CloudDownloadOutlined,
  'cloud-o': CloudOutlined,
  'code-o': CodeOutlined,
  compass: CompassOutlined,
  copy: CopyOutlined,
  'customer-service': CustomerServiceOutlined,
  database: DatabaseOutlined,
  delete: DeleteOutlined,
  down: DownOutlined,
  download: DownloadOutlined,
  edit: EditOutlined,
  ellipsis: EllipsisOutlined,
  exception: ExceptionOutlined,
  'exclamation-circle': ExclamationCircleFilled,
  'exclamation-circle-o': ExclamationCircleOutlined,
  export: ExportOutlined,
  eye: EyeFilled,
  file: FileOutlined,
  'file-text': FileTextOutlined,
  filter: FilterOutlined,
  folder: FolderOutlined,
  'folder-open': FolderOpenOutlined,
  fork: ForkOutlined,
  forward: ForwardOutlined,
  hdd: HddOutlined,
  home: HomeOutlined,
  inbox: InboxOutlined,
  'info-circle': InfoCircleFilled,
  'info-circle-o': InfoCircleOutlined,
  layout: LayoutOutlined,
  left: LeftOutlined,
  link: LinkOutlined,
  loading: LoadingOutlined,
  lock: LockOutlined,
  mail: MailOutlined,
  message: MessageOutlined,
  'minus-circle-o': MinusCircleOutlined,
  notification: NotificationOutlined,
  'paper-clip': PaperClipOutlined,
  'pause-circle-o': PauseCircleOutlined,
  picture: PictureOutlined,
  'play-circle': PlayCircleFilled,
  'play-circle-o': PlayCircleOutlined,
  plus: PlusOutlined,
  'plus-circle-o': PlusCircleOutlined,
  'plus-square-o': PlusSquareOutlined,
  poweroff: PoweroffOutlined,
  question: QuestionOutlined,
  'question-circle': QuestionCircleFilled,
  'question-circle-o': QuestionCircleOutlined,
  reload: ReloadOutlined,
  right: RightOutlined,
  rollback: RollbackOutlined,
  save: SaveOutlined,
  scan: ScanOutlined,
  search: SearchOutlined,
  setting: SettingOutlined,
  'share-alt': ShareAltOutlined,
  shrink: ShrinkOutlined,
  solution: SolutionOutlined,
  star: StarFilled,
  'star-o': StarOutlined,
  swap: SwapOutlined,
  switcher: SwitcherOutlined,
  sync: SyncOutlined,
  tag: TagFilled,
  'tag-o': TagOutlined,
  team: TeamOutlined,
  tool: ToolOutlined,
  unlock: UnlockOutlined,
  up: UpOutlined,
  upload: UploadOutlined,
  user: UserOutlined,
  'user-add': UserAddOutlined,
  'user-delete': UserDeleteOutlined,
  'usergroup-add': UsergroupAddOutlined,
  warning: WarningOutlined,
};

/**
 * Component for mapping old antd 2x icon names to modern antd icons.
 * @param {string|React.ComponentType} type - The old antd2x icon type or icon component
 * @param {object} restProps - Additional props to pass to the icon component
 * @returns {JSX.Element|null} The corresponding modern antd icon component or null
 */
export default function OldAntIconsResolver({type, ...restProps}) {
  if (typeof type === 'function' || React.isValidElement(type)) {
    const IconComponent = typeof type === 'function' ? type : () => type;
    return <IconComponent {...restProps} />;
  }
  const IconComponent = iconMapping[type];
  if (!IconComponent) {
    console.warn(`Icon "${type}" not found in OldAntIconsResolver mapping`);
    return null;
  }
  return <IconComponent {...restProps} />;
}
