const API_BASE = Cypress.env('API_BASE');

export const stubRunFilter = () => {
  cy.intercept('POST', `${API_BASE}/run/filter`, {
    statusCode: 200,
    body: {
      payload: {
        elements: [
          {
            id: 72651,
            createdDate: '2025-03-28 11:09:14.078',
            mask: 15,
            tags: 'blabla',
            owner: 'PIPE_ADMIN',
            locked: false,
            originalOwner: 'PIPE_ADMIN',
            startDate: '2025-03-27 11:15:18.780',
            instanceStartDate: '2025-03-27 11:19:25.895',
            endDate: '2025-03-27 11:16:54.443',
            status: 'STOPPED',
            commitStatus: 'NOT_COMMITTED',
            lastChangeCommitTime: '2025-03-27 11:15:18.780',
            params:
              'CP_CAP_SGE=true=boolean|CP_CAP_AUTOSCALE=true=boolean|CP_CAP_LIMIT_MOUNTS=None=string|CP_CAP_AUTOSCALE_WORKERS=5=int|CP_CAP_AUTOSCALE_INSTANCE_TYPE=p3.2xlarge=string|CP_CAP_NFS=true=string',
            dockerImage: 'docker.aws.cloud-pipeline.com:443/library/alphafold:latest',
            actualDockerImage: 'docker.aws.cloud-pipeline.com:443/library/alphafold:latest',
            platform: 'linux',
            cmdTemplate: 'sleep infinity',
            actualCmd: 'sleep infinity',
            terminating: false,
            sensitive: false,
            podId: 'pipeline-72651',
            pipelineRunParameters: [
              {
                name: 'CP_CAP_SGE',
                value: 'true',
                type: 'boolean',
              },
              {
                name: 'CP_CAP_AUTOSCALE',
                value: 'true',
                type: 'boolean',
              },
              {
                name: 'CP_CAP_LIMIT_MOUNTS',
                value: 'None',
                type: 'string',
              },
              {
                name: 'CP_CAP_AUTOSCALE_WORKERS',
                value: '5',
                type: 'int',
              },
              {
                name: 'CP_CAP_AUTOSCALE_INSTANCE_TYPE',
                value: 'p3.2xlarge',
                type: 'string',
              },
              {
                name: 'CP_CAP_NFS',
                value: 'true',
                type: 'string',
              },
            ],
            instance: {
              nodeType: 'm5.xlarge',
              nodeDisk: 100,
              effectiveNodeDisk: 105,
              nodeIP: '172.31.23.130',
              nodeId: 'i-0da56b4c8901cdca7',
              nodeName: 'i-0da56b4c8901cdca7',
              nodePlatform: 'linux',
              spot: false,
              cloudRegionId: 1,
              cloudProvider: 'AWS',
              poolId: 0,
            },
            timeout: 0,
            configName: 'default',
            nodeCount: 0,
            childRunsCount: 0,
            activeChildRunsCount: 0,
            initialized: false,
            configurationId: 0,
            prolongedAtTime: '2025-03-27 11:15:18.780',
            executionPreferences: {
              environment: 'CLOUD_PLATFORM',
            },
            pricePerHour: 0.25,
            computePricePerHour: 0.23,
            diskPricePerHour: 0.00013,
            runStatuses: [
              {
                runId: 72651,
                status: 'RUNNING',
                timestamp: '2025-03-27 11:15:20.863',
              },
              {
                runId: 72651,
                status: 'STOPPED',
                timestamp: '2025-03-27 11:16:39.462',
              },
            ],
            nonPause: false,
            aclClass: 'PIPELINE',
            kubeServiceEnabled: false,
            masterRun: true,
            workerRun: false,
            taskName: 'pipeline-72651',
            clusterRun: true,
          },
          {
            id: 69558,
            createdDate: '2025-03-28 11:09:14.078',
            mask: 15,
            owner: 'AZ_USER1',
            locked: false,
            originalOwner: 'AZ_USER1',
            pipelineId: 23729,
            startDate: '2025-01-21 10:53:31.332',
            version: 'draft-5968baf6',
            endDate: '2025-01-21 10:53:47.497',
            status: 'STOPPED',
            commitStatus: 'NOT_COMMITTED',
            lastChangeCommitTime: '2025-01-21 10:53:31.332',
            params:
              'AF_DEFAULT_OUTPUT_PATH=s3://epm-az-demo-alphafold/Structures=output|AF_DB_PATH=/opt/alphafold/db/20240322=string|TEST=s3://cloud-pipeline-aws-scratch-bucket/upload/AZ_USER1/2025-01-21/resources(1).20250121105318048.csv=input|CP_CAP_LIMIT_MOUNTS=None=string|CP_CAP_FORCE_MOUNTS=31473=string|CP_CAP_AUTOSCALE=false=boolean|CP_CAP_AUTOSCALE_HYBRID=false=boolean|CP_CAP_SGE=false=boolean|CP_CAP_SPARK=false=boolean|CP_CAP_SLURM=false=boolean|CP_CAP_KUBE=false=boolean|CP_CAP_SHARE_FS_TYPE=lfs=string',
            dockerImage: 'docker.aws.cloud-pipeline.com:443/library/alphafold:latest',
            actualDockerImage: 'docker.aws.cloud-pipeline.com:443/library/alphafold:latest',
            platform: 'linux',
            cmdTemplate: 'bash $SCRIPTS_DIR/src/[main_file]',
            actualCmd: 'bash $SCRIPTS_DIR/src/runalphafold.sh',
            terminating: false,
            sensitive: false,
            podId: 'run-alphafold-69558',
            pipelineName: 'RUN-Alphafold',
            pipelineRunParameters: [
              {
                name: 'AF_DEFAULT_OUTPUT_PATH',
                value: 's3://epm-az-demo-alphafold/Structures',
                type: 'output',
              },
              {
                name: 'AF_DB_PATH',
                value: '/opt/alphafold/db/20240322',
                type: 'string',
              },
              {
                name: 'TEST',
                value:
                  's3://cloud-pipeline-aws-scratch-bucket/upload/AZ_USER1/2025-01-21/resources(1).20250121105318048.csv',
                type: 'input',
              },
              {
                name: 'CP_CAP_LIMIT_MOUNTS',
                value: 'None',
                type: 'string',
              },
              {
                name: 'CP_CAP_FORCE_MOUNTS',
                value: '31473',
                type: 'string',
              },
              {
                name: 'CP_CAP_AUTOSCALE',
                value: 'false',
                type: 'boolean',
              },
              {
                name: 'CP_CAP_AUTOSCALE_HYBRID',
                value: 'false',
                type: 'boolean',
              },
              {
                name: 'CP_CAP_SGE',
                value: 'false',
                type: 'boolean',
              },
              {
                name: 'CP_CAP_SPARK',
                value: 'false',
                type: 'boolean',
              },
              {
                name: 'CP_CAP_SLURM',
                value: 'false',
                type: 'boolean',
              },
              {
                name: 'CP_CAP_KUBE',
                value: 'false',
                type: 'boolean',
              },
              {
                name: 'CP_CAP_SHARE_FS_TYPE',
                value: 'lfs',
                type: 'string',
              },
            ],
            instance: {
              nodeType: 'm5.8xlarge',
              nodeDisk: 200,
              effectiveNodeDisk: 205,
              nodePlatform: 'linux',
              spot: false,
              cloudRegionId: 1,
              cloudProvider: 'AWS',
              poolId: 0,
            },
            timeout: 0,
            configName: 'default',
            nodeCount: 0,
            childRunsCount: 0,
            activeChildRunsCount: 0,
            initialized: false,
            queued: true,
            configurationId: 0,
            prolongedAtTime: '2025-01-21 10:53:31.332',
            executionPreferences: {
              environment: 'CLOUD_PLATFORM',
            },
            pricePerHour: 1.87,
            computePricePerHour: 1.84,
            fsPricePerHour: 0,
            diskPricePerHour: 0.00013,
            runStatuses: [
              {
                runId: 69558,
                status: 'RUNNING',
                timestamp: '2025-01-21 10:53:31.659',
              },
              {
                runId: 69558,
                status: 'STOPPED',
                timestamp: '2025-01-21 10:53:43.567',
              },
            ],
            nonPause: false,
            aclClass: 'PIPELINE',
            kubeServiceEnabled: false,
            masterRun: false,
            workerRun: false,
            taskName: 'RUN-Alphafold',
            clusterRun: false,
          },
          {
            id: 65733,
            createdDate: '2025-03-28 11:09:14.079',
            mask: 15,
            owner: 'PIPE_ADMIN',
            locked: false,
            originalOwner: 'PIPE_ADMIN',
            pipelineId: 26342,
            startDate: '2024-10-30 15:30:23.807',
            instanceStartDate: '2024-10-30 15:34:17.082',
            version: 'draft-e225a10f',
            endDate: '2024-10-30 15:40:14.764',
            status: 'SUCCESS',
            commitStatus: 'NOT_COMMITTED',
            lastChangeCommitTime: '2024-10-30 15:30:23.807',
            params:
              'Sequences=10008:Sequences:8282,8283,8284=metadata|AF_DEFAULT_OUTPUT_PATH=s3://rnd-structure-data/Structures=output|AF_DB_PATH=/opt/alphafold/db/20240322=string|CP_CAP_LIMIT_MOUNTS=None=string|CP_CAP_FORCE_MOUNTS=31473=string|CP_CAP_AUTOSCALE=false=boolean|CP_CAP_AUTOSCALE_HYBRID=false=boolean|CP_CAP_SGE=false=boolean|CP_CAP_SPARK=false=boolean|CP_CAP_SLURM=false=boolean|CP_CAP_KUBE=false=boolean',
            dockerImage: 'docker.aws.cloud-pipeline.com:443/library/alphafold:latest',
            actualDockerImage: 'docker.aws.cloud-pipeline.com:443/library/alphafold:latest',
            platform: 'linux',
            cmdTemplate: 'bash $SCRIPTS_DIR/src/[main_file]',
            actualCmd: 'bash $SCRIPTS_DIR/src/runalphafold.sh',
            terminating: false,
            sensitive: false,
            podId: 'alphafold-rnd-65733',
            pipelineName: 'Alphafold-RnD',
            pipelineRunParameters: [
              {
                name: 'Sequences',
                value: '10008:Sequences:8282,8283,8284',
                type: 'metadata',
              },
              {
                name: 'AF_DEFAULT_OUTPUT_PATH',
                value: 's3://rnd-structure-data/Structures',
                type: 'output',
              },
              {
                name: 'AF_DB_PATH',
                value: '/opt/alphafold/db/20240322',
                type: 'string',
              },
              {
                name: 'CP_CAP_LIMIT_MOUNTS',
                value: 'None',
                type: 'string',
              },
              {
                name: 'CP_CAP_FORCE_MOUNTS',
                value: '31473',
                type: 'string',
              },
              {
                name: 'CP_CAP_AUTOSCALE',
                value: 'false',
                type: 'boolean',
              },
              {
                name: 'CP_CAP_AUTOSCALE_HYBRID',
                value: 'false',
                type: 'boolean',
              },
              {
                name: 'CP_CAP_SGE',
                value: 'false',
                type: 'boolean',
              },
              {
                name: 'CP_CAP_SPARK',
                value: 'false',
                type: 'boolean',
              },
              {
                name: 'CP_CAP_SLURM',
                value: 'false',
                type: 'boolean',
              },
              {
                name: 'CP_CAP_KUBE',
                value: 'false',
                type: 'boolean',
              },
            ],
            instance: {
              nodeType: 'm5.8xlarge',
              nodeDisk: 200,
              effectiveNodeDisk: 205,
              nodeIP: '172.31.18.168',
              nodeId: 'i-0e9e38f063ca2a348',
              nodeName: 'i-0e9e38f063ca2a348',
              nodePlatform: 'linux',
              spot: false,
              cloudRegionId: 1,
              cloudProvider: 'AWS',
              poolId: 0,
            },
            timeout: 0,
            podIP: '10.244.231.196',
            configName: 'default',
            nodeCount: 0,
            childRunsCount: 0,
            activeChildRunsCount: 0,
            initialized: true,
            configurationId: 0,
            prolongedAtTime: '2024-10-30 15:30:23.807',
            executionPreferences: {
              environment: 'CLOUD_PLATFORM',
            },
            pricePerHour: 1.87,
            computePricePerHour: 1.84,
            fsPricePerHour: 0,
            diskPricePerHour: 0.00013,
            runStatuses: [
              {
                runId: 65733,
                status: 'RUNNING',
                timestamp: '2024-10-30 15:30:24.109',
              },
              {
                runId: 65733,
                status: 'SUCCESS',
                timestamp: '2024-10-30 15:40:15.028',
              },
            ],
            nonPause: false,
            aclClass: 'PIPELINE',
            tags: {
              WORK_FINISHED: '2024-10-30 15:40:07.904',
            },
            kubeServiceEnabled: false,
            masterRun: false,
            workerRun: false,
            taskName: 'Alphafold-RnD',
            clusterRun: false,
          },
        ],
        totalCount: 3,
      },
      status: 'OK',
    },
  }).as('getRunFilter');
};
