---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cp-system-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 500Gi
