#!/bin/bash

# Copyright 2017-2020 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The following environment variables shall be set
# CP_API_JWT_ADMIN
# CP_API_SRV_INTERNAL_HOST
# CP_API_SRV_INTERNAL_PORT

export OOM_REPORTER_SYNC_FILE="${OOM_REPORTER_SYNC_FILE:-/opt/oom-reporter/sync_file}"
export OOM_REPORTER_LOG_FILE="${OOM_REPORTER_LOG_FILE:-/opt/oom-reporter/monitor_service.log}"
mkdir -p $(dirname $OOM_REPORTER_LOG_FILE)

/monitor_service.sh --api-url "https://$CP_API_SRV_INTERNAL_HOST:$CP_API_SRV_INTERNAL_PORT/pipeline/restapi/" \
                    --api-token "$CP_API_JWT_ADMIN" \
                    --node-name $NODE_NAME \
                    --sync-file "$SYNC_FILE" \
                    --debug &> $OOM_REPORTER_LOG_FILE
