plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.3'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.sonarqube' version '2.6.1'
}

group 'com.epam.pipeline'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

ext {
    springBootVersion = '3.5.3'
}

configurations {
    all*.exclude module: 'spring-boot-starter-logging'
    all*.exclude group: 'commons-logging', module: 'commons-logging'
}

jar {
    archiveFileName = 'notifier.jar'
}

dependencies {

    implementation 'org.springframework.boot:spring-boot-starter-log4j2'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation project(':core')
    implementation 'org.postgresql:postgresql:42.7.3'
    implementation 'com.zaxxer:HikariCP:3.2.0'
    implementation 'org.apache.commons:commons-collections4:4.0'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.8.7'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.8.7'
    implementation 'org.apache.commons:commons-email:1.5'
    implementation 'org.apache.velocity:velocity:1.7'
    implementation 'org.apache.velocity:velocity-tools:2.0'
    implementation 'org.projectlombok:lombok:1.18.34'

    annotationProcessor 'org.projectlombok:lombok:1.18.34'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'com.h2database:h2:1.4.197'
    testImplementation 'com.icegreen:greenmail:2.1.0'
}