setup.template.name: "security_log_template"
setup.template.pattern: "security_log*"
setup.template.enabled: false
output.elasticsearch:
  hosts: ["http://${CP_SEARCH_ELK_INTERNAL_HOST}:${CP_SEARCH_ELK_ELASTIC_INTERNAL_PORT}"]
  pipeline: "audit_dav"
  index: "security_log"
filebeat:
  inputs:
    - paths:
        - /etc/nginx/logs/webdav.access.log
      fields:
        service: edge
        type: audit
        level: INFO
      include_lines: ['PUT', 'GET', 'MOVE', 'DELETE']
processors:
  - drop_fields:
      fields: ["log", "offset", "beat", "agent", "log.offset", "esc" ]
logging.files:
  name: filebeat-audit-dav
