apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-statping-monitor: "true"
  name: cp-statping-monitor
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: ${CP_STATPING_INTERNAL_PORT}
    targetPort: 8080
    name: cp-statping-monitor-port-http
  selector:
    cloud-pipeline/cp-statping-monitor: "true"
