apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-health: "true"
  name: cp-health
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: cp-health-port-http
  externalIPs:
  - ${CP_STATPING_EXTERNAL_IP}
  selector:
    cloud-pipeline/cp-health: "true"
