---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: amazon/aws-efs-csi-driver
    newName: ${CP_CSI_EFS_CSI_DRIVER_IMAGE_NAME}
    newTag: ${CP_CSI_EFS_CSI_DRIVER_IMAGE_TAG}
  - name: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
    newName: ${CP_CSI_EFS_LIVENESS_PROBE_IMAGE_NAME}
    newTag: ${CP_CSI_EFS_LIVENESS_PROBE_IMAGE_TAG}
  - name: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar
    newName: ${CP_CSI_EFS_NODE_DRIVER_REGISTRAR_IMAGE_NAME}
    newTag: ${CP_CSI_EFS_NODE_DRIVER_REGISTRAR_IMAGE_TAG}
  - name: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
    newName: ${CP_CSI_EFS_EXTERNAL_PROVISIONER_IMAGE_NAME}
    newTag: ${CP_CSI_EFS_EXTERNAL_PROVISIONER_IMAGE_TAG}
resources:
  - "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/base/?ref=release-1.7"
  - ./resources/efs-sc.yaml
  - ./resources/efs-pv.yaml
  - ./resources/efs-pvc.yaml
patches:
  - path: ./patches/deployment.yaml
