#!/bin/bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

TRUST_CERT_PATH="$1"
TRUST_CERT_ALIAS="$2"

if [ -z "$TRUST_CERT_PATH" ]; then
    echo "TRUST_CERT_PATH is not provided, exiting"
    exit 1
fi

if [ -z "$TRUST_CERT_ALIAS" ]; then
    TRUST_CERT_ALIAS="$(basename TRUST_CERT_PATH)"
fi

echo Setting trust to $TRUST_CERT_PATH via update-ca-trust
\cp $TRUST_CERT_PATH /etc/pki/ca-trust/source/anchors/
update-ca-trust extract

echo "Setting trust to $TRUST_CERT_PATH via keytool (/usr/lib/jvm/jre/lib/security/cacerts)"
keytool  -import \
            -trustcacerts \
            -keystore /usr/lib/jvm/jre/lib/security/cacerts \
            -storepass changeit \
            -noprompt \
            -alias $TRUST_CERT_ALIAS \
            -file $TRUST_CERT_PATH
