apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-share-srv: "true"
  name: cp-share-srv
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: ${CP_SHARE_SRV_INTERNAL_PORT}
    targetPort: 8080
    name: cp-share-srv-port-https
  externalIPs:
${CP_SHARE_SRV_SVC_EXTERNAL_IP_LIST}
  selector:
    cloud-pipeline/cp-share-srv: "true"
