export const CP_CAP_SGE = 'CP_CAP_SGE';
export const CP_CAP_SPARK = 'CP_CAP_SPARK';
export const CP_CAP_SLURM = 'CP_CAP_SLURM';
export const CP_CAP_KUBE = 'CP_CAP_KUBE';
export const CP_CAP_AUTOSCALE = 'CP_CAP_AUTOSCALE';
export const CP_CAP_AUTOSCALE_WORKERS = 'CP_CAP_AUTOSCALE_WORKERS';
export const CP_CAP_AUTOSCALE_HYBRID = 'CP_CAP_AUTOSCALE_HYBRID';
export const CP_CAP_AUTOSCALE_PRICE_TYPE = 'CP_CAP_AUTOSCALE_PRICE_TYPE';

export const CP_CAP_DIND_CONTAINER = 'CP_CAP_DIND_CONTAINER';
export const CP_CAP_SYSTEMD_CONTAINER = 'CP_CAP_SYSTEMD_CONTAINER';
export const CP_CAP_SINGULARITY = 'CP_CAP_SINGULARITY';
export const CP_CAP_DESKTOP_NM = 'CP_CAP_DESKTOP_NM';
export const CP_CAP_MODULES = 'CP_CAP_MODULES';
export const CP_DISABLE_HYPER_THREADING = 'CP_DISABLE_HYPER_THREADING';

export const CP_CAP_LIMIT_MOUNTS = 'CP_CAP_LIMIT_MOUNTS';
export const CP_CAP_RUN_CAPABILITIES = 'CP_CAP_RUN_CAPABILITIES';

export const CP_CAP_DCV = 'CP_CAP_DCV';
export const CP_CAP_DCV_DESKTOP = 'CP_CAP_DCV_DESKTOP';
export const CP_CAP_DCV_WEB = 'CP_CAP_DCV_WEB';

export const CP_CAP_RESCHEDULE_RUN = 'CP_CAP_RESCHEDULE_RUN';
export const CP_CAP_AUTOSCALE_HYBRID_FAMILY = 'CP_CAP_AUTOSCALE_HYBRID_FAMILY';
export const CP_CAP_AUTOSCALE_INSTANCE_TYPE = 'CP_CAP_AUTOSCALE_INSTANCE_TYPE';

export const CP_CAP_SHARE_FS_TYPE = 'CP_CAP_SHARE_FS_TYPE';
export const CP_CAP_SHARE_FS_DEPLOYMENT_TYPE = 'CP_CAP_SHARE_FS_DEPLOYMENT_TYPE';
export const CP_CAP_SHARE_FS_SIZE = 'CP_CAP_SHARE_FS_SIZE';
export const CP_CAP_SHARE_FS_THROUGHPUT = 'CP_CAP_SHARE_FS_THROUGHPUT';
export const CP_CAP_SHARE_FS_IOPS = 'CP_CAP_SHARE_FS_IOPS';

export const CP_CAP_REQUESTS_CPU = 'CP_CAP_REQUESTS_CPU';
export const CP_CAP_REQUESTS_GPU = 'CP_CAP_REQUESTS_GPU';
export const CP_CAP_REQUESTS_RAM = 'CP_CAP_REQUESTS_RAM';

export const systemCapabilitiesParameters = [
  CP_CAP_DIND_CONTAINER,
  CP_CAP_SINGULARITY,
  CP_CAP_SYSTEMD_CONTAINER,
  CP_CAP_DESKTOP_NM,
  CP_CAP_MODULES,
  CP_DISABLE_HYPER_THREADING,
  CP_CAP_DCV,
  CP_CAP_DCV_DESKTOP,
  CP_CAP_DCV_WEB,
];

export const reservedParameters = [
  CP_CAP_LIMIT_MOUNTS,
  CP_CAP_SGE,
  CP_CAP_SPARK,
  CP_CAP_SLURM,
  CP_CAP_KUBE,
  CP_CAP_AUTOSCALE,
  CP_CAP_AUTOSCALE_WORKERS,
  CP_CAP_AUTOSCALE_HYBRID,
  CP_CAP_AUTOSCALE_PRICE_TYPE,
  CP_CAP_RESCHEDULE_RUN,

  ...systemCapabilitiesParameters,

  CP_CAP_SHARE_FS_TYPE,
  CP_CAP_SHARE_FS_DEPLOYMENT_TYPE,
  CP_CAP_SHARE_FS_SIZE,
  CP_CAP_SHARE_FS_THROUGHPUT,
  CP_CAP_SHARE_FS_IOPS,

  CP_CAP_REQUESTS_CPU,
  CP_CAP_REQUESTS_GPU,
  CP_CAP_REQUESTS_RAM,
];

export const RUN_CAPABILITIES = {
  dinD: 'DinD',
  singularity: 'Singularity',
  systemD: 'SystemD',
  noMachine: 'NoMachine',
  module: 'Module',
  disableHyperThreading: 'Disable Hyper-Threading',
  dcv: 'NICE DCV',
};

export const RUN_CAPABILITIES_PARAMETERS = {
  [RUN_CAPABILITIES.dinD]: CP_CAP_DIND_CONTAINER,
  [RUN_CAPABILITIES.singularity]: CP_CAP_SINGULARITY,
  [RUN_CAPABILITIES.systemD]: CP_CAP_SYSTEMD_CONTAINER,
  [RUN_CAPABILITIES.noMachine]: CP_CAP_DESKTOP_NM,
  [RUN_CAPABILITIES.module]: CP_CAP_MODULES,
  [RUN_CAPABILITIES.disableHyperThreading]: CP_DISABLE_HYPER_THREADING,
  [RUN_CAPABILITIES.dcv]: CP_CAP_DCV,
};
