export const CP_CAP_SGE = 'CP_CAP_SGE';
export const CP_CAP_SPARK = 'CP_CAP_SPARK';
export const CP_CAP_SLURM = 'CP_CAP_SLURM';
export const CP_CAP_KUBE = 'CP_CAP_KUBE';
export const CP_CAP_AUTOSCALE = 'CP_CAP_AUTOSCALE';
export const CP_CAP_AUTOSCALE_WORKERS = 'CP_CAP_AUTOSCALE_WORKERS';
export const CP_CAP_AUTOSCALE_HYBRID = 'CP_CAP_AUTOSCALE_HYBRID';
export const CP_CAP_AUTOSCALE_PRICE_TYPE = 'CP_CAP_AUTOSCALE_PRICE_TYPE';

export const CP_CAP_DIND_CONTAINER = 'CP_CAP_DIND_CONTAINER';
export const CP_CAP_SYSTEMD_CONTAINER = 'CP_CAP_SYSTEMD_CONTAINER';
export const CP_CAP_SINGULARITY = 'CP_CAP_SINGULARITY';
export const CP_CAP_DESKTOP_NM = 'CP_CAP_DESKTOP_NM';

export const CP_CAP_LIMIT_MOUNTS = 'CP_CAP_LIMIT_MOUNTS';
