apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-git
  namespace: default
spec:
  selector:
    matchLabels:
      cloud-pipeline/cp-git: "true"
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        cloud-pipeline/cp-git: "true"
    spec:
      nodeSelector:
        cloud-pipeline/cp-git: "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
        - name: cp-git
          image: ${CP_DOCKER_DIST_SRV}lifescience/cloud-pipeline:git-$CP_GITLAB_VERSION-$CP_VERSION
          imagePullPolicy: "Always"
          ports:
            - containerPort: ${CP_GITLAB_INTERNAL_PORT}
          envFrom:
          - configMapRef:
              name: cp-config-global
          volumeMounts:
            - mountPath: /var/log/gitlab
              subPath: gitlab/logs
              name: cp-system
            - mountPath: /var/opt/gitlab
              subPath: gitlab/data
              name: cp-system
            - mountPath: /opt/gitlab/pki
              subPath: gitlab/pki
              name: cp-system
            - mountPath: /opt/idp/pki
              subPath: idp/pki
              name: cp-system
            - mountPath: /opt/common/pki
              subPath: common/pki
              name: cp-system
            - mountPath: /etc/gitlab
              subPath: gitlab/config
              name: cp-system
          # With SSO enabled - readiness probe gets redirect to IdP and fails, switched to manual ping in install.sh
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: ${CP_GITLAB_INTERNAL_PORT}
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
      volumes:
        - name: cp-system
          persistentVolumeClaim:
            claimName: cp-system-pvc
      imagePullSecrets:
        - name: cp-distr-docker-registry-secret
