#!/bin/bash

# Copyright 2017-2019 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function validate_smtp_parameter {
    local param_name="$1"
    local optional="$2"
    if [ -z "${!param_name}" ]; then
        if [ "$optional" == "true" ]; then
            echo "WARN: $param_name is not set - but proceeding with initialization"
        else
            echo "ERROR: $param_name is not set - EXITING"
            exit 1
        fi
    fi
}

validate_smtp_parameter "CP_NOTIFIER_SMTP_SERVER_HOST"
validate_smtp_parameter "CP_NOTIFIER_SMTP_SERVER_PORT" 
validate_smtp_parameter "CP_NOTIFIER_SMTP_FROM"
validate_smtp_parameter "CP_NOTIFIER_SMTP_USER" "true"
validate_smtp_parameter "CP_NOTIFIER_SMTP_PASS" "true"

NOTIFIER_RUN_TIME_LOG=$CP_NOTIFIER_HOME/logs/runtime.log
mkdir -p $(dirname $NOTIFIER_RUN_TIME_LOG)
touch $NOTIFIER_RUN_TIME_LOG

cd $CP_NOTIFIER_HOME
nohup java $CP_NOTIFIER_JAVA_OPTS -jar notifier.jar &> $NOTIFIER_RUN_TIME_LOG &

sleep 5

tail -F $NOTIFIER_RUN_TIME_LOG
