apiVersion: v1
kind: ConfigMap
metadata:
  name: cp-dnsmasq-hosts
  namespace: kube-system
data:
  hosts: |
    10.0.239.164 idp.azure.cloud-pipeline.com
    10.0.159.192 edge.azure.cloud-pipeline.com
    10.0.68.189 azure.cloud-pipeline.com
    10.0.48.158 52.170.130.140