import type {ReactNode} from 'react';
import {Link} from 'react-router-dom';
import {
  CalculatorOutlined,
  DownloadOutlined,
  ForkOutlined,
  PlayCircleOutlined,
  SettingOutlined,
  TagOutlined,
  ToolOutlined,
  UserOutlined,
} from '@ant-design/icons';
import {useQuery} from '@tanstack/react-query';
import localization from '../../utils/localization';
import UserName from '../shared/user-name';
import {dockerRegistryQueryOptions, pipelinesQueryOptions} from '../../queries';
import {AutoGeneratedTags} from './constants.ts';
import type {MetadataItem} from './types.ts';

type AutogeneratedMetadataProps = {
  items: MetadataItem[];
};

function AutogeneratedMetadata({items}: AutogeneratedMetadataProps) {
  const localizedString = localization.localization.localizedString;
  const {data: pipelines = []} = useQuery(pipelinesQueryOptions());
  const {data: dockerRegistries = {registries: []}} = useQuery(dockerRegistryQueryOptions());

  const renderRow = (
    key: string,
    title: string,
    IconComponent: typeof UserOutlined | null,
    link: string | false | null,
    value: ReactNode,
  ) => (
    <>
      <tr key={`${key}_key`} className="cp-metadata-item-row key read-only">
        <td id={`key-column-${key}`} colSpan={6} className="cp-metadata-item-key cp-ellipsis-text">
          {IconComponent ? <IconComponent /> : null} {title}
        </td>
      </tr>
      <tr key={`${key}_value`} className="cp-metadata-item-row">
        <td id={`value-column-${key}`} colSpan={6}>
          {link ? <Link to={link}>{value}</Link> : value}
        </td>
      </tr>
    </>
  );

  const ownerTag = items.find((item) => item.key === AutoGeneratedTags.owner);
  const sourceTag = items.find((item) => item.key === AutoGeneratedTags.source);
  const runIdTag = items.find((item) => item.key === AutoGeneratedTags.runId);
  const pipelineIdTag = items.find((item) => item.key === AutoGeneratedTags.job.id);
  const pipelineNameTag = items.find((item) => item.key === AutoGeneratedTags.job.name);
  const pipelineVersionTag = items.find((item) => item.key === AutoGeneratedTags.job.version);
  const pipelineConfigurationTag = items.find(
    (item) => item.key === AutoGeneratedTags.job.configuration,
  );
  const dockerImageTag = items.find((item) => item.key === AutoGeneratedTags.dockerImage);
  const calcConfigTag = items.find((item) => item.key === AutoGeneratedTags.calculationConfig);

  let pipelineName = 'Unknown';
  if (!pipelineNameTag && pipelineIdTag) {
    const pipeline = pipelines.find((entry) => `${entry.id}` === `${pipelineIdTag.value}`);
    if (pipeline) {
      pipelineName = pipeline.name;
    }
  } else if (pipelineNameTag?.value) {
    pipelineName = pipelineNameTag.value;
  }

  let dockerImageId: number | null = null;
  if (dockerImageTag?.value) {
    const [registryPath, groupName, toolWithVersion] = dockerImageTag.value.split('/');
    const [toolName] = (toolWithVersion ?? '').split(':');
    const registry = (dockerRegistries.registries ?? []).find(
      (entry) => entry.path.toLowerCase() === (registryPath || '').toLowerCase(),
    );
    const group = (registry?.groups ?? []).find(
      (entry) => entry.name.toLowerCase() === (groupName || '').toLowerCase(),
    );
    const tool = (group?.tools ?? []).find(
      (entry) => entry.image.toLowerCase() === `${groupName || ''}/${toolName}`.toLowerCase(),
    );
    if (tool) {
      dockerImageId = tool.id;
    }
  }

  return (
    <>
      {ownerTag
        ? renderRow(
            ownerTag.key,
            'Owner',
            UserOutlined,
            false,
            <UserName userName={ownerTag.value} />,
          )
        : null}
      {sourceTag
        ? renderRow(sourceTag.key, 'Source', DownloadOutlined, false, sourceTag.value)
        : null}
      {runIdTag
        ? renderRow(
            runIdTag.key,
            'RunID',
            PlayCircleOutlined,
            `/run/${runIdTag.value}`,
            runIdTag.value,
          )
        : null}
      {pipelineIdTag
        ? renderRow(
            pipelineIdTag.key,
            localizedString('Pipeline'),
            ForkOutlined,
            `/${pipelineIdTag.value}`,
            pipelineName,
          )
        : null}
      {pipelineIdTag && pipelineVersionTag
        ? renderRow(
            pipelineVersionTag.key,
            `${localizedString('Pipeline')} version`,
            TagOutlined,
            `/${pipelineIdTag.value}/${pipelineVersionTag.value}`,
            pipelineVersionTag.value,
          )
        : null}
      {pipelineIdTag && pipelineVersionTag && pipelineConfigurationTag
        ? renderRow(
            pipelineConfigurationTag.key,
            `${localizedString('Pipeline')} configuration`,
            SettingOutlined,
            `/${pipelineIdTag.value}/${pipelineVersionTag.value}/configuration/${pipelineConfigurationTag.value}`,
            pipelineConfigurationTag.value,
          )
        : null}
      {dockerImageTag
        ? renderRow(
            dockerImageTag.key,
            'Docker image',
            ToolOutlined,
            dockerImageId ? `/tool/${dockerImageId}` : null,
            dockerImageTag.value,
          )
        : null}
      {calcConfigTag
        ? (() => {
            const [instanceTypeRaw, workersCountRaw, totalCPURaw] = (
              calcConfigTag.value ?? ''
            ).split(':');
            const instanceType =
              (instanceTypeRaw || '').toLowerCase() === 'none' ? undefined : instanceTypeRaw;
            const workersCount =
              (workersCountRaw || '').toLowerCase() === 'none' ? undefined : workersCountRaw;
            const totalCPU = (totalCPURaw || '').toLowerCase() === 'none' ? undefined : totalCPURaw;
            const value = (
              <ul style={{listStyle: 'disc inside'}}>
                {instanceType ? <li>Instance type: {instanceType}</li> : null}
                {workersCount ? <li>Workers count: {workersCount}</li> : null}
                {totalCPU ? <li>Total CPU: {totalCPU}</li> : null}
              </ul>
            );
            return renderRow(calcConfigTag.key, 'Compute', CalculatorOutlined, null, value);
          })()
        : null}
    </>
  );
}

export {AutogeneratedMetadata};
