import {
  RunCapabilitiesMetadataPreference,
  METADATA_KEY as RUN_CAPABILITIES,
} from '../pipelines/launch/form/utilities/run-capabilities';
import FSNotifications from '../special/metadata/special/fs-notifications';
import LimitMountsUserPreference from '../special/metadata/special/limit-mounts';
import RequestDavAccess from '../special/metadata/special/request-dav-access';
import MuteEmailNotifications from '../special/metadata/special/mute-email-notifications';
import SshThemeSelect from '../special/metadata/special/ssh-theme-select';
import RequiredLaunchTags from '../special/metadata/special/required-launch-tags';
import type {ComponentType} from 'react';

export const AutoGeneratedTags = {
  owner: 'CP_OWNER',
  source: 'CP_SOURCE',
  runId: 'CP_RUN_ID',
  job: {
    id: 'CP_JOB_ID',
    name: 'CP_JOB_NAME',
    version: 'CP_JOB_VERSION',
    configuration: 'CP_JOB_CONFIGURATION',
  },
  dockerImage: 'CP_DOCKER_IMAGE',
  calculationConfig: 'CP_CALC_CONFIG',
} as const;

export const SpecialTags = {
  [FSNotifications.metatadaKey]: FSNotifications,
  [LimitMountsUserPreference.metatadaKey]: LimitMountsUserPreference,
  [RequestDavAccess.metatadaKey]: RequestDavAccess,
  [MuteEmailNotifications.metadataKey]: MuteEmailNotifications,
  [SshThemeSelect.metadataKey]: SshThemeSelect,
  [RUN_CAPABILITIES]: RunCapabilitiesMetadataPreference,
  [RequiredLaunchTags.metadataKey]: RequiredLaunchTags,
} as Record<string, ComponentType<Record<string, unknown>>>;

export const MetadataDisplayOptions = {
  preview: {
    maxLength: 100,
    display(value?: string) {
      if (value && value.length > this.maxLength) {
        return `${value.substring(0, this.maxLength)}...`;
      }
      return value;
    },
  },
  edit: {
    autoSize: {
      maxRows: 6,
      minRows: undefined as number | undefined,
    },
  },
};
