import {useCallback, useMemo, useState, type ReactNode} from 'react';
import classNames from 'classnames';
import {Alert, Modal, Splitter, message} from 'antd';
import LoadingView from '../special/LoadingView.tsx';
import {useSystemDictionary} from '../../queries/system-dictionaries/hooks.ts';
import {AddMetadataKeyRow} from './add-metadata-key-row.tsx';
import {AutogeneratedMetadata} from './autogenerated-metadata.tsx';
import {
  ApplyChanges,
  MetadataAddKeyState,
  MetadataChangeItem,
  MetadataEditField,
  MetadataProps,
} from './types.ts';
import {MetadataHeader} from './metadata-header.tsx';
import {MetadataItemRow} from './metadata-item-row.tsx';
import {FilePreviewPanel} from './file-preview-panel.tsx';
import {SpecialTagRow} from './special-tag-row.tsx';
import {useMetadataController} from './use-metadata-controller.ts';
import {
  isAutoGeneratedItem,
  isSpecialItem,
  getCascadeValues,
  resolveMetadataContext,
} from './utilities.ts';
import './metadata.css';

function Metadata(props: MetadataProps) {
  const {
    className,
    style,
    readOnly = false,
    hideMetadataTags = false,
    entityName,
    title,
    titleStyle,
    canNavigateBack,
    onNavigateBack,
    downloadable = true,
    showContent = true,
    removeAllAvailable = true,
    extraInfo = [],
    specialTagsProperties,
    metadataRenderFn,
    showMetadata = true,
    jobList,
    fileIsEmpty,
    openEditFileForm,
    applyChanges = ApplyChanges.inline,
  } = props;

  const context = useMemo(
    () => resolveMetadataContext(props),
    [props.entity, props.entityClass, props.entityId, props.entityParentId, props.entityVersion],
  );
  const controller = useMetadataController(props, context);
  const {
    items,
    pending,
    loaded,
    error,
    dictionaries,
    isReadOnlyTag,
    reload,
    applyChangesInternal,
    applyRemoveChanges,
    applyCascadeValues,
  } = controller;

  const [addKey, setAddKey] = useState<MetadataAddKeyState | null>(null);
  const [editableKeyIndex, setEditableKeyIndex] = useState<number | null>(null);
  const [editableValueIndex, setEditableValueIndex] = useState<number | null>(null);
  const [editableText, setEditableText] = useState<string | null>(null);

  const discardChanges = useCallback(() => {
    setAddKey(null);
    setEditableKeyIndex(null);
    setEditableValueIndex(null);
    setEditableText(null);
  }, []);

  const handleReloadAfterChange = useCallback(
    async (result: {error?: string; refresh: boolean}) => {
      if (result.error) {
        message.error(result.error, 5);
        return false;
      }
      if (result.refresh) {
        await reload();
      }
      discardChanges();
      return true;
    },
    [discardChanges, reload],
  );

  const onDeleteItem = useCallback(
    async (item: {key: string; value?: string; type?: string; index: number}) => {
      const result = await applyRemoveChanges({item});
      await handleReloadAfterChange(result);
    },
    [applyRemoveChanges, handleReloadAfterChange],
  );

  const saveMetadataValue = useCallback(
    (index: number) => async (value: string) => {
      const current = items.find((item) => item.index === index);
      if (!current || current.value === value) {
        return true;
      }
      const result = await applyChangesInternal([{...current, value}]);
      return handleReloadAfterChange(result);
    },
    [applyChangesInternal, handleReloadAfterChange, items],
  );

  const saveDictionaryMetadata = useCallback(
    (index: number) => async (value: string) => {
      const current = items.find((item) => item.index === index);
      if (!current || current.value === value) {
        discardChanges();
        return;
      }
      await applyCascadeValues(current.key, value);
    },
    [applyCascadeValues, discardChanges, items],
  );

  const saveMetadata = useCallback(
    (opts: {index?: number; field?: MetadataEditField}) => async () => {
      const {index, field} = opts;
      const modified: MetadataChangeItem[] = [];
      const removed: MetadataChangeItem[] = [];

      if (addKey) {
        if (!addKey.key?.trim()) {
          message.error('Enter key', 5);
          return;
        }
        if (items.find((item) => item.key === addKey.key.trim())) {
          message.error(`Key '${addKey.key}' already exists.`, 5);
          return;
        }
        if (!addKey.value?.length) {
          message.error('Enter value', 5);
          return;
        }
        const {result, warnings} = getCascadeValues(
          addKey.key.trim(),
          addKey.value,
          addKey.secret,
          dictionaries,
        );
        if (warnings.size > 0) {
          message.warning(
            `Error auto-filling attributes: circular dependency for "${[...warnings].join(', ')}" dictionar${warnings.size > 1 ? 'ies' : 'y'}`,
            5,
          );
        }
        modified.push(...result);
      } else if (index !== undefined && field) {
        const current = items.find((item) => item.index === index);
        if (!current) {
          return;
        }
        const value = editableText ?? '';
        if (
          (field === 'key' && current.key === value) ||
          (field === 'value' && current.value === value)
        ) {
          discardChanges();
          return;
        }
        if (field === 'key') {
          if (!value.trim()) {
            message.error('Key should not be empty', 5);
            return;
          }
          if (items.find((item) => item.index !== index && item.key === value)) {
            message.error(`Key '${value}' already exists.`, 5);
            return;
          }
          modified.push({...current, key: value.trim()});
          removed.push({...current});
        } else {
          modified.push({...current, value});
        }
      }

      const result = await applyChangesInternal(modified, removed);
      await handleReloadAfterChange(result);
    },
    [
      addKey,
      applyChangesInternal,
      dictionaries,
      discardChanges,
      editableText,
      handleReloadAfterChange,
      items,
    ],
  );

  const onEditStarted = useCallback(
    (field: MetadataEditField, index: number, value: string) => {
      if (readOnly) {
        return;
      }
      setAddKey(null);
      if (field === 'key') {
        setEditableKeyIndex(index);
        setEditableValueIndex(null);
      } else {
        setEditableKeyIndex(null);
        setEditableValueIndex(index);
      }
      setEditableText(value);
    },
    [readOnly],
  );

  const confirmDeleteMetadata = useCallback(() => {
    Modal.confirm({
      title: 'Do you want to delete all metadata?',
      style: {wordWrap: 'break-word'},
      content: null,
      okText: 'OK',
      cancelText: 'Cancel',
      onOk: async () => {
        const result = await applyRemoveChanges({all: true});
        await handleReloadAfterChange(result);
      },
    });
  }, [applyRemoveChanges, handleReloadAfterChange]);

  const editable = !readOnly && (!hideMetadataTags || !context?.isDataStorageTags);
  const visibleItems = items.filter(({key}) => !isReadOnlyTag(key));
  const addKeyDictionary = useSystemDictionary(addKey?.key);
  const existingKeys = useMemo(() => new Set(items.map((item) => item.key)), [items]);
  const availableDictionaries = useMemo(
    () =>
      dictionaries
        .map((dictionary) => dictionary.key)
        .filter((key): key is string => !!key && !existingKeys.has(key)),
    [dictionaries, existingKeys],
  );

  if (!context) {
    return (
      <div className={classNames(className, 'metadata-container')} style={style}>
        Select object to view metadata
      </div>
    );
  }

  if (pending || (!loaded && applyChanges === ApplyChanges.inline && !props.value)) {
    return <LoadingView className={undefined} style={undefined} />;
  }

  const metadataBody = error ? (
    <div key="body" style={{width: '100%', flex: 1, overflowY: 'auto', paddingTop: 10}}>
      <Alert type="error" title={error} />
    </div>
  ) : !hideMetadataTags || !context.isDataStorageTags ? (
    <div key="body" style={{width: '100%', flex: 1, overflowY: 'auto'}}>
      <table style={{width: '100%', tableLayout: 'fixed'}}>
        <tbody>
          {extraInfo.map((info, idx) => (
            <tr key={`extra-info-${idx}`}>
              <td colSpan={6}>{info}</td>
            </tr>
          ))}
          {context.isDataStorageTags ? <AutogeneratedMetadata items={visibleItems} /> : null}
          {visibleItems.map((item) => {
            if (context.isDataStorageTags && isAutoGeneratedItem(item.key)) {
              return null;
            }
            if (isSpecialItem(item.key)) {
              return (
                <SpecialTagRow
                  key={item.key}
                  item={item}
                  readOnly={readOnly || isReadOnlyTag(item.key)}
                  specialTagsProperties={specialTagsProperties}
                  onSaveValue={saveMetadataValue}
                  onRemove={onDeleteItem}
                  onReload={reload}
                />
              );
            }
            const dictionary = dictionaries.find((entry) => entry.key === item.key);
            return (
              <MetadataItemRow
                key={item.key}
                item={item}
                readOnly={readOnly || isReadOnlyTag(item.key)}
                editableKeyIndex={editableKeyIndex}
                editableValueIndex={editableValueIndex}
                editableText={editableText}
                dictionary={dictionary}
                onEditStarted={onEditStarted}
                onEditableTextChange={setEditableText}
                onDiscardChanges={discardChanges}
                onSave={saveMetadata}
                onSaveDictionary={saveDictionaryMetadata}
                onSaveValue={saveMetadataValue}
                onDelete={onDeleteItem}
              />
            );
          })}
          {items.length === 0 ? (
            <tr className="cp-text-not-important" style={{height: 40}}>
              <td colSpan={3} style={{textAlign: 'center'}}>
                No attributes set
              </td>
            </tr>
          ) : null}
        </tbody>
      </table>
    </div>
  ) : null;

  const header = (
    <table key="header" style={{width: '100%'}}>
      <MetadataHeader
        editable={editable}
        showMetadata={showMetadata}
        removeAllAvailable={removeAllAvailable}
        addKeyVisible={!!addKey}
        items={items}
        isReadOnlyTag={isReadOnlyTag}
        entityName={entityName}
        title={title}
        titleStyle={titleStyle}
        canNavigateBack={canNavigateBack}
        onNavigateBack={onNavigateBack}
        onAddKey={() => {
          discardChanges();
          setAddKey({key: '', value: '', secret: false});
        }}
        onRemoveAll={confirmDeleteMetadata}
      />
      <tbody>
        {addKey ? (
          <AddMetadataKeyRow
            addKey={addKey}
            readOnly={isReadOnlyTag(addKey.key)}
            availableDictionaries={availableDictionaries}
            dictionary={addKeyDictionary}
            onChange={(field, value) =>
              setAddKey((current) => ({
                ...(current ?? {key: '', value: '', secret: false}),
                [field]: value,
              }))
            }
            onSave={saveMetadata({})}
            onCancel={discardChanges}
          />
        ) : null}
      </tbody>
    </table>
  );

  const panels: ReactNode[] = [];
  if (context.isDataStorageTags && showContent) {
    panels.push(
      <div key="file preview" style={{display: 'flex', flexDirection: 'column', height: '100%'}}>
        <FilePreviewPanel
          context={context}
          entityName={entityName}
          fileIsEmpty={fileIsEmpty}
          downloadable={downloadable}
          metadataRenderFn={metadataRenderFn}
          openEditFileForm={openEditFileForm}
        />
      </div>,
    );
  }
  if (showMetadata && (!hideMetadataTags || !context.isDataStorageTags)) {
    panels.push(metadataBody);
  }
  if (jobList) {
    panels.push(jobList);
  }

  let body: ReactNode;
  if ((context.isDataStorageTags && showContent) || jobList) {
    if (panels.length <= 1) {
      body = panels.length === 1 ? panels[0] : metadataBody;
    } else {
      body = (
        <Splitter key="split" style={{flex: 1, overflow: 'auto'}} orientation="vertical">
          {panels.map((panel, index) => (
            <Splitter.Panel
              key={index}
              resizable
              style={{display: 'flex', flexDirection: 'column', overflow: 'hidden', minHeight: 0}}
            >
              <div
                className="cp-split-panel-panel"
                style={{
                  height: '100%',
                  display: 'flex',
                  flexDirection: 'column',
                  overflow: 'auto',
                  minHeight: 0,
                }}
              >
                {panel}
              </div>
            </Splitter.Panel>
          ))}
        </Splitter>
      );
    }
  } else {
    body = metadataBody;
  }

  return (
    <div
      className={classNames(className, 'metadata-container')}
      style={{flex: 1, display: 'flex', flexDirection: 'column', overflow: 'auto', ...style}}
    >
      {header}
      {body}
    </div>
  );
}

export {Metadata, ApplyChanges};
export {SpecialTags} from './constants.ts';
