import {SystemDictionary} from '../../@types/system-dictionaries.ts';
import {
  MetadataEntityData,
  MetadataEntityRef,
  MetadataLoadResponseItem,
} from '../../@types/metadata.ts';
import {AutoGeneratedTags, SpecialTags} from './constants.ts';
import type {MetadataChangeItem, MetadataContext, MetadataItem, MetadataProps} from './types.ts';

export function isJson(string?: string): boolean {
  if (!string) {
    return false;
  }
  try {
    const obj = JSON.parse(string);
    return !!obj && typeof obj === 'object';
  } catch {
    return false;
  }
}

export function resolveMetadataContext(props: MetadataProps): MetadataContext | undefined {
  const entityClass = props.entityClass ?? props.entity?.entityClass;
  const entityId = props.entityId ?? props.entity?.entityId;
  if (!entityClass || entityId === undefined || entityId === null || entityId === '') {
    return undefined;
  }
  const isDataStorageTags = entityClass === 'DATA_STORAGE_ITEM';
  const metadataEntity =
    !isDataStorageTags && typeof entityId === 'number'
      ? (props.entity ?? {entityId, entityClass})
      : undefined;
  return {
    entityId,
    entityClass,
    entityParentId: props.entityParentId,
    entityVersion: props.entityVersion,
    isDataStorageTags,
    metadataEntity,
  };
}

export function buildMetadataItems(options: {
  value?: MetadataEntityData;
  entityData?: MetadataLoadResponseItem;
  tags?: Record<string, string>;
  extraKeys?: string[];
}): MetadataItem[] {
  const {value, entityData, tags, extraKeys = []} = options;
  const items: Omit<MetadataItem, 'index'>[] = [];

  if (value) {
    for (const key of Object.keys(value)) {
      items.push({
        key,
        value: stringifyMetadataAttributeValue(value[key]?.value),
        type: value[key]?.type,
      });
    }
  } else if (tags) {
    for (const key of Object.keys(tags)) {
      items.push({key, value: tags[key]});
    }
  } else if (entityData?.data) {
    for (const key of Object.keys(entityData.data)) {
      items.push({
        key,
        value: stringifyMetadataAttributeValue(entityData.data[key]?.value),
        type: entityData.data[key]?.type,
      });
    }
  }

  for (const extraKey of extraKeys) {
    if (!items.find((item) => item.key === extraKey)) {
      items.push({key: extraKey});
    }
  }

  const getExtraKeyIndex = (key: string) => {
    const index = extraKeys.indexOf(key);
    return index === -1 ? Infinity : index;
  };

  return items
    .sort((a, b) => a.key.localeCompare(b.key))
    .sort(
      (a, b) =>
        Number(isSpecialItem(b.key)) - Number(isSpecialItem(a.key)) ||
        getExtraKeyIndex(a.key) - getExtraKeyIndex(b.key),
    )
    .map((item, index) => ({...item, index}));
}

function stringifyMetadataAttributeValue(value: unknown): string | undefined {
  if (value === undefined || value === null) {
    return undefined;
  }
  return String(value);
}

export function isAutoGeneratedItem(key: string): boolean {
  const autoGeneratedKeys: string[] = [
    AutoGeneratedTags.calculationConfig,
    AutoGeneratedTags.dockerImage,
    AutoGeneratedTags.job.configuration,
    AutoGeneratedTags.job.id,
    AutoGeneratedTags.job.name,
    AutoGeneratedTags.job.version,
    AutoGeneratedTags.owner,
    AutoGeneratedTags.runId,
    AutoGeneratedTags.source,
  ];
  return autoGeneratedKeys.includes(key);
}

export function isSpecialItem(key: string): boolean {
  return Object.hasOwn(SpecialTags, key);
}

export function getCascadeValues(
  key: string,
  value: string,
  secret: boolean,
  dictionaries: SystemDictionary[],
  processed: MetadataChangeItem[] = [],
): {result: MetadataChangeItem[]; warnings: Set<string>} {
  let warnings = new Set<string>();
  let result = processed.slice().concat({key, value, type: secret ? 'secret' : 'string'});
  const dictionary = dictionaries.find((dict) => dict.key === key);
  if (dictionary) {
    const dictValue = (dictionary.values ?? []).find((entry) => entry.value === value);
    if (dictValue) {
      for (const link of dictValue.links ?? []) {
        const linkKey = link.key;
        const linkValue = link.value;
        if (!linkKey || linkValue === undefined) {
          continue;
        }
        const existedLink = result.find((entry) => entry.key === linkKey);
        if (existedLink) {
          if (existedLink.value !== linkValue) {
            warnings.add(linkKey);
          }
        } else {
          const child = getCascadeValues(linkKey, linkValue, false, dictionaries, result);
          result = child.result;
          warnings = new Set([...warnings, ...child.warnings]);
        }
      }
    }
  }
  return {result, warnings};
}

export function toMetadataEntityRef(context: MetadataContext): MetadataEntityRef | undefined {
  if (context.isDataStorageTags || typeof context.entityId !== 'number') {
    return undefined;
  }
  return {entityId: context.entityId, entityClass: context.entityClass};
}

export function toMetadataEntityData(items: MetadataChangeItem[]): MetadataEntityData {
  return items.reduce<MetadataEntityData>((acc, item) => {
    acc[item.key] = {value: item.value, type: item.type || 'string'};
    return acc;
  }, {});
}
