apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-idp: "true"
  name: cp-idp
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: ${CP_IDP_INTERNAL_PORT}
    targetPort: 8080
    name: cp-idp-port-https
  selector:
    cloud-pipeline/cp-idp: "true"
