apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cp-idp
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        cloud-pipeline/cp-idp: "true"
    spec:
      nodeSelector:
        cloud-pipeline/cp-idp: "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
        - name: cp-idp
          image: quay.io/lifescience/cloud-pipeline:idp-0.17
          imagePullPolicy: "Always"
          command: ["/init"]
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: cp-config-global
          volumeMounts:
            - mountPath: /opt/idp/pki
              name: idp-pki
            - mountPath: /opt/api/pki
              name: api-pki
            - mountPath: /opt/share-srv/pki
              name: share-pki
            - mountPath: /opt/gitlab/pki
              name: git-pki
            - mountPath: /opt/common/pki
              name: common-pki
            - mountPath: /saml-idp-profiles.json
              name: idp-profiles-file
          readinessProbe:
            httpGet:
              path: /metadata
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: idp-pki
          hostPath:
            path: /opt/idp/pki
        - name: api-pki
          hostPath:
            path: /opt/api/pki
        - name: git-pki
          hostPath:
            path: /opt/gitlab/pki
        - name: share-pki
          hostPath:
            path: /opt/share-srv/pki
        - name: common-pki
          hostPath:
            path: /opt/common/pki
        - name: idp-profiles-file
          hostPath:
            path: /opt/idp/saml-idp-profiles.json
            type: FileOrCreate
      imagePullSecrets:
        - name: cp-distr-docker-registry-secret

