apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "github.com/kubernetes-sigs/aws-fsx-csi-driver/deploy/kubernetes/base/?ref=release-1.1"
  - ./resources/fsx-pv.yaml
  - ./resources/fsx-pvc.yaml
patches:
  - path: ./patches/deployment.yaml
