apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-dav: "true"
  name: cp-dav
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: ${CP_DAV_INTERNAL_PORT}
    targetPort: ${CP_DAV_INTERNAL_PORT}
    name: cp-dav-port-http
  selector:
    cloud-pipeline/cp-dav: "true"
