apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cp-node-logger
  namespace: default
  labels:
    k8s-app: cp-node-logger
spec:
  selector:
    matchLabels:
      name: cp-node-logger
  template:
    metadata:
      labels:
        name: cp-node-logger
    spec:
      containers:
      - name: cp-node-logger
        image: ${CP_DOCKER_DIST_SRV}lifescience/cloud-pipeline:node-logger-$CP_VERSION
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - name: kubelet-log
          mountPath: /var/log/kubelet
          readOnly: true
        envFrom:
        - configMapRef:
            name: cp-config-global
      volumes:
      - name: kubelet-log
        hostPath:
          path: /var/log/kubelet
