apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-edge: "true"
    cloud-pipeline/role: "EDGE"
    cloud-pipeline/region: $CP_CLOUD_REGION_ID
  name: cp-edge
  namespace: default
spec:
  ports:
  - protocol: TCP
    nodePort: ${CP_EDGE_INTERNAL_PORT}
    port: ${CP_EDGE_INTERNAL_PORT}
    targetPort: 8080
    name: cp-edge-port-https
  - protocol: TCP
    nodePort: ${CP_EDGE_WEB_INTERNAL_PORT}
    port: ${CP_EDGE_WEB_INTERNAL_PORT}
    targetPort: 8181
    name: cp-edge-port-web
  - protocol: TCP
    nodePort: ${CP_EDGE_CONNECT_INTERNAL_PORT}
    port: ${CP_EDGE_CONNECT_INTERNAL_PORT}
    targetPort: 8282
    name: cp-edge-port-connect
  type: NodePort
  selector:
    cloud-pipeline/cp-edge: "true"
