apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cp-edge-${CP_ADDITION_REGION}
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        cloud-pipeline/cp-edge: "true"
        cloud-pipeline/role: "EDGE"
        cloud-pipeline/region: $CP_CLOUD_ADDITIONAL_REGION_ID
        cloud-pipeline/core-component: "Deployment"
    spec:
      nodeSelector:
        cloud-pipeline/cp-edge: "true"
        cloud-pipeline/region: $CP_CLOUD_ADDITIONAL_REGION_ID
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
        - name: cp-edge
          image: ${CP_DOCKER_DIST_SRV}lifescience/cloud-pipeline:edge-$CP_VERSION
          imagePullPolicy: "Always"
          command: ["/init"]
          env:
          - name: NODE_OPTIONS
            value: "--max_old_space_size=4096"
          - name: CP_EDGE_REGION
            value: "$CP_CLOUD_ADDITIONAL_REGION_ID"
          - name: EDGE_EXTERNAL
            value: "${CP_EDGE_ADDITIONAL_EXTERNAL}"
          - name: CP_EDGE_EXTERNAL_HOST
            value: "${CP_EDGE_ADDITIONAL_EXTERNAL_HOST}"
          - name: CP_EDGE_EXTERNAL_PORT
            value: "${CP_EDGE_ADDITIONAL_EXTERNAL_PORT}"
          envFrom:
          - configMapRef:
              name: cp-config-global
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /liveness.sh
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 4
          volumeMounts:
            - mountPath: /var/log
              name: edge-logs
            - mountPath: /opt/api/pki
              name: api-pki
              readOnly: true
            - mountPath: /opt/gitlab/pki
              name: gitlab-pki
              readOnly: true
            - mountPath: /opt/docker-registry/pki
              name: docker-pki
              readOnly: true
            - mountPath: /opt/idp/pki
              name: idp-pki
              readOnly: true
            - mountPath: /opt/edge/pki
              name: edge-pki
              readOnly: true
            - mountPath: /opt/common/pki
              name: common-pki
              readOnly: true
            - mountPath: /etc/nginx/external-apps
              name: edge-external-apps
            - mountPath: /opt/share-srv/pki
              name: share-pki
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      volumes:
        - name: edge-logs
          hostPath:
            path: /opt/edge/logs/$CP_CLOUD_ADDITIONAL_REGION_ID
        - name: api-pki
          hostPath:
            path: /opt/api/pki
        - name: gitlab-pki
          hostPath:
            path: /opt/gitlab/pki
        - name: docker-pki
          hostPath:
            path: /opt/docker-registry/pki/
        - name: idp-pki
          hostPath:
            path: /opt/idp/pki/
        - name: edge-pki
          hostPath:
            path: /opt/edge/pki
        - name: common-pki
          hostPath:
            path: /opt/common/pki
        - name: edge-external-apps
          hostPath:
            path: /opt/edge/external-apps
        - name: share-pki
          hostPath:
            path: /opt/share-srv/pki
      imagePullSecrets:
        - name: cp-distr-docker-registry-secret
