apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-docker-registry: "true"
  name: cp-docker-registry
  namespace: default
spec:
  ports:
  - protocol: TCP
    nodePort: ${CP_DOCKER_INTERNAL_PORT}
    port: ${CP_DOCKER_INTERNAL_PORT}
    targetPort: 443
    name: cp-docker-registry-port-https
  type: NodePort
  selector:
    cloud-pipeline/cp-docker-registry: "true"
