apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-docker-comp: "true"
  name: cp-docker-comp
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: ${CP_DOCKER_COMP_INTERNAL_PORT}
    targetPort: 8080
    name: cp-docker-comp-port-http
  selector:
    cloud-pipeline/cp-docker-comp: "true"
