#!/bin/bash
#
# Copyright 2017-2026 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Schedules a periodic repair of the broken docker registry tags, see repair-dangling-tags.sh,
# and starts a cron daemon. Runs once at a container startup and does nothing at all,
# unless CP_DOCKER_REPAIR_TAGS_ENABLED is set to true.
#
# Configuration (environment variables):
#
#   CP_DOCKER_REPAIR_TAGS_ENABLED  set to true to check and repair the broken tags periodically,
#                                  false by default
#   CP_DOCKER_REPAIR_TAGS_CRON     a schedule of a repair in a cron format, `0 0 * * *`
#                                  by default, i.e. every day at midnight
#   CP_DOCKER_REPAIR_TAGS_LOG      a log file of a repair and of a cron daemon itself,
#                                  /var/log/repair-dangling-tags.log by default
#   CP_DOCKER_REPAIR_TAGS_SCRIPT   a path to a repair script, /repair-dangling-tags.sh by default
#
# A repair itself is configured by the CP_DOCKER_* variables of repair-dangling-tags.sh, e.g.
# CP_DOCKER_DRY_RUN, CP_DOCKER_MAX_REMOVALS or CP_DOCKER_EXCLUDE_REPOSITORIES.
#
# A cron job does not inherit an environment of a container, therefore all the CP_* variables
# are dumped to a file at a startup and are restored by a job before a repair. A dump contains
# a Cloud Pipeline access token and thus is readable by its owner only.
#
# A registry startup shall not be affected by an inability to schedule a repair, so that any issue
# is reported and ignored.
#

set -o errexit
set -o nounset
set -o pipefail

CP_DOCKER_REPAIR_TAGS_ENABLED="${CP_DOCKER_REPAIR_TAGS_ENABLED:-false}"
CP_DOCKER_REPAIR_TAGS_CRON="${CP_DOCKER_REPAIR_TAGS_CRON:-0 0 * * *}"
CP_DOCKER_REPAIR_TAGS_LOG="${CP_DOCKER_REPAIR_TAGS_LOG:-/var/log/repair-dangling-tags.log}"
CP_DOCKER_REPAIR_TAGS_SCRIPT="${CP_DOCKER_REPAIR_TAGS_SCRIPT:-/repair-dangling-tags.sh}"

ENVIRONMENT_FILE="${CP_DOCKER_REPAIR_TAGS_ENVIRONMENT:-/repair-dangling-tags.env}"
JOB_FILE="${CP_DOCKER_REPAIR_TAGS_JOB:-/repair-dangling-tags-cron.sh}"
LOCK_FILE="${CP_DOCKER_REPAIR_TAGS_LOCK:-/var/run/repair-dangling-tags.lock}"

function log() {
    echo "[repair-dangling-tags] $*"
}

# Reports an issue and exits successfully: a registry shall start even without a scheduled repair.
function skip() {
    log "ERROR: $*, a periodic repair of the broken tags is not scheduled"
    exit 0
}

# Dumps the Cloud Pipeline variables of a container, so that a cron job can restore them.
function save_environment() {
    local variable
    : > "$ENVIRONMENT_FILE"
    # An access token is dumped as well, so that a file is never exposed to the other users
    chmod 600 "$ENVIRONMENT_FILE"
    for variable in $(env | sed -n 's/^\(CP_[A-Za-z0-9_]*\)=.*/\1/p' | sort); do
        # A value is quoted by a shell itself, so that the special characters are kept as is
        printf 'export %s=%q\n' "$variable" "${!variable}" >> "$ENVIRONMENT_FILE"
    done
}

# Generates a job, that is executed by cron: an environment of a container is restored and a repair
# is started under a lock, so that the runs, that take longer than a schedule interval, do not pile
# up on each other.
function save_job() {
    local lock=""
    if command -v flock > /dev/null 2>&1; then
        # A short option is used, as a busybox flock does not support the long ones
        lock="flock -n ${LOCK_FILE} "
    else
        log "WARN: flock is not installed, the concurrent repairs are not prevented"
    fi
    cat > "$JOB_FILE" <<EOF
#!/bin/bash
# Generated by setup_cron.sh at a container startup, see it for the details.
source "${ENVIRONMENT_FILE}"
${lock}bash "${CP_DOCKER_REPAIR_TAGS_SCRIPT}"
EOF
    chmod +x "$JOB_FILE"
}

# Schedules a job, keeping the other cron jobs, if any, and replaces a job of a previous startup.
function schedule_job() {
    local schedule="$1"
    {
        crontab -l 2>/dev/null | grep -vF -- "$JOB_FILE" || true
        echo "${schedule} ${JOB_FILE} >> ${CP_DOCKER_REPAIR_TAGS_LOG} 2>&1"
    } | crontab -
}

function main() {
    local required schedule
    if [ "$CP_DOCKER_REPAIR_TAGS_ENABLED" != "true" ]; then
        log "A periodic repair of the broken tags is disabled, "\
"set CP_DOCKER_REPAIR_TAGS_ENABLED=true to enable it"
        exit 0
    fi
    for required in crond crontab bash curl jq; do
        command -v "$required" > /dev/null 2>&1 || skip "${required} is not installed"
    done
    [ -f "$CP_DOCKER_REPAIR_TAGS_SCRIPT" ] \
        || skip "${CP_DOCKER_REPAIR_TAGS_SCRIPT} does not exist"
    # An invalid schedule is rejected by a cron daemon silently, i.e. a repair would never run
    schedule="$(echo "$CP_DOCKER_REPAIR_TAGS_CRON" | tr -s '[:space:]' ' ' \
                | sed -e 's/^ //' -e 's/ $//')"
    echo "$schedule" | grep -Eq '^(@[a-z]+|[^ ]+( [^ ]+){4})$' \
        || skip "CP_DOCKER_REPAIR_TAGS_CRON \"${CP_DOCKER_REPAIR_TAGS_CRON}\" is not a schedule "\
"of 5 fields, e.g. \"0 0 * * *\""

    save_environment
    save_job
    schedule_job "$schedule"

    mkdir -p "$(dirname "$CP_DOCKER_REPAIR_TAGS_LOG")"
    touch "$CP_DOCKER_REPAIR_TAGS_LOG"
    if pgrep -x crond > /dev/null 2>&1; then
        log "A cron daemon is already running"
    elif ! crond -b -L "$CP_DOCKER_REPAIR_TAGS_LOG"; then
        skip "cannot start a cron daemon"
    fi
    log "A repair of the broken tags is scheduled as \"${schedule}\", "\
"see ${CP_DOCKER_REPAIR_TAGS_LOG} for its output"
}

main "$@"
