#!/bin/bash

# Copyright 2017-2023 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

CP_NF_WORKDIR="${CP_NF_WORKDIR:-${ANALYSIS_DIR}/work}"
CP_NF_TRACE_FILE="${CP_NF_TRACE_FILE_DIR:-$CP_NF_WORKDIR}/trace.txt"
CP_NF_RUNTIME_DATA_SYNC_PERIOD=${CP_NF_RUNTIME_DATA_SYNC_PERIOD:-300}
CP_NF_RUNTIME_DATA_SYNC_BACKOFF_SEC=6

export NXF_WORK="$CP_NF_WORKDIR"
mkdir -p "$NXF_WORK"

_IS_RUN_COMMAND=
for param in "$@"; do
   if [ "$param" == "run" ]; then
      _IS_RUN_COMMAND="1"
      break
   fi
done

NEXTFLOW_CONFIG="/etc/nextflow/nextflow.config"
mkdir -p $(dirname "$NEXTFLOW_CONFIG")
rm -f "$NEXTFLOW_CONFIG"

if [ "$CP_CAP_SINGULARITY" == "true" ]; then
    echo "singularity.enabled = true" >> $NEXTFLOW_CONFIG
elif [ "$CP_CAP_DIND_CONTAINER" == "true" ]; then
    echo "docker.enabled = true" >> $NEXTFLOW_CONFIG
    if nvidia-smi >/dev/null 2>&1; then
        echo "docker.runOptions = '-u \$(id -u):\$(id -g) --privileged --runtime=nvidia'" >> $NEXTFLOW_CONFIG
    else
        echo "docker.runOptions = '-u \$(id -u):\$(id -g) --privileged'" >> $NEXTFLOW_CONFIG
    fi
fi

if [ "$CP_CAP_SGE" == "true" ]; then
    echo "process.executor = 'sge'" >> $NEXTFLOW_CONFIG
    echo "process.penv = 'local'" >> $NEXTFLOW_CONFIG
    echo "process.queue = 'main.q'" >> $NEXTFLOW_CONFIG
    echo "process.clusterOptions = '-V'" >> $NEXTFLOW_CONFIG
fi

_ARGS=("$@")
if [ -f "$NEXTFLOW_CONFIG" ]; then
    _ARGS+=('-c')
    _ARGS+=("$NEXTFLOW_CONFIG")
fi

if [ "$_IS_RUN_COMMAND" == "1" ]; then
    if [ "$CP_NF_WEBLOG_HANDLER_ENABLED" == "1" ] && /opt/nf-weblog-handler/nf-weblog-handler.sh --check ; then
        echo "Running Nextflow with -with-weblog http://localhost:${CP_NF_WEBLOG_HANDLER_PORT:-8080}/nextflow/event option"
        _ARGS+=('-with-weblog')
        _ARGS+=("http://localhost:${CP_NF_WEBLOG_HANDLER_PORT:-8080}/nextflow/event")
        if [ -n "$CP_NF_WORKDIR" ]; then
            _ARGS+=('-with-trace')
            _ARGS+=("${CP_NF_TRACE_FILE}")
        fi
    fi
fi

$NXF_HOME/nextflow "${_ARGS[@]}"

if [ "$_IS_RUN_COMMAND" == "1" ]; then
    if [ "$CP_NF_WEBLOG_HANDLER_ENABLED" == "1" ] && sync_to_storage check &> /dev/null ; then
        echo "Nextflow process finished. Waiting for synchronization of nextflow task runtime files... "
        _wait_count=0
        while [ "$_wait_count" -lt "$((CP_NF_RUNTIME_DATA_SYNC_PERIOD / CP_NF_RUNTIME_DATA_SYNC_BACKOFF_SEC))" ]; do
          _wait_count=$((_wait_count + 1))
          _files_to_sync=$(sync_to_storage count)
          if [ "$?" -eq 0 ] && [ "$_files_to_sync" -eq "0" ]; then
              echo "Synchronization of nextflow task runtime files finished."
              exit 0
          fi
          sleep $CP_NF_RUNTIME_DATA_SYNC_BACKOFF_SEC
        done
        echo "[WARN] Synchronization of nextflow task runtime files can't finished in configured time, not all files would be available in statistic report. Exiting!"
        exit 0
    fi
fi

