#!/bin/bash

# Copyright 2017-2023 EPAM Systems, Inc. (https://www.epam.com/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function generate_params_file() {
    all_cp_params_json=""
    all_cp_params=$(printenv | sed 's;=.*;;' | grep _PARAM_TYPE)
    for cp_param in $all_cp_params; do
        [[ "$cp_param" =~ CP_* ]]  && continue
        cp_param_clean=$(echo "$cp_param" | sed 's/_PARAM_TYPE//')
        all_cp_params_json="${all_cp_params_json},\"$cp_param_clean\": \"${!cp_param_clean}\""
    done
    all_cp_params_json="{ $(echo "$all_cp_params_json" | sed 's/,//') }"
    echo "$all_cp_params_json" | jq -r > "$CP_NF_AUTOGENERATE_PARAMETERS_PATH"
    echo "[INFO] Parameters are written into $CP_NF_AUTOGENERATE_PARAMETERS_PATH"
    echo "[INFO] Parameters JSON:"
    cat "$CP_NF_AUTOGENERATE_PARAMETERS_PATH"
}

CP_NF_WORKDIR="${CP_NF_WORKDIR:-${ANALYSIS_DIR}/work}"
CP_NF_TRACE_FILE="${CP_NF_TRACE_FILE_DIR:-$CP_NF_WORKDIR}/trace.txt"
CP_NF_RUNTIME_DATA_SYNC_PERIOD=${CP_NF_RUNTIME_DATA_SYNC_PERIOD:-300}
CP_NF_RUNTIME_DATA_SYNC_BACKOFF_SEC=10
CP_NF_AUTOGENERATE_PARAMETERS_PATH="${CP_NF_AUTOGENERATE_PARAMETERS_PATH:-$SCRIPTS_DIR/cp_params.json}"

export NXF_WORK="$CP_NF_WORKDIR"
mkdir -p "$NXF_WORK"

_IS_RUN_COMMAND=
for param in "$@"; do
   if [ "$param" == "run" ]; then
      _IS_RUN_COMMAND="1"
      break
   fi
done

_ARGS=("$@")

NEXTFLOW_CONFIG="/etc/nextflow/nextflow.config"
mkdir -p $(dirname "$NEXTFLOW_CONFIG")
rm -f "$NEXTFLOW_CONFIG"

if [ "$CP_CAP_SINGULARITY" == "true" ]; then
    echo "singularity.enabled = true" >> $NEXTFLOW_CONFIG
elif [ "$CP_CAP_DIND_CONTAINER" == "true" ]; then
    echo "docker.enabled = true" >> $NEXTFLOW_CONFIG
    if nvidia-smi >/dev/null 2>&1; then
        echo "docker.runOptions = '-u \$(id -u):\$(id -g) --privileged --runtime=nvidia'" >> $NEXTFLOW_CONFIG
    else
        echo "docker.runOptions = '-u \$(id -u):\$(id -g) --privileged'" >> $NEXTFLOW_CONFIG
    fi
fi

if [ "$CP_CAP_SGE" == "true" ]; then
    echo "process.executor = 'sge'" >> $NEXTFLOW_CONFIG
    echo "process.penv = 'local'" >> $NEXTFLOW_CONFIG
    echo "process.queue = 'main.q'" >> $NEXTFLOW_CONFIG
    echo "process.clusterOptions = '-V'" >> $NEXTFLOW_CONFIG
fi

if [ "$_IS_RUN_COMMAND" == "1" ]; then
    if [ "$CP_NF_WEBLOG_HANDLER_ENABLED" == "1" ] && /opt/nf-weblog-handler/nf-weblog-handler.sh --check ; then
        echo "Running Nextflow with -with-weblog http://localhost:${CP_NF_WEBLOG_HANDLER_PORT:-8080}/nextflow/event option"
        _ARGS+=('-with-weblog')
        _ARGS+=("http://localhost:${CP_NF_WEBLOG_HANDLER_PORT:-8080}/nextflow/event")
        if [ -n "$CP_NF_WORKDIR" ]; then
            echo "trace.enabled = true" >> $NEXTFLOW_CONFIG
            echo "trace.raw = true" >> $NEXTFLOW_CONFIG
            echo "trace.file = '${CP_NF_TRACE_FILE}'" >> $NEXTFLOW_CONFIG
            echo "trace.fields = 'task_id,hash,native_id,process,tag,name,status,exit,module,container,cpus,time,disk,memory,attempt,submit,start,complete,duration,realtime,queue,%cpu,%mem,rss,vmem,peak_rss,peak_vmem,rchar,wchar,syscr,syscw,read_bytes,write_bytes'" >> $NEXTFLOW_CONFIG
        fi
    fi

    if [ "$CP_NF_AUTOGENERATE_PARAMETERS" == "true" ]; then
        generate_params_file
        _ARGS+=("-params-file" "$CP_NF_AUTOGENERATE_PARAMETERS_PATH")
    fi
fi

if [ -f "$NEXTFLOW_CONFIG" ]; then
    _ARGS+=('-c')
    _ARGS+=("$NEXTFLOW_CONFIG")
fi

$NXF_HOME/nextflow "${_ARGS[@]}"
_result_code="$?"

if [ "$_IS_RUN_COMMAND" == "1" ]; then
    /opt/nf-weblog-handler/nf-weblog-handler.sh --wait-runtime-data -tf "$CP_NF_TRACE_FILE"
fi

exit $_result_code

