plugins {
    id 'idea'
    id 'java'
    id 'org.sonarqube' version '2.6.1'
    id 'org.springframework.boot' version '3.5.3'
    id 'io.spring.dependency-management' version '1.1.7'
}

group 'com.epam.pipeline'
version '1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

jar {
    archiveFileName = 'docker-comp-scan.jar'
}

configurations {
    all*.exclude module: 'spring-boot-starter-logging'
    all*.exclude group: 'commons-logging', module: 'commons-logging'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-log4j2'
    implementation 'com.google.code.findbugs:annotations:3.0.1'
    implementation 'com.google.guava:guava:26.0-jre'
    implementation 'org.apache.commons:commons-compress:1.18'
    implementation 'org.owasp:dependency-check-core:3.3.2'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.9.6'
    implementation 'com.squareup.okhttp3:okhttp:3.11.0'
    implementation 'org.projectlombok:lombok:1.18.34'

    annotationProcessor 'org.projectlombok:lombok:1.18.34'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.projectlombok:lombok:1.18.34'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.34'
}