name: Cloud-Pipeline-CLI-Mac-Arm64

concurrency: Cloud-Pipeline-CLI-Mac-Arm64

on:
  push:
    branches:
      - develop
      - 'release/**'
      - 'stage/**'

  workflow_dispatch:

env:
  CLOUD_PIPELINE_BUILD_NUMBER_SEED: 300000

jobs:
  CLI_MacOS:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - run: bash deploy/github_actions/gha_build_pipe_macos.sh
