name: CI

on:
  push:
    branches:
      - develop
      - 'release/**'
      - 'stage/**'
      - gha

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-python@v2
        with:
          python-version: '2.7.18'
          architecture: 'x64'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: CLI_MacOS
        run: bash deploy/github_actions/gha_build_macos.sh
