name: Cloud-Pipeline-Distribution

concurrency: Cloud-Pipeline-Distribution

# We build only develop, until the GHA is proved working correctly
on:
  push:
    branches:
      - develop
      - 'release/**'
      - 'stage/**'

  workflow_dispatch:

env:
  CLOUD_PIPELINE_BUILD_NUMBER_SEED: 20000

jobs:
  CLI_MacOS_Arm:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'arm64'
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - run: bash deploy/github_actions/gha_build_macos_arm.sh
        env:
          MAC_SIGN_IDENTITY: ${{ secrets.MAC_SIGN_IDENTITY }}
          MAC_SIGN_KEYCHAIN: ${{ secrets.MAC_SIGN_KEYCHAIN }}
          MAC_SIGN_KEYCHAIN_PASSWORD: ${{ secrets.MAC_SIGN_KEYCHAIN_PASSWORD }}
          MAC_SIGN_P12: ${{ secrets.MAC_SIGN_P12 }}
          MAC_SIGN_P12_PASSWORD: ${{ secrets.MAC_SIGN_P12_PASSWORD }}
          PIPE_CLI_REQUIRES_SIGNING: ${{ secrets.PIPE_CLI_REQUIRES_SIGNING }}
  Build_All:
    runs-on: ubuntu-22.04
    needs:
    - CLI_MacOS_Arm
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - run: sudo -E bash deploy/github_actions/gha_pack_dist.sh
        env:
          CP_DOCKER_DIST_SRV: ${{ secrets.CP_DOCKER_DIST_SRV }}