name: Cloud-Pipeline-Distribution

concurrency: Cloud-Pipeline-Distribution

on:
  push:
    branches:
      - develop
      - 'release/**'
      - 'stage/**'
      - 'ci/**'

  workflow_dispatch:

env:
  CLOUD_PIPELINE_BUILD_NUMBER_SEED: 30000

jobs:
  CLI_MacOS:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - run: bash deploy/github_actions/gha_build_macos.sh
  Build_All:
    runs-on: ubuntu-20.04
    needs: CLI_MacOS
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - run: sudo -E PATH=$PATH bash deploy/github_actions/gha_pack_dist.sh
